### ISSUE TITLE
"Frontverlaufsmodul"

### ISSUE THREAD

**Issue by Nimrod489** [TacticalBaconDevs/TBMod#101]
Wäre es möglich etwas zu skripten das in Arma die Grids auf der Karte Einfärbt je nach dem was sich innerhalb des Grids befindet, um somit Atmosphärisch und für jeden sichtbar einen "Frontverlauf" darstellen zu können. Dieses Modul sollte auch für normale Missionen genutzt werden können um Feindgebiet besser darstellen zu können:

Funktionen:
- Grid wird je nach besetzender Fraktion Eingefärbt (BLUEFOR=Blau, Opfor=Rot, Independent=Grün)

- Größe des Grid was eingefärbt wird, kann bestimmt werden.

- Grid soll auf einzelne Einheit reagieren wenn diese den Grid betritt und wird erst umgefärbt wenn a.) keine gegnerische Fraktion mehr sich im Grid aufhällt b.) eine übermacht z.B 1:2 herrscht (am besten einstellbar welches von beiden aktiv genutz wird)

-Grid aktualisiert sich erst bei überschreiten der Linie um Serverressourcen zu schonen, somit keine ständige abfrage nötig. 

-Grid sollen vorab eingeteilt werden können:  z.B Karte Altis, Linke seite Blau, Rechte seite Rot oder Individualisiert einstellbar sein welche Grids Grün und welche Rot.

Ich denke es wäre eine coole Ergänzung für einen Missionbauer der Kampangen Missionen plant um den Spielern das Feindgebiet besser darstellen zu können.
Dazu hat jeder Spieler für sich ein Optisches Feedback wie es den Momentan aussieht.
Ebenfalls für kleinere Missionen gut einsetzbar um den Spieler klare grenzen darstellen zu können wenn erwünscht.

+ Das es vlt. für den ein oder anderen eine Phsychologische positive Wirkung erzielen kann auch wenn es gerade hart läuft das trotzdem zu sehen das Feindgebiet genommen wird.

Wäre aufjedenfall ne feine sache wenn alles an Funktionen umsetzbar wäre bei rückfragen gerne auf mich zukommen. :)

Gruß Nimrod

**Comment by shukari** [comment]
Alles bis auf Übermachtverhältnis umgesetzt, derzeit simples wenn eine Seite mehr ist, dann eingefärbt.
