### ISSUE TITLE
BW Default Loadouts kontrollieren/anpassen

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#104]
@IDarky bitte die defaultLoadouts in https://github.com/TacticalBaconDevs/TBMod/blob/4a2474d6a4a1d5bf28a1658bfb56aa61ab274d58/addons/TBMod_arsenal/functions/fn_loadDefault.sqf#L35-L58 überprüfen, DMR war zB noch alte Waffe usw.

**Comment by IDarky** [comment]
fix ist in #107
