### ISSUE TITLE
Ki Medic- und Loadoutsystem

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#124]
Wäre cool wenn wir ein Skript oder Mod hätten, wo sich die Ki selbst verarztet und/oder weggezogen bzw.getragen wird. (Hätte da ein Beispielskript für euch)
~~Genauso cool wäre es wenn sich die Ki wieder selbstständig bei ihren gefallenen Kameraden oder an einem Fahrzeuge (Gleiche Fraktion wie die Ki) selbst neu aufmunitioniert.~~

**Comment by shukari** [comment]
1. Munition nimmt sie bereits von Toten durch VCOM auf
2. Das die KI sich verarztet, hatte ich damals aus gemacht, als ich alles in ACE3 deaktiviert hatte zum Performance sparen. Werde ich wieder an machen.
3. Das mit dem wegtragen finde ich einmal in einer Mission lustig, aber es ist meiner Meinung nach nicht förderlich, da die KI dann manchmal noch dümmer ist, weil sie auf dem offenen Feld Leute weg trägt... wäre Diskussions betraf.

**Comment by Culli-TB** [comment]
Zu 3) Vertsehe ich, habe es selbst schon mitbekommen :D

**Comment by shukari** [comment]
zu 2) habe ich wieder angemacht auf dem Server
zu 3) würde ich lasse, ggf in den Missions verwenden, wenn es passt
