### ISSUE TITLE
Tactical Beard (Dark) + VR-Brille

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#126]
Wenn jmd. es schafft diese zwei Sachen zu einer zu kombinieren, trage ich es bis ans Ende von TB.

SFG_Tac_BeardD + G_Goggles_VR

**Comment by shukari** [comment]
Außer jemand kennt sich gut mit 3d Objekten aus und kann p3d zusammen mergen, sonst schließe ich das jetzt hier, denn ich kann es nicht.
