### ISSUE TITLE
AL-6 Drohne ins Arsenal

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#136]
Anfrage, dass der Drohnen Operator neben der bisherigen AL-2 auch die AL-6 zur Verfügung gestellt wird. Die Rolle bekäme damit eine weitere Funktion und kann in gewissen Maße die Logistik für abgeschnittene, schnell zu unterstützende oder weiter entfernte Teileinheiten stellen.

**Comment by Er1807** [comment]
@shukari ist das genehmigt? Dann füge ich es ein.

**Comment by shukari** [comment]
Jop
