### ISSUE TITLE
Sanizelt optimieren

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#139]
Verschnellerte Behandlung. Darf nicht mehr Kaputt gehen durch platzieren von anderen Items

**Comment by shukari** [comment]
@Er1807 
Weiß nicht was das Beste ist. Entweder eine Ace3-AddAction drauf oder irgendwie alle x Sekunden alle im/am Zelt heilen...

**Comment by Er1807** [comment]
Hatte keine Notifikation bekommen(oder direkt gelöscht.)
Wie wäre es mit einem over time effekt. Pro Sekunde werden x Wunden gechlossen/genäht.

**Comment by shukari** [comment]
@Er1807 Wäre möglich, vll nur zunähen lassen, dann müssten wir einen pefh bei allen Spielern laufen lassen, der immer wenn man bei MedicHäusern ist etwa, das hier ausführt -> https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_surgicalKit_onProgress.sqf
