### ISSUE TITLE
Arzt überarbeiten

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#145]
- [ ] Arsenal optimieren
- [ ] besser als Sani machen (schneller behandeln)

**Comment by E-for-Eron** [comment]
Sollte der Arzt nur für MedEvac Aufgaben zuständig sein und damit PDW´s als Bewaffnung erhalten oder soll er auch am Kampfgeschehen dran teilnehmen?

**Comment by shukari** [comment]
Nur MedEvac

**Comment by E-for-Eron** [comment]
Vorschlag: alle Sturmwaffen aus dem Arsenal des Arztes und nur Waffensysteme vergleichbar mit der MP7 rein.
Neben schnellerer Behandlung könnte man einführen, dass bis auf Sani/Arzt alle nur "QuikClots" im Arsenal haben; Kampfsanis auf einfache Bandagen und Ärzte auf elastische Bandagen Zugriff haben. Desweiteren könnte man dem Kampfsani große/mittelgroße Rucksäcke entfernen und durch kleinere austauschen, sodass er nicht soviel an SanMat transportieren kann, da er verpflichtet ist als Priorität genügend Munition mitzuführen.

**Comment by Er1807** [comment]
#153

**Comment by shukari** [comment]
Duplicate of #153
alles aus diesem Issue, wird dort behandelt.
