### ISSUE TITLE
Briefingübersicht

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#146]
- [ ] im Briefing (Karte links oben), die Sanisettings anzeigen
- [ ] ggf auch andere Übersichten erstellen

Quelle & Idee: https://github.com/Schwaggot/kellerkompanie-mods/blob/master/addons/common/functions/fnc_addBriefingEntries.sqf

**Comment by Er1807** [comment]
Würde mich später mal dransetzen. Was sollte da alles Dazu? Welche Sanisettings etc?

**Comment by shukari** [comment]
- PAK/SurgKit/DEFI
    - ob verbraucht
    - wo zu nutzen
    - welche Kondition (verbunden/immer)
    - wer kann
- Revive Zeit in min
- wenn dir noch andere Sachen einfallen die immer mal gefragt werden von den Serversettings

**Comment by shukari** [comment]
Habe mich rangesetzt, ist drin, allerdings ungetestet.

**Comment by shukari** [comment]
wie gesagt ungetestet... wird überprüft, aufgrund #169
