### ISSUE TITLE
EOS Eron Patrol Laufen nur auf Straßen oder freien Gebiet. ohne Bäume

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#149]
Patrols und Fahrzeuge nutzen beide TB_fnc_shk_patrol. Diese nutzt TB_EOS_fnc_findSafePos mit glaube Size 10 
`_wps pushBack ([_mkrPos, 0, _mkrSize, 10, _waterMode, 0.25, 0] call TB_EOS_fnc_findSafePos);`
Sollte vlt. nen Parameter hinzugefügt werden, der es auf 1 setzt für Infantrie.

**Comment by E-for-Eron** [comment]
[https://imgur.com/a/gqQZYFR](url)

**Comment by E-for-Eron** [comment]
https://imgur.com/a/gqQZYFR
