### ISSUE TITLE
Rucksäcke/Inventar/Spezialrollen

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#151]
### Aufgaben
- [x] https://github.com/TacticalBaconDevs/TBMod/issues/151#issuecomment-474462399

### Ursprünglicher Text
Anfrage für den Generalsstab zur Änderung welche Rollen Rucksäcke nutzen sollen. 
Vorschlag, folgende Rollen behalten ihren Rucksack:
- Truppführer, Kampfsanitäter Sprengmeister, Pionier, Munitionsträger, Anti-Fahrzeug, Sniper, Spotter, UAV Operator (nur die Drohnenrucksäcke), Arzt

Alle anderen Rollen sollen Rucksäcke nicht mehr nutzen dürfen, um den Rollen wie dem Munitionsträger, Anti-Fahrzeug etc mehr Bedeutung zuzuschreiben und die Interaktion zwischen den Spielern zu erhöhen. 

Rucksäcke sollen auf Wunsch nicht aus dem Arsenal gelöscht werden, sondern dem Missionsbauern die Freiheit geben Missionen mit oder ohne Rucksäcke zu ermöglichen.

Eine Reduktion der One-Use-Raketenwerfer oder Beschränkung auf HP würde dem AT-Schützen ebenso eine größere Bedeutung beimessen. Derzeit werden meist SPz als Feindfahrzeuge verwendet, die auf kurze Entfernung schnell von jedem Soldaten ausgeschaltet werden und ein AT-Schütze fast immer mitgenommen, aber nicht tatsächlich gebraucht wird. 
AT-S/AA-S werden aktuell nur gegen KPz oder Lufteinheiten benötigt.

Desweiteren könnten Schützen Vorteile in ihrer Ausrüstung gebrauchen, um die Rolle attraktiver bzw sinnvoller zu machen. Denn um ehrlich zu sein, wird praktisch niemals der Schütze gespielt. Warum auch, wenn ein Grenadier die gleiche Rolle nur mit ULG-Granaten zusätzlich ist? Würde man nur dem Schützen bspweise die Möglichkeit geben Spaten und One-Use-Raketenwerfer o.ä zu nutzen, würde die Rolle an Bedeutung gewinnen. 
(ein Missionserbauer hat logischerweise die Möglichkeit eine Maximalanzahl an Spezialrollen für eine Mission festzuschreiben und damit Personen auf die Schützenrolle zu zwingen, sodass eine Attraktivitätssteigerung der Schützenrolle nicht zwangsweise nötig ist)

**Comment by shukari** [comment]
Persönlich aus Text genommene Punkte, Umsetzung ist damit aber noch nicht beschlossen:
- [ ] Rucksäcke per Einstellung (Missionbauer kann per EdenAttribut bestimmen)
- [ ] One-UseRockets beschränken, ggf nur noch leichte Variante (auch Nachschub)
- [ ] One-UseRocket ggf schwerer machen, damit die Entscheidung bewusster getroffen werden muss
- [ ] normalen Soldatenslot mehr definieren (ggf nur ehr kann One-Use nehmen... ggf noch mehr Spezialitäten)

Ein festschreiben der "Spezialrollen" wird nicht skriptseitig passieren, sondern wird wie die Tarnung ein Terminspezifikum, des Missionbauers, bleiben.

**Comment by E-for-Eron** [comment]
- allen Klassen bis auf den Schützen die One-Use Raketenwerfer entfernen

**Comment by shukari** [comment]
@E-for-Eron Frage ist was wir mit der One-Use-Kiste machen, ich kenne Pakowski, der wird einfach ne Kiste mitnehmen und schon haben alle wieder einen ^^

**Comment by E-for-Eron** [comment]
Gedanken zu Waffenänderungen/Rückstoß Überarbeitung:

Überhitzung bearbeiten (falls sinnvoll)

Unterlauf für TF entfernen +Einzel-Granatwerfer als Zweitwaffe einfügen

Schütze Boni in Rückstoßkontrolle, Verwacklung geben (soll nicht zum Scharfschützen werden)

Visierfreigabe überarbeiten: Schütze erhält Zugriff auf Kombinationsvisiere für Nahkampf wie auch mittlere Entfernung (1x-4x), während Spezialisten sich für 1x oder 4x entscheiden müssen
- bestimmte Vanilla Visiere sind dafür geeignet, sollten mit ins Arsenal aufgenommen werden

Grenadier starke Verwacklung geben, wenn nicht aufgelegt, dafür gute Rückstoßkontrolle (Grenadier soll wegen des Unterlaufgranatwerfers genommen werden)

Grenadier: alle Waffen ohne Granatwerfer entfernen

MG starke Repressalien, wenn nicht aufgelegt (Verwacklung ohne das geschossen wird massiv erhöhen) ; aktuell kann man stehend im Feuerstoß arbeiten wie mit einem AR... Ein MG soll der Unterdrückung und der Sicherung dienen und nur im absoluten Notfall im CQB genutzt werden können
(MG und Gruppenscharfschütze gehören theoretisch immer zusammen; beide nicht für CQB geeignet)

Repetiergewehre (Singleshot) Boni gegenüber Halbautomatik geben

Munitionsträger sollte Buff bzgl Ausdauer/Gewicht bekommen, um ihn nicht als Belastung zu sehen, den man mitnehmen muss, weil man sonst nicht genügend Munition dabei hat (der Träger ist besonders gut körperlich gebaut oder ähnliches)

Schütze könnte Freigabe für Einzel-Granatwerfer als Zweitwaffe bekommen (in Kombination mit den One-Use Raketenwerfern kann man darüber nachdenken ihn zum "Waffenspezialisten" umzubenennen, alle anderen Rollen sind bereits Spezialisten auf ihrem jeweiligen Gebiet)

Schütze: jeweils die leichteren Waffenmodelle anbieten, den anderen Rollen die 0,5-3kg schwereren Modelle geben

nur TF Zugriff auf Long Range Funk

**Comment by E-for-Eron** [comment]
Bundewehr, gewünschte Camouflage:

G36 Wüstentarnung+Magazine

Truppführer/Grenadier/Spotter

BWA3_G36A1_AG40_tan
BWA3_G36A2_AG40_tan
BWA3_G36A3_AG40_tan

Sani/SprengM/AntiFhrz/MuniT/DrohnenOP/Arzt/Schütze/Pionier

BWA3_G36A1_tan
BWA3_G36A2_tan
BWA3_G36KA3_tan

BW Magazine für alle Klassen

BWA3_30Rnd_556x45_G36_Tracer
BWA3_30Rnd_556x45_G36_Tracer_Dim
BWA3_30Rnd_556x45_G36
BWA3_30Rnd_556x45_G36_SD

Beim Arzt möglicherweise direkt das G36 entfernen und ihm ne MP7(Zweitwaffenslot) in die Hand drücken, um ihn mit dem Pilot gleichzustellen.

BWA3_MP7

BWA3_40Rnd_46x30_MP7
BWA3_40Rnd_46x30_MP7_SD

**Comment by Er1807** [comment]
Ich würde dem Schützen auch die schweren Waffen lassen. Damit er an sich
mehr auswahl hat. Style ist wichtig nicht nur gewicht.

E-for-Eron <notifications@github.com> schrieb am Mi., 13. März 2019, 15:02:

**Comment by E-for-Eron** [comment]
Einverstanden, es geht eher andersherum, dass den anderen Klassen die leichteren Modelle weggenommen werden. Sie haben trotzdem noch gut 15 verschiedene Versionen für den Style, sollte also die Jungs nicht einschränken

**Comment by Er1807** [comment]
Ich kann bei nächsten Missionen mir mal anschauen welch Waffen pro Klasse
normalerweise genommen werden.

E-for-Eron <notifications@github.com> schrieb am Mi., 13. März 2019, 16:10:

**Comment by E-for-Eron** [comment]
Sehr gut! Kannst du mir bitte desweiteren ne Übersicht ab sofort nach jeder Mission geben wie viel Schuss jeder verbraucht hat? Damit könnte ich arbeiten, um zu entscheiden wie ich mit Rucksäcken/Muniträger umzugehen habe beim Missionsbau

**Comment by Er1807** [comment]
Kann ich machen.

E-for-Eron <notifications@github.com> schrieb am Mi., 13. März 2019, 16:18:

**Comment by shukari** [comment]
Wir können einen EH machen der das zählt ^^
Sag mir welche Statistiken du brauchst zu allem... Medic... Granaten... Schüsse usw... baue etwas ^^

**Comment by Er1807** [comment]
Gibts schon. @Eron hast du noch die Bilder. Kannst ja mal reinschieken.

shukari <notifications@github.com> schrieb am Mi., 13. März 2019, 16:22:

**Comment by E-for-Eron** [comment]
Negativ @Er1807 , hattest du mir nur im TS damals geschickt und der Cache ist von dem Channel bereits mit anderen Sachen gefüllt. Was ich aber noch gebrauchen kann sind Medic-Daten. Wie viele/welche Bandagen, wie viel Blut/Plasma/Saline verwendet, wie viele Medikamente....

**Comment by Er1807** [comment]
@shukari hatte das Logging schon auf deinem performance logger aufgebaut. Nur mit mehr optionen und Prepared Statements. Die shot eventhandler sind global. Konnte also lokal bei mir alle sachen mit loggen lassen. Medic sachen laufen lokal. Müssten also zu einem zentralen punkt geschickt werden. Kann dir meinen Source Code vlt am Freitag/Samstag schicken falls ich dann nach Hause kann.

**Comment by Er1807** [comment]
https://ace3mod.com/wiki/framework/events-framework.html#21-fired-event-handlers-ace_common Eventhandler für Shots und Medical

**Comment by Er1807** [comment]
https://workupload.com/file/f2QNg85n
Hatte in main noch
```
"TBMOD_Statistics" callExtension missionName;

["ace_firedPlayer", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Player",text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;
["ace_firedPlayerNonLocal", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Player",text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;
["ace_firedNonPlayer", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Player",text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;

["ace_firedPlayerVehicle", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Vehicle",text typeOf (_this select 0), text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;
["ace_firedPlayerVehicleNonLocal", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Vehicle",text typeOf (_this select 0), text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;
["ace_firedNonPlayerVehicle", {"TBMOD_Statistics" callExtension ["sendQueue", [text "Vehicle",text typeOf (_this select 0), text name (_this select 0),text getPlayerUID (_this select 0),text (_this select 1),text (_this select 3)]]}] call CBA_fnc_addEventHandler;
```

**Comment by E-for-Eron** [comment]
Rückstoß abhängig vom "TB_cacheWeaponType" entfernen und stattdessen der aktuellen Rolle unterordnen. Mehrzahl aller Waffen hat nicht den Waffentyp, der für "TB_cacheWeaponType" gedacht ist. 
Bsp: der Sniper der US verwendet Waffe der Klasse "Assault Rifle", obwohl es visuell ein Sniperrifle ist. Das gilt wie oben genannt für die Mehrzahl aller Waffen, sodass die berücksichtigten Rückstoßberechnungen keinen Einfluss auf manche Systeme hatte.

**Comment by E-for-Eron** [comment]
Ingesamten Rückstoßwert für MG stehend auf 8-9 setzen, wenn hingelegt auf 1 und aufgelegte Waffe/Bipod auf 0,4.

**Comment by Er1807** [comment]
@shukari damit du auch mal die resultate der letzten Mission siehst. https://imgur.com/a/3v2tvNE

**Comment by shukari** [comment]
> Rückstoß abhängig vom "TB_cacheWeaponType" entfernen und stattdessen der aktuellen Rolle unterordnen

Sehe ich sehr kritisch, da dann die Pistole der MG Rolle den Recoil einer Konaone aus dem Mittelalter hat und der Scharfschütze ggf auf seinem Ausweichgewehr den Recoil des Scharfschützengewehrs.

**Comment by E-for-Eron** [comment]
Mögliche Abhängigkeiten für den Rückstoß:
- Kaliber
- Magazingröße
- Gewicht

Zusatz: aim_down_side beachten

**Comment by E-for-Eron** [comment]
Memo an @Er1807  und mich: MG Rückstoß nochmal überprüfen, aktuell anscheinend schon gebalanced nach Aussagen anderer Spieler.

**Comment by E-for-Eron** [comment]
Grundausrüstung beim Auswählen der Rollen müssen dann noch angepasst werden, sowie für die Rollen bestimmte Items entfernt/hinzugefügt werden. (Blut/Plasma/Saline/Medikamente)

Desweiteren ist die Equipmentkiste aktuell sinnlos, da gleicher Inhalt wie die Nachtkiste. Vorschlag: Scharfschützendreibein, die neuen ACE Seile (zum Abseilen von Helis) etc etc dort reinzupacken

**Comment by shukari** [comment]
Habe in diesem Issue den Überblick verloren. Ihr wisst ja wie man Änderungen einrecht ^^

**Comment by E-for-Eron** [comment]
- [ ] neuen Ace Seile in Equipmentkiste
- [ ] Rückstoß abhängig von Kaliber/Magazingröße/Gewicht   (zu beachten: aim_down_side)
- [ ] Arzt auf MP beschränken
- [ ] Unterlauf für TF entfernen +Einzel-Granatwerfer als Zweitwaffe einfügen
- [ ] Munitionsträger Buff bzgl Ausdauer/Gewicht
- [ ] One-Use Launcher beschränken
- [ ] Visiere überarbeiten: Schütze erhält Zugriff auf Kombinationsvisiere für Nahkampf wie auch mittlere Entfernung (1x-4x), während Spezialisten sich für 1x oder 4x entscheiden müssen
- [ ] Grenadier: alle Waffen ohne Granatwerfer entfernen

**Comment by E-for-Eron** [comment]
Alle möglichen Tasks erledigt. Restlichen Tasks benötigen erst Rücksprache oder Skripte
