### ISSUE TITLE
Sanisystem überarbeiten

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#153]
**Hauptaspekt sollte sein, das jetztige System nicht zu verlangsamen, sondern an anderen Stellen Vorteile und Verschnellerungen zu integrieren. Das Sanisystem soll nicht der Hauptaspekt einer Mission sein.**

- [x] Bandagen mehr spezalisieren
- [x] Koeffizient für Aktionen (Soldat<Kampfsani<Arzt<Auto<Gebäude)
    - Soldat Coef: 1
    - Kampfsani Coef: 0.5
    - Arzt Coef: 0.2
    - Vehicle Einfluss (Coef **-** Einfluss): 0.1
    - Facility Einfluss (Coef **-** Einfluss): 0.3
    - [x] Coef/Einfluss überdenken
- [x] verschiedene Flüssigkeiten (Plasma/Blut/Saline)
- [x] Adenosin und Atropin nützlich machen
- [x] Piloten stärker machen Prozentual am gesamt Leben (unbedingt dynamisch machen)
    - https://github.com/TacticalBaconDevs/TBMod/issues/153#issuecomment-469005037
- [x] Atropin wird Ketamin nicht Adenosion (hatte ich an dem Abend nur 500mal gesagt ^^)
- [x] https://github.com/TacticalBaconDevs/TBMod/issues/153#issuecomment-474457653
- weiteres was ich vergessen habe, weil ichs nicht sofort aufgeschrieben hatte

**Comment by E-for-Eron** [comment]
Ideen

-Einführung von Saline für den Kampfsanitäter ; auf Blut hat nur Arzt Zugriff (500ml Blut im Rucksack=500ml Blut im Patienten, 500ml Saline i.R.=250ml i.P.) 
-bestimmte Verbände verursachen oder entfernen leichte Schmerzen (besseres Verbandsmaterial führt schneller aus der Bewusstlosigkeit)
-Arzt erhält alleinigen Zugriff auf spezielles medizinisches Material oder Möglichkeiten (ohne Fahrzeug CPR o.ä.)
-einfacher Soldat hat nur Zugriff auf eine Verbandsart, die zwar gegen fast alle Schadensarten hilft, aber nur kleine bis mittlere Wunden für gewisse Zeit verschließt, bei großen Wunden sehr schnell wieder auf geht
-große Wunden können nur von Kampfsani/Arzt effizient geschlossen werden


aktuelle Umsetzung

-Anpassung der Bandagen abhängig von Wundart, Größe von Wunden, Rolle des Spielers
(Bsp: eine Mullbinde ist nicht steril und wird damit keine Effizienz/kaum Effizienz gegen jegliche offenen Wunden haben)
-Koeffizient für Aktionen anpassen

**Comment by E-for-Eron** [comment]
Habe bisher keine Formel/Skalierung für die Bestimmung der Effektivität und Reopening Chance gefunden. Bsp: ist eine Effektivität von 2 doppelt so hoch wie 1 und wie effektiv/wahrscheinlich wird damit eine Wunde verschlossen. Gleiches gilt für das Reopening.

**Comment by E-for-Eron** [comment]
Ist Realismus beizubehalten oder darauf keine Rücksicht zu nehmen um weniger Umgewöhnungszeit für die Anwender zu ermöglichen? 
(aktuell gehe ich dem System nach eine geringe Umgewöhnungszeit zu ermöglichen)

**Comment by E-for-Eron** [comment]
Effizienz v. Bandagen ist eine Kennziffer wie viel von einer Wunde mit einer einzelnen Bandage verbunden wird; sobald die komplette Wunde verbunden ist, gilt sie als verbunden/geschlossen

Offene Fragen:
-steigt die Effizienz linear? ist 3 dreifach so effizient wie 1?
-ab welcher Eff. ist eine kleine Wunde mit einer einzelnen Bandage geschlossen (gleiches für mittlere/große Wunden)

Freue mich über Hilfe! Bisherige Recherchen haben nichts ergeben

**Comment by E-for-Eron** [comment]
- Wunden mit einer geringen Chance wieder aufzugehen (aktuell kleine Wunden oder richtige Bandagen für Art der Verwundung) und Wunden mit einer sehr hohen Chance wieder aufzugehen (aktuell große Wunden oder falsche Bandagen für Art der Verwundung) sollten die geringsten Beobachtungszeiten erhalten
- Hintergrund ist der, dass kleine Wunden relativ ungefährlich auch über mittlere Zeit sind und ein Sani nicht sofort eingreifen muss bzw bei großen Wunden oder falschem Verband die Wunde schnell wieder aufreißt und ein Sani nötig wird
- das sollte dazu führen, dass:
              - kleine Wunden weiterhin zu keinerlei Einschränkungen führen
              - große Wunden nach Granaten/zahlreichen Treffern einen Sani verlangen
              - mittlere Verwundungen mit einer sehr hohen Beobachtungszeit den Soldaten am längsten 
                einsatzfähig lassen
-kleine/mittlere Verwundungen sind die häufigsten Arten die uns schnell ausbremsen lassen, aber mit diesen Änderungen und den verbrauchbaren OP-Kits sollte sich ein Bewusstsein entwickeln, dass nicht sofort wegen jeder kleineren/mittleren Wunde ein Sani gerufen werden muss

**Comment by shukari** [comment]
Alles zu Bandageneffektivität ist hier zu finden: [fnc_treatmentAdvanced_bandageLocal.sqf](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_bandageLocal.sqf)
Erklärungen dazu:
1. aus dem configpath `"ACE_Medical_Advanced" >> "Treatment" >> "Bandaging" >> BANDAGETYPE >> "effectiveness"` wird die Effektivität als Zahl genommen
2. wenn eine spezifische Effektivität für einen Wundentyp verfügbar ist wird diese verwendet `"ACE_Medical_Advanced" >> "Treatment" >> "Bandaging" >> BANDAGETYPE >> "Abrasion" >> "effectiveness"`
3. es werden alle offenen Wunden des derzeit behandelten BodyParts durchlaufen und nach zwei Bedingungen für die beste Bedingung gesucht `_specificClass == _classID` (müsste forschen was das ist, bis jetzt kein Plan müsste openWounds analysieren oder debuggen) und `_woundEffectiveness * ((_x select 4) * (_x select 3)) > _effectivenessFound * ((_mostEffectiveInjury select 4) * (_mostEffectiveInjury select 3))`
4. es wird der impact auf die Wunde berechnet (wie stark es die Anzahl der Verwundungen reduziert), zb wenn er die "große Abrasion" als beste Behandlung gefunden hat und du hast davon 5, dann bestimmt der impact wie viele von denen behandelt werden, Berechnung: `private _impact = if ((_mostEffectiveInjury select 3) >= _effectivenessFound) then {_effectivenessFound} else { (_mostEffectiveInjury select 3) };`, das bedeutet nur wenn die gefundene _effectivenessFound größer als die Anzahl ist, behandelt es nur die Anzahl... wenn du also 5 Abrasionen hast, deine Bandage aber eine Effektivität von 10 hat, behandelt es nur 5, der Rest geht verloren.

**Comment by E-for-Eron** [comment]
https://docs.google.com/spreadsheets/d/1uTFGN8C_IRlbge2PtZM1HFCJWNKEqiVzYkoqKMWpZNk/edit?usp=sharing

Dies ist ein erster Vorschlag; ihr habt volle Zugriffsrechte die Werte in der Tabelle zu ändern.
Unter der Formatierung hat das Aussehen gelitten, lesbar sollte dennoch alles sein.

**Comment by shukari** [comment]
ich bin 2 Punkte angegangen, Erklärung in der CommitMsg -> https://github.com/TacticalBaconDevs/TBMod/pull/147/commits/41277f70401c6518ec420f2a8ba7fa5cc4e1bb4d

**Comment by E-for-Eron** [comment]
erste Gedanken zu Adenosin/Atropin/Morphin , die noch selbst nachgeprüft werden, ob technisch überhaupt möglich und einen Sinn mit anderen Änderungen ergeben:

- Morphin: Schmerz leicht und Puls stark verringern, Blutungsrate erhöhen (in der Annahme, dass alle Blutungen von allen existierenden Wunden erst in einer Zahl zusammengefasst werden)
- Atropin: keine aktuelle Funktion als Gegengift; umbenennen in bspweise ein Hämostatikum, welches die Blutungsrate für gewissen Zeitraum senkt, gut geeignet für einfachen Soldaten
- oder Atropin: zu einen Mittel gegen medikamentiöse Überdosis umfunktionieren und dafür die Grenzwerte für eine Überdosis bei anderen Medikamenten senken
- Adenosin: erhöht leicht den Puls (Äquivalent zu Morphium im Verhältnis 3A=1M), für Soldat verfügbar
- ist Viskosität von Blut ein Faktor bzw der Faktor für die Blutungsrate? (https://github.com/acemod/ACE3/blob/191c4fb694b80337c35a36be369b62c634f0e079/addons/medical/ACE_Medical_Treatments.hpp#L1258)

**Comment by shukari** [comment]
Überdosis ist _derzeit_ standardmäßig deaktiviert, da es zu 90% keinen Spieleinfluss hat, sondern nur zum Trolling benutzt wird.
Nur die Sachen die im ACE_Medical_Treatments.hpp angeboten werden gehen.

**Comment by shukari** [comment]
@E-for-Eron brauche eine Einschätzung zu den Coefs und Einflüssen.

### Formel für TreatmentTime:
`finalZeit = originalTreatmentTime * (0.05 max (TB_medical_coef - _influence) min 2);`
- finalZeit: die Zeit die am Ende benötigt wird
- originalTreatmentTime: die Zeit aus der Vanilla TreatmentConfig
- TB_medical_coef: RollenCoef, siehe ersten Post für die derzeitigen Werte für Soldat/Kampfsani/Arzt
- _influence: Einfluss der Medizinischen Fahrzeuge/Gebäude, siehe erster Post für derzeitigen werde
- max und min: gesamtCoef liegt am Ende zwischen 5% - 200% der Originalen Zeit, wobei derzeit keine "plus" Faktoren existieren und der derzeitige Wertebereich zwischen 5% - 100% ist

**Comment by E-for-Eron** [comment]
Piloten: 
- Leben auf den Faktor 10 erhöhen
- es besteht immer noch die Chance ohnmächtig zu werden
- Blutverlust und Schmerzen werden den Piloten nach geringer-mittlerer Zeit (je nachdem wie schnell verbunden werden kann) an den Boden zwingen

**Comment by E-for-Eron** [comment]
Coefs/Einflüsse:

Soldat Coef: 1,5
Sani Coef: 1,1
Arzt Coef: 0,7

Fahrzeug Eff: 0,25
Gebäude Eff: 0,45

Beispiele (in Sekunden angegeben) anhand einer Bandage, CPR und OP-Set (freies Feld/Fahrzeug/Gebäude):

Bandage Soldat: 7,25/6,25/5,75
Bandage Sani: 5,5/4,25/3,25
Bandage Arzt: 3,5/2,25/1,25

CPR Sani: n.V./12,75/9,75    (falls einfaches SaniSys: 16,5/12,75/9,75)
CPR Arzt: 10,5/6,75/3,75

**Comment by shukari** [comment]
Wäre dann länger als jetzt, würde ich aber mitgehen... würde das Abbinden
für alle fix sehr kurz machen.



E-for-Eron <notifications@github.com> schrieb am So., 3. März 2019, 11:56:

**Comment by E-for-Eron** [comment]
Man kann auch noch den Soldaten Coef um 0,2 auf 1,3 senken um auf 6,5/5,25/4,25 zu kommen.
Der normale Schütze soll nicht ewig sich verbinden müssen und ein Sani wird schon eh notwendig werden bei großen Wunden. 
Sehr kurzes Abbinden finde ich gut!

**Comment by E-for-Eron** [comment]
Haben wir die Möglichkeit einen Zeitfaktor einzubauen, ab wann ein Medikament wirken soll? Ich denke an zwei Schmerzstiller: Morphium und Naloxon, wobei Morphium erst nach 40 Sekunden anfängt zu wirken, dafür aber mit einer hohen analgetischen Potenz und langer Wirkzeit, und dem gegenübergestellt Naloxon, welches sofort wirkt, jedoch eine niedrige analgetische Potenz und kurze Wirkzeit hat.  
Naloxon für den normalen Schützen; für Sani/Arzt steht beides zur Verfügung.

**Comment by E-for-Eron** [comment]
Statt Atropin Ketamin, ein weiteres Schmerzmittel:

Morphine
                painReduce = 15;
                hrIncreaseLow[] = {-10, -20, 35};
                hrIncreaseNormal[] = {-10, -30, 35};
                hrIncreaseHigh[] = {-10, -35, 50};
                timeInSystem = 900;

Ketamin
                painReduce = 2;
                hrIncreaseLow[] = {0, -5, 60};
                hrIncreaseNormal[] = {-5, -10, 60};
                hrIncreaseHigh[] = {-10, -15, 90};
                timeInSystem = 300;

**Comment by E-for-Eron** [comment]
Mit gesenktem Soldaten Coef

Coefs/Einflüsse:

Soldat Coef: 1,3
Sani Coef: 1,1
Arzt Coef: 0,7

Fahrzeug Eff: 0,25
Gebäude Eff: 0,45

Beispiele (in Sekunden angegeben) anhand einer Bandage, CPR und OP-Set für 8 Wunden im Extremfall (freies Feld/Fahrzeug/Gebäude):

Bandage Soldat: 6,5/5,25/4,25
Bandage Sani: 5,5/4,25/3,25
Bandage Arzt: 3,5/2,25/1,25

CPR Soldat: 19,5/15,75/12,75
CPR Sani: 16,5/12,75/9,75
CPR Arzt: 10,5/6,75/3,75    

OP-Set Sani: 44/34/26
OP-Set Arzt: 28/18/10


Coef steht gerade für den einfach Soldaten in direktem Zusammenhand zu der Effektivität der Verbandsart, die ihm zukünftig zur Verfügung stehen wird. Planung ist eine überaus effektive, die bei kleinen-mittleren Wunden durchschnttl 5-15Min hält und eine Reopening Chance von 0,2-0,5 hat. Ein Soldat sollte mit dieser mit ein bisschen Glück mind 10-30min ohne weitere Bandagierung derselben Wunde klarkommen.
(große Wunden hingegen haben extrem hohe Reopening Chance)

**Comment by E-for-Eron** [comment]
Komplett überarbeitetes Sanisystem in Textform, tut mir leid wenn der Versatz an Zeilen oder ähnliches euch Informatikern Augenkrebs verursacht, es sollte aber alles funktionieren. Es handelt sich um dieselben Werte, die in der bereits oben verlinkten erweiterten Tabelle aktualisiert wurden. 

https://drive.google.com/file/d/1Nb517eIBc2K2DEXSAzcYZzziN8MQhqQs/view?usp=sharing

**Comment by E-for-Eron** [comment]
Fehler bei der Zuordnung von Ketamin. Grundgedanke: Atropin durch Ketamin ersetzen und dem neue Werte geben. 
Die Werte hat aktuell aber Adenosin. Um nicht wieder 40 Mal Sachen umzubezeichnen einfach die Werte auf Atropin übertragen und umbenennen.
Adenosin kann Standardwerte erstmal zurück erhalten, wird von mir aber noch überarbeitet.

**Comment by shukari** [comment]
Bearbeite ich mit dem Ketamin, haben wir verwechselt, war auch spät ^^
Sonst alles bis zu dem Beitrag jetzt oben reingeschrieben oder beantwortet, alles zu Wunden/Bandagen usw zählt für mich als erledigt seit dem Bandagenupdate von Dir.

**Comment by E-for-Eron** [comment]
Pilotenleben dynamisch bereits erhöht?

**Comment by shukari** [comment]
Nope, auch nicht oben angehackt ^^

**Comment by E-for-Eron** [comment]
Adenosin/Epinephrin werden noch von den Werten angepasst, um es gebalanced und sinnvoll zu halten. Werde ich dann hier posten.

**Comment by E-for-Eron** [comment]
Saline mit dem Faktor 0.5 dem Arzt/Sani geben mit dem Zusatz des "Selftreatment allowed", dass nicht mehr mehrere Sanis in einem Trupp benötigt werden, sondern sie sich in Notsituationen selbst Blutvolumen geben können.

**Comment by shukari** [comment]
Wollten wir nicht den normalen Soldaten das kleinste geben und das darüber lösrn

**Comment by E-for-Eron** [comment]
Jep, ich weiß nur nicht welches System sinnvoller ist, drum hat ich diesen Gedankenblitz hier schnell niedergeschrieben

**Comment by E-for-Eron** [comment]
Angepassten Werte für alle Medikamente:

class Morphine {
                painReduce = 10;
                hrIncreaseLow[] = {-25, -35, 45};
                hrIncreaseNormal[] = {-25, -45, 40};
                hrIncreaseHigh[] = {-25, -50, 35};
                timeInSystem = 1200;
                maxDose = 4;
                viscosityChange = -25;

class Epinephrine {
                hrIncreaseLow[] = {15, 35, 15};
                hrIncreaseNormal[] = {15, 35, 10};
                hrIncreaseHigh[] = {15, 30, 5};
                timeInSystem = 150;
                maxDose = 6;

class Ketamin {
                painReduce = 1.25;
                hrIncreaseLow[] = {0, -1, 15};
                hrIncreaseNormal[] = {-1, -3, 10};
                hrIncreaseHigh[] = {-3, -5, 5};
                timeInSystem = 300;
                maxDose = 6;
                viscosityChange = -3;

class Adenosin {
                hrIncreaseLow[] = {5, 10, 20};
                hrIncreaseNormal[] = {8, 12, 15};
                hrIncreaseHigh[] = {-15, -25, 10};
                timeInSystem = 90;
                maxDose = 3;
                viscosityChange = 6;

**Comment by E-for-Eron** [comment]
> Wollten wir nicht den normalen Soldaten das kleinste geben und das darüber lösrn

Jawohl, bleibt dabei! Hatte nen Denkfehler

**Comment by shukari** [comment]
Habe die Medication übernommen und die Namen der IVs verändert... gleich auch noch die Gewichte... Blut wiegt wie vanilla, Plasma mal 2 und Kochsalz mal 3. Ist erstmal nur eine Idee das etwas zu Balancen.

**Comment by E-for-Eron** [comment]
Alles einmal niedergeschrieben als Infoblatt für alle Leute.

https://drive.google.com/open?id=1pE_mtWcXWdne_Ln1hZWKT4kCuj25-iYs

**Comment by E-for-Eron** [comment]
Alles zusammengetragen, gedacht als Infoblatt bei Veröffentlichung:

https://drive.google.com/open?id=1pg_1Q4s1XrMjbspdng9gy1y5YyAyKYyb

**Comment by E-for-Eron** [comment]
Was passiert aktuell bei einer Überdosis? Ich habe in Tests nichts feststellen können. Wäre es sinnvoll Überdosis eine Bedeutung zu geben und mit bestimmten Effekten (https://community.bistudio.com/wiki/Post_process_effects) zu belegen? Bei Morphium würde man nach 3-4 sowieso anhand des sinkendes Blutdrucks einen Herzstillstand bekommen, aber Leute könnten auf die Idee kommen Adenosin sich wie eine Droge zu spritzen, weil es die periphale Resistance erhöht und damit indirekt den Blutdruck.
Die Jungs sollen nicht ausfallen, aber spüren, dass sie mit ner Überdosis nicht ohne Einschränkung weiter kämpfen können. 
Eure Meinung; zu sehr ins Detail gehend oder sinnvoll?

**Comment by shukari** [comment]
Überdosis + random 2 = **Tod**
incompatible Medics = **onOverdose Event**

**Comment by shukari** [comment]
@E-for-Eron Bitte mal zusammentragen was jetzt noch fehlt, für mich ist dieses Issue derzeit erledigt.

**Comment by E-for-Eron** [comment]
Bezüglich Sanisystem fehlen nur noch die Anpassungen im Arsenal und Standardloadout der Rollen.

**Comment by shukari** [comment]
@E-for-Eron bitte mal für mich ne Checkliste hier erstellen, beim schreiben oben der dritte listentype also immer |` - [ ] TEXT `|

**Comment by E-for-Eron** [comment]
- [ ] Inventar Sani/Arztkiste anpassen
- [ ] Standardloadout aller Rollen anpassen
- [ ] allgemeines Inventar aller Rollen anpassen (Bandagen, IV, Medikamente...)

**Comment by E-for-Eron** [comment]
Ich habe ein paar unserer Sanis jetzt das Infoblatt zur Verfügung gestellt, um erste Meinungen zu erhalten. Nici sprach mich daraufhin an, dass sie die Verdreifachung des Gewichts für Saline zu unrealistisch hält. Vorschlag, wir setzen das Gewicht vorerst runter und falls wir feststellen, dass Saline nicht nur für den Notfall mitgenommen wird und die Sanis zu wenig zu tun haben, schrauben wir das Ganze wieder hoch. (würde ich bei Zustimmung einfach in die Taskliste mit aufnehmen)
Ansonsten gab es sehr positives Feedback und die Leute freuen sich schon darauf!

**Comment by shukari** [comment]
@E-for-Eron gib mir einfach gewichte die du für gut hälst für alle 3 jeweils 1l, 500ml und 250ml.
Derzeit ist zuviel... brauche es in lb (pound)... 500ml Kochsalz derzeit 30lb = 13,6kg ^^
Allerdings ist von ACE3 aus auch 1l Blut = 4,5kg
https://github.com/TacticalBaconDevs/TBMod/blob/d47411a8b3d1c6a16afe147da09c75112185a73e/addons/TBMod_main/configs/CfgWeapons.hpp#L24-L34

**Comment by shukari** [comment]
@E-for-Eron Gewicht wieder auf normal gesetzt, Saline wiegt mit 500ml soviel wie Blut mit 2000ml denke das reicht als "Gewichtsnachteil".
Habe mal die Anwendungszeiten der IVs bearbeitet, siehe hier:
https://github.com/TacticalBaconDevs/TBMod/blob/13da2a9ec141651a34c8b359f207d1df397cdfb3/addons/TBMod_main/configs/ACE_Medical_Treatments.hpp#L20-L28

**Comment by Er1807** [comment]
Dachte das eigentlich auch. Muss vlt. Nochmal getestet werden. Setzt mich heut mal dran

**Comment by E-for-Eron** [comment]
@shukari  Habe genau das zuerst im Text auch zu stehen gehabt und hatte dann einen Test über 80min durchgeführt und es hat sich immer wieder eine Wunde geöffnet, konnte also nicht nachweisen, dass selbst mit 99,9% eine Wunde sich automatisch verschließt. Kann das mit dir testen @Er1807 , interessiert mich auch brennend.

**Comment by shukari** [comment]
@Er1807 @E-for-Eron Das dieser Mythos weg ist. Reopening = öffnen einer Wunde mehr nicht... kein automtisch verschließen oder irgendwas...
Wenn man sich verbindet, wird [ACE_medical_fnc_handleBandageOpening](https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/medical/functions/fnc_handleBandageOpening.sqf) aufgerufen... da wird gewürfelt mit mit der reopChance... wenn erwischt wird die zweit ausgewürfelt und eine [Funktion mit delay](https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/medical/functions/fnc_handleBandageOpening.sqf#L86) ausgeführt, die die wunde öffnen... mehr nicht

**Comment by shukari** [comment]
> Stört mich etwas, für weitere ~13min geschlossen zu bleiben ... eigl nicht... Reopeningchance von 90% heißt das sie zu 10% nach ~13min wieder aufgeht und einfach wieder eine Wunde ist, sonst bleibt sie ewig zu.

Die Aussage ist übrings auch falsch.... wenn die reopingchance 90% ist, geht sie zu 90% wieder auf... keine Ahnung was ich beim Schreiben dachte ^^

**Comment by E-for-Eron** [comment]
Das sind gute Nachrichten! Ich ändere die Textstelle und ein paar Werte in der Medictabelle.
