### ISSUE TITLE
BW UAV-Operator

### ISSUE THREAD

**Issue by BeLink13** [TacticalBaconDevs/TBMod#155]
Drohnen nicht verwendbar

**Comment by E-for-Eron** [comment]
Welche Einstellungen hast du?

Ich kann den Fehler nicht reproduzieren. 
- Main Modset, MainCore.VR, Multiplayer, als BW Drohnen-OP ausrüsten, Drohnen kontrollierbar

**Comment by shukari** [comment]
Bestätige letzte 2 Tages Mission am Sa, du konntest die Drohne hinlegen mit
Terminal verbinden... dann aber im Termin Fahrer und Schütze nicht
steuern... war ausgegraut... auch bei fliegenden Drohnen..

E-for-Eron <notifications@github.com> schrieb am Do., 21. Feb. 2019, 17:55:

**Comment by shukari** [comment]
Scheint behoben
