### ISSUE TITLE
Server Persistence speichern

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#157]
Server Persistence speichern

**Comment by Er1807** [comment]
@shukari Hat dies funktioniert? Was wäre wenn man das auch über ne Datenbank macht. Dann läuft wird auch der profilenamespace nicht immer voller.

**Comment by shukari** [comment]
Jap, das wäre der nächste Schritt, weg von profileNamespace und hin zu SQL wie bei unseren Freunden bei der KK.
