### ISSUE TITLE
Helikopter Crew Überlebensfähigkeit

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#160]
Ziel: Pilot/Co-Pilot sollen weniger Schaden durch Beschuss erhalten, um Landung in heißer LZ  durchzuführen oder CAS Überflüge zu ermöglichen, statt in 2km Entfernung zu hovern.

Habe möglicherweise bereits unter "crewCrashProtection" den richtigen Faktor dafür gefunden:

https://community.bistudio.com/wiki/CfgVehicles_Config_Reference#crewCrashProtection

**Comment by shukari** [comment]
Müssten dann die Klassen überschreiben und compat Addons schreiben.
Für rhs existiert so was ja schon.

**Comment by E-for-Eron** [comment]
Ist es möglich das an einem einzelnen Beispiel ohne zuviel Aufwand zu testen? Dieser Issue hat nicht die größte Dringlichkeit.

**Comment by shukari** [comment]
Ein Fahrzeug per config in cfgvehicles per Mod ändern. Kann ich dir zu
heute abend bauen.


E-for-Eron <notifications@github.com> schrieb am Mi., 27. Feb. 2019, 16:56:

**Comment by shukari** [comment]
Ein schnell zusammen geschusterter Versuch eines Addons... in deinen Addons git Ordner packen und bauen lassen.
Vorher die Klasse und parrentklasse ersetzen. Objekt im ConfigViewer öffnen (setzen und dann Rechtsklick) dort den Classennamen und den ersten namen aus dem parrents array.

[TBMod_tests.zip](https://github.com/TacticalBaconDevs/TBMod/files/2911202/TBMod_tests.zip)

**Comment by shukari** [comment]
Für den LittleBird aka Hummingbird wäre das in der CfgVehicles.cpp im configsOrdner:

```
class Heli_Light_01_unarmed_base_F;
class B_Heli_Light_01_F : Heli_Light_01_unarmed_base_F
```

**Comment by E-for-Eron** [comment]
Ich weiß nicht was mit "Objekt im ConfigViewer öffnen...[]...parrents array." gemeint ist. Ich habe zur Überprüfung im ConfigViewer jetzt nur nachgeschaut, ob der crewcrashprotection Wert auf 0.01 geändert worden ist

**Comment by shukari** [comment]
"Objekt im ConfigViewer öffnen", also wie beschrieben, imk Editor setzen und per Rechtsklick darauf dann "im Configviewer öffnen", dann ist ganz unten eine Zeile Namens parrents.
Wie lief der Test den?

Zudem gäbe es noch die Möglichkeit, bei den Piloten generell den Spielerschaden (von ACE3) zu erhöhen oder nur wenn sie als Pilot aktiv sind.

**Comment by E-for-Eron** [comment]
Wir haben aneinander vorbei geredet, hab mir von Eric helfen lassen und ich hatte bereits alles richtig gemacht ^^ 
Der Test lief desaströs, keinerlei Unterschied erkennbar, weder bei Beschuss, noch bei anderen Formen von Schadeneinwirkungen. 

Die Kopplung an den Piloten fände ich sehr gut!

**Comment by shukari** [comment]
wird in #153 bearbeitet
