### ISSUE TITLE
Kistenlayout

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#166]
Anbei alle überarbeiteten und überprüften Kisten für USA/BW/Allgemein. Inventar sollte nach Update und Übernahme des Sanisystems angepasst werden #Arztkiste#Sanikiste (Namen können noch geändert werden). #153 

Zusatz: Inventar der Equipmentkiste anpassen, aktuell fast identisch mit Nachtkiste. 

Nachschubabwurf als Zeus per TB-Mod Tool reparieren, aktuell nicht verwendbar.

**Comment by shukari** [comment]
@E-for-Eron @Er1807 
> Nachschubabwurf als Zeus per TB-Mod Tool reparieren, aktuell nicht verwendbar

Was meinen?

**Comment by Er1807** [comment]
Es gab Fehlermeldungen beim starten und das Modul zum abwerfen konnte nicht
benutzt werden. Ob es durch die neuen Kisten kommt ist unbekannt.

shukari <notifications@github.com> schrieb am Di., 12. März 2019, 16:14:

**Comment by E-for-Eron** [comment]
@Er1807  Modul konnte in gestrigen Tests verwendet werden, bleibe trotzdem aufmerksam, falls das Problem sich wiederholt

**Comment by shukari** [comment]
Lag an Problem #173 in #147 behoben, kannst neu pullen @E-for-Eron

**Comment by E-for-Eron** [comment]
Kisten werden größtenteils nicht richtig dargestellt, in manchen Fällen noch falsches Modell. Gewollte Grundfarbe ist olivfarbend.

- Allgemein: alle Mörserkisten schwarze Grundfarbe, ebenso Funkkiste, MP5 Mun, Minen, Leere Kiste; bei der Baukiste fehlende Schrifttextur
- US: alle Kisten bis Nachtkiste schwarze oder unsichtbare Grundfarbe
- BW: Nachtkiste ist falsches Modell (soll identisches Modell mit dem Allgemeinmodell haben-"kleine Munikiste"), alle anderen Kisten bis auf Werfer Munition schwarze/unsichtbare Grundfarbe

**Comment by E-for-Eron** [comment]
![20190314153043_1](https://user-images.githubusercontent.com/42243988/54364954-37eaea80-466e-11e9-8350-08fb942ed7ee.jpg)

**Comment by shukari** [comment]
Schau dir mal eine falsche Kiste im Configviewer an und schick mir den Wert
der bei HiddenSection steht.



E-for-Eron <notifications@github.com> schrieb am Do., 14. März 2019, 15:31:

**Comment by E-for-Eron** [comment]
Bsp ist eine unsichtbare Kiste, richtiges Modell und richtige Schrift:

hiddenSelections[] = {"Camo_Signs","Camo"};
hiddenSelectionsTextures[] = {"\TBMod_skins\pictures\statics\AmmoBox_signs_CA_0_1.paa"};

Bsp ist eine schwarze Kiste, richtiges Modell und richtige Schrift:

hiddenSelections[] = {"Camo_Signs","Camo"};
hiddenSelectionsTextures[] = {"\TBMod_skins\pictures\statics\AmmoBox_signs_CA_0_2.paa"};
