### ISSUE TITLE
Mikro MakePBO 7.16 zerhaut unsere Macros

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#173]
Habe ein MakePBO/dePbo Update gemacht, weil @E-for-Eron ein Problem hatte und ich gesehen hatte, das ich eine super alte Version hatte.
Nun wurde einiges in der neuen Version geändert, so das fast alle unsere Macros schrott sind.

@Er1807 bitte sag mir das du noch eine alte MakePBO und dePBO Version hast.

Beispiel:
```
#define PUBLIC_NAME_CAT(D_NAME, CATO) \
        displayName = D_NAME; \
        scope = 2; \
        scopeCurator = 2; \
        editorSubcategory = "EdSubcat_TB_Supply_##CATO"
```
Ging früher... nun ersetzt er ##CATO nicht mehr mit dem Parameter von oben, weil es in "" steht, gleiches gilt für #172 .

**Comment by Er1807** [comment]
Hab eine alte installiert weiß aber nicht ob ich den Installer noch habe. Bin zur Zeit aber nicht zu Hause und habe keinen Zugriff zum PC.

**Comment by shukari** [comment]
@Er1807 Jap, installer wird abgespeichert, alles zu finden in `C:\Program Files (x86)\Mikero\DePboTools` bitte mal als Archiv packen und mir schicken ^^

**Comment by Er1807** [comment]
Mach ich. Werde aber warscheinlich erst am Wochende die Möglichkeit dazu
haben. Eron kennt den Grund.

shukari <notifications@github.com> schrieb am Mi., 13. März 2019, 14:45:

**Comment by shukari** [comment]
@Er1807 alles ok, versuche es zu beheben... viel Zeit für unnötige Scheiße... habs mal reported... [REPORT](https://forums.bohemia.net/forums/topic/113852-mikeros-dos-tools/?do=findComment&comment=3344670)
