### ISSUE TITLE
Einige Aktions disablen

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#176]
Aufmerksam wieder darauf geworden durch @Schwaggot (https://github.com/Schwaggot/kellerkompanie-mods/commit/20b2afdc02244553e744049d8847c0296243aac3)
Hatte es in ACE3 Optional schon gesehen... aber bis jetzt nicht weiter interessiert.

- Waffen wechsel Aktionsmenü Eintrag löschen
    - ich wechle nur über 1, 2, 3 und B meine Waffen/Bios
- Munitionswechsel [...]
    - fände es fast cooler wenn du ins Inventar gehen musst um dir Tracer in die Waffe zu machen, oder wie Attachmentwechsel per ACE3

Brauche dazu Meinungen @TacticalBaconDevs/developer @TacticalBaconDevs/helper

**Comment by E-for-Eron** [comment]
- ebenso Waffenwechsel per Tastatur
- Muniwechsel per Inventar

**Comment by Schwaggot** [comment]
Obacht! Die Mausrad Actions sind auch für Munitionswechsel in Fahrzeugen, wenn ihr die rausnehmt kann man bspw. im Panzer nicht mehr auf andere Munition wechseln.

**Comment by Er1807** [comment]
Ich habe bei mir den Waffenwechsel im nicht aktiv/nie aktiviert. Glaube
nicht das es entfernt werden muss. Muss da von anderen mal hören ob sie die
sachen sehen.

Schwaggot <notifications@github.com> schrieb am Di., 19. März 2019, 15:50:

**Comment by shukari** [comment]
@Schwaggot Das ist doch Müll ^

**Comment by Schwaggot** [comment]
Ja ich bin noch nicht dazu gekommen, ich wollte ACE actions hinzufügen für im Fahrzeug um das zu umgehen, aber die configs sind ekelig.

**Comment by IDarky** [comment]
Währe dafür keine Änderungen am  Waffenwechsel oder Munitionswechsel vorzunehmen.

**Comment by shukari** [comment]
Ich persönlich finde weniger Actionmenü = besser, aber wäre auch ok wenns bleibt.

Bitte abstimmen auf diesem Kommentar mit einem Smiley (JA = 👍 , Nein = 👎 ), ob:
### Soll das Waffenwechseln und Munitionswechseln aus dem Actionmenü entfernt werden und über Inventar und ACE3 Menü passieren?
@TacticalBaconDevs/developer @TacticalBaconDevs/helper

**Comment by mordl** [comment]
Ich bin zwar für die zusätzliche Option über das Ace Menü, aber gegen die Entfernung der bestehenden Möglichkeiten, weil es die Freiheit unserer Gemeinschaft in der Spielsteuerung einschränkt. Da Darky schon dagegen ist macht es keinen Sinn. 

PS: Das HUD verschwindet doch sowieso, sobald es für ein paar Sekunden nicht verwendet wird, oder?

**Comment by Er1807** [comment]
https://imgur.com/a/ef47Thh Einfach diese Werte setzten dann ist die Waffen auswahl weg. Hatte seit Jahren dadurch dieses Menü nicht gehabt. Munition soll drin bleiben. Der Arme Grenadier der für jede Granate ins Inventar muss.

**Comment by shukari** [comment]
Denke mal eindeutig ^^
