### ISSUE TITLE
Heli Medevac Skin auf die bewaffnete variante

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#182]
Heli Medevac Skin auf die bewaffnete variante
von Pfeiffer

**Comment by E-for-Eron** [comment]
In Ordnung. Modell lautet: "RHS_UH60M" kann bezeichnet werden mit UH-60 MEV bewaffnet.
Textur-Schicht, auf die die neue Textur gehört:
0 - "uh60m_fuselage_mev_co"
1 - "uh60m_engine_mev_co"
2 - "default_co"
3 - "uh60m_dust_filter_co"

https://workupload.com/file/hwMnPQy8

**Comment by E-for-Eron** [comment]
![20190324025827_1](https://user-images.githubusercontent.com/42243988/54873908-cbe05300-4de0-11e9-9913-15daa6bc2339.jpg)
