### ISSUE TITLE
Grenadier Optimierungsvorschläge

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#194]
**Anpassungsvorschläge:**
- Rucksäcke ausklammern  **machbar in Kombination mit der Traglasterhöhung der Weste**
- Traglast für Grenadierwesten auf testweise 9kg erhöhen 
- Grenadier verliert Zugriff auf tödliche Handgranaten, Hunter IR Monitor (Aufklärung obliegt dem TF) und Klappspaten **geht klar, aber Vorsicht mit dem Klappspaten, sonst hockt zum Schluss der Schütze alleine im Dreck**
- 3-Schuss-Rauch-ULG (weiß) Gewicht auf 0.46 reduzieren  **machbar**
- ~~und Größe der Rauchwolke erhöhen~~ **nicht machbar**
- Gewicht von 1-Schuss AIM Smoke auf 0.23 kg reduzieren **machbar**
- ~~Lebenszeit von Rauchgeschossen auf das Doppelte von Handgranaten erhöhen~~ **nicht machbar**
- ~~Vanilla-Smoke-ULGs ausklammern oder entfernen~~ **nicht machbar, weil die 3er AIM Vanilla sind**
- Gewicht von Flare ULGs auf 0.10 kg reduzieren und Leuchtdauer auf 5min erhöhen **machbar, aktuell unendliche Leuchtdauer**
- Stun ULG Wirkradius auf 20m erhöhen und alle Personen im Radius unabhängig von Blickrichtung stunnen **aktuell kein Einblick, muss von @Er1807 @shukari geprüft werden**
- Breaching Charges entfernen **machbar**
- (Einführung von eigenen Explosivgeschossen und Entfernung alter Varianten)
 Anti-Personen-ULG: Tödlich in einem Radius von 5m, verursacht Verstümmelung in einem Radius von 15m (Personen können nicht mehr rennen) 
 Anti-Fahrzeug-ULG: Beschädigt in einem Radius von 10m die Reifen von Fahrzeugen und zwingt sie zum Stillstand **schwer umsetzbar, muss abgesprochen werden mit @Er1807 @shukari ; indirect damage müsste dafür erhöht und gebalanced werden**

**Kommentar:**
Grundidee ist eine Überarbeitung und Optimierung des Grenadiers zur besseren taktischen Nutzung und Vermeidung von überladenen Grenadieren mit 30 HE ULG Granaten, die am Ende nicht effizient eingesetzt werden. Schütze und Grenadier sollen unterschiedliche Anwendungsbereiche erhalten damit der Grenadier ein Unterstützer wird und nicht den normalen Schützen ersetzen kann und vice versa. Truppführer und Grenadier sollen durch die Änderungen enger zusammenarbeiten. Durch die Anpassungen von Gewichten sollte der Grenadier in der Lage sein 8 Magazine und ca. 15 Schuss 0.23kg Geschosse plus ca. 1kg Reserve. Dadurch sollte genug Raum zum Experimentieren zur Verfügung stehen, ohne den Rahmen zu sprengen.

**Comment by Er1807** [comment]
Alles was mit den Smoke Effekten zu tun hat. NEIN.

**Comment by shukari** [comment]
@E-for-Eron du als Konzeptbearbeiter bitte einfach sagen was gemacht werden soll.
Was passt in unser derzeitiges Konzept ohne zu stark / schwach zu sein.

**Comment by E-for-Eron** [comment]
- [ ] Stun ULG: Effekt auf 20m erweitern, unabhängig der Blickrichtung
- [ ] Flare ULG: Leuchtdauer auf 90 Sekunden, Gewicht auf 0,1kg setzen
- [ ] Airburst ULG: [2,40,20,40,200,60]
- [ ] HE ULG: [2,100,80,15,40,30]
- [ ] HEDP ULG : [3,80,60,5,30,30]
- [ ] *NEU* Buckshot ULG: Splitterwirkung, vergleichbar mit Schrotflinte (auf 40m 1,5m Radius der Pellets)
- [ ] Allgemein Knicklichter/Leuchtstäbe: Leuchtdauer auf 120min erhöhen
- [ ] weitere Sachen, die noch hinzugefügt werden müssen
