### ISSUE TITLE
Ideen für Anpassungen vom 13.04.2019

### ISSUE THREAD

**Issue by pkost** [TacticalBaconDevs/TBMod#197]
Folgende Vorschläge/Issues:

- [x] QuickClot ist für alles als kleine Wunden quasi unbrauchbar. Effektivität erhöhen, dafür evtl. höhere Reopeningchance/niedrigere Reopeningtime?
- [x] Bloodflow ist zu langsam. Mit CPR verdoppeln/erhöhen?
- [x] Gar keine Rucksäcke sind ungut. Platz für 2 Mags, Spaten, Rauchgranaten, Materialverteilung?
- [x] Schmerzsystem nochmal anschauen

**Comment by E-for-Eron** [comment]
- Bloodflow ist eine gefixte Einstellung und kann von uns nicht bearbeitet werden, dafür ist Adenosin eingeführt, um im Notfall schnell den Blutdruck zu erhöhen, wenn der Patient bereits stabil ist, aber erst wieder zu Bewusstsein käme, wenn in 10min genügend Blut reingeflossen ist
- QuikClot soll viel Materialverbrauch haben, aber dafür nicht mehr aufgehen ; die Effektivität wird auf 1/0,75/0,5 angehoben, die Reopening Chance auf 0,1/0,1/0,2 gesenkt (damit bleibt eine Wunde zu 80/90% für immer verschlossen)
- Elastische Bandage/Mullbinde werden gleiche Funktion erhalten (effektiv mit hoher ReopeningChance und kurzer Beobachtungszeit), und nur für unterschiedliche Wundarten notwendig sein

**Comment by shukari** [comment]
> Bloodflow ist eine gefixte Einstellung und kann von uns nicht bearbeitet werden, dafür ist Adenosin eingeführt, um im Notfall schnell den Blutdruck zu erhöhen, wenn der Patient bereits stabil ist, aber erst wieder zu Bewusstsein käme, wenn in 10min genügend Blut reingeflossen ist

Kann ich trotzdem ändern... ggf auch Abhängig vom Ort oder so... das in MedicFacs es schneller geht.
Zudem hat Puls oder Blutdruck anscheinend keinen Einfluss auf irgendwas mit der Fluss Geschwindigkeit.
Override von: https://github.com/acemod/ACE3/blob/a18f4180ac0309c1ad48889abe8676bc2b6e700c/addons/medical/functions/fnc_getBloodVolumeChange.sqf#L38
