### ISSUE TITLE
Kein Klappspaten in manchen Loadouts

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#208]
Siehe Header

**Comment by shukari** [comment]
vll gleich in #206 umsetzbar @IDarky @E-for-Eron

**Comment by IDarky** [comment]
Alle Arsenale haben  "ACE_EntrenchingTool", in der Allgemein Menge. @Er1807

**Comment by Er1807** [comment]
@IDarky Ich mein die Default Loadouts.

**Comment by Er1807** [comment]
![image](https://user-images.githubusercontent.com/20169013/56644523-2557ce00-667c-11e9-8394-299d671fd585.png)

**Comment by IDarky** [comment]
bin schon dran die Defaults komplett zu überarbeiten.

**Comment by IDarky** [comment]
kann geschlossen werden  @shukari @Er1807

**Comment by shukari** [comment]
**fixed in PR**

**Comment by IDarky** [comment]
#206 Wurde doch schon gemerged

**Comment by Er1807** [comment]
Ich sließe es mal.
