### ISSUE TITLE
Diskussion/Poll: NiArsenal

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#210]
Frage an alle @TacticalBaconDevs/developer und @TacticalBaconDevs/helper 

### Können/Wollen wir @NiArsenal entfernen?

- damalige Gründe für NiArsenal (zu große @BWA3 Waffen, sind nach dem letzten Update ade)
- generell wird wenig @bwa3 gespielt und @NiArsenal ist nicht gleich stark zu @bwa3 viel genauer und stärker
- die Pistolen aus @NiArsenal wenden, wenn wir USA spielen NIE benutzt
- laut einem Partnerclan, der fast nur @bwa3 spielt, sind die MGs davon seit dem letzten Update gut
- weniger Mods gleich besser ;D

Das Ergebnis hiervon ist nur ein Indikator, keine Entscheidung.

**Comment by E-for-Eron** [comment]
Bin ich mit einverstanden. Habe mir einen Überblick über alle übriggebliebenen Waffen gemacht und damit kann man weiterhin gut arbeiten.

**Comment by IDarky** [comment]
Ich würde dann das BW Arsenal fixen und NI rausschmeißen

**Comment by Er1807** [comment]
Benutze fast nie NiArsenal. weiß nur das die DMR von NiArsenal im Vergleich von BW sehr stark ist. Ob immernoch keine Ahnung.

**Comment by mordl** [comment]
Ich bin für das Entfernen. Ich habe die NiArsenal Waffen nie benutzt und finde sie auch nicht unbedingt notwendig.

**Comment by IDarky** [comment]
Ich würde sagen ist einstimmig oder? Würde mich im DL PR um das entfernen dann kümmern
