### ISSUE TITLE
Erkennung von Fahrzeugen differenzieren

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#221]
@shukari @Er1807 @IDarky  @mordl @BeLink13 

Sollen die verschiedenen Fahrzeuge, speziell unsere meist genutzten, so angepasst werden, dass sie realistischere bzw differenzierte Erkennungsquerschnitte bieten? Auf hochdeutsch: ein Little Bird und eine CH-47 werden aktuell gleich schnell und in gleicher Entfernung erkannt und beschossen; ein MRZR-4 wird so schnell erkannt wie ein LKW mit Lautsprecher auf dem Dach etc....

Ich würde dies anpassen, sodass die Führungspersonen tatsächliche taktische Entscheidungen fällen können bzw Fahrzeuge auch für verdeckte Missionen verwendet werden können, von denen man es optisch erwarten würde.

Ich biete ebenso an die Stealth Helicopter aus Vanilla anzupassen, solange diese auch benutzt werden wollen und nicht abschreckend sind, weil sie angeblich 2035 darstellen würden (*hust* Osama Bin Laden)

**Comment by BeLink13** [comment]
Gute Idee, finde ich sinnvoll! Habe auch nicht gegen die Vanilla Helikopter.

**Comment by shukari** [comment]
?

**Comment by E-for-Eron** [comment]
> ?

Wird nicht wieder vorkommen

**Comment by TBMakuro** [comment]
In meinen Augen durchaus sinnvoll und eine klasse Idee! Zum Thema Vanilla: Nachdem ich ja generell gegen eine Verwendung der Gunships bin bleibt nur der Ghosthawk, bei diesem fänd ichs aber vollkommen ok.

**Comment by shukari** [comment]
Kleiner Hinweis an @E-for-Eron 
in Zukunft die Gruppen erwähnen... also @TacticalBaconDevs/developer und @TacticalBaconDevs/helper dann müssten alle was kriegen.
Zudem Issues die zu PRs gehören, werden über PRs geschlossen... dafür in die Beschreibung von PRs einfach "resolve #ISSUENUMMER" schreiben, habe ich mal gemacht.
--- Hinweis Ende ---
