### ISSUE TITLE
Roadblocks / Ruinen als Pionier räumen

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#223]
Dem Pio die Möglichkeit geben Objekte die im Editor oder von Zeus gesetzt wurden zu entfernen. ( Zum Beispiel Straßensperren )

Optimal wäre es wenn der Missionsbauer einem Objekt eine Entsprechende Eigenschaft setzt und ein "Gewicht" zwischen 1 und x ( Beispiel ) festlegt. Gewichte mit Wert 1 können durch einen einzelnen Pio bewegt ( tragen wie Kisten ) werden, während größere Objekte ( z.B. Waschmaschiene oder PKW ) 2 oder sogar 3 Pios in Umkreis X benötigen ( ähnlich der Menge an benötigten Spielern zum umdrehen eines Fahrzeugs ).

**Comment by shukari** [comment]
Umsetzbarkeit zum derzeitigen Zeitpunkt, also zu schwer eingestuft, wegen zuvieler anderen Issues.... verschoben in Backlog.
