### ISSUE TITLE
Betrifft Bw Arsenal

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#224]
Seit rausnahme des NiArms Mod, fehlen im Bw Arsenal einige Sachen.
Aufgefallen sind zum jetzigen Zeitpunkt: 
- Waffen für die Gruppenführung
- Schalldämpfer für die Aufklärung und/oder Spotter
- Evtl. Waffen ohne Unterlauf für die Aufklärer bzw. Spotter

... bin mir nicht sicher ob noch mehr fehlt.

Gruß
Culli

**Comment by Er1807** [comment]
generell Schalldämpfer

**Comment by E-for-Eron** [comment]
Habe bereits @IDarky darum gebeten sich um diese, und noch weitere Sachen bezüglich HEAT Munition in der Kiste, die neuen ULGs etc zu kümmern. Habe selbst dafür aktuell keine Zeit. Danke!
