### ISSUE TITLE
Betrifft TB-VoiceMod

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#225]
Habe den Mod endlich gefunden der noch gut in unseren TB-Voice Samples mit aufgenommen werden könnte. Schaut es euch einfach mal an!
YouTube: https://tinyurl.com/y6q6exmv
Steam: https://tinyurl.com/y29q4dns

Culli

**Comment by IDarky** [comment]
Klingt zu Brutal. Würde mich nur stören wenn die ganzen Leichen rum röcheln.

**Comment by Culli-TB** [comment]
Da sind auch noch andere Sampler drin die man in unser VoicMod reinnehmen kann. Mann muß nicht alle nehmen.

**Comment by E-for-Eron** [comment]
Je brutaler, desto größer ist meine Immersion und die Hemmung auf jemanden zu schießen.
Dennoch bin ich aktuell auch dagegen, da das Spiel nur den Status tot oder lebendig kennt, und nicht verwundet/Animationen+entwaffnet (Mod existiert, haben wir aber nicht in der Repo). Damit schreien Feindeinheiten rum, als würden sie kurz vor der Ohnmacht stehen, obwohl sie voll einsatzbereit sind und ihre Poition verraten oder sie röcheln, obwohl sie tot sind. 
Die Idee finde ich jedoch toll und einzelne passende Samples wären kein Problem, wir könnten dahingehend auch welche selbst einsprechen, nach Aussage des Autors

**Comment by shukari** [comment]
Das Sound ding gehe ich im Hintergrund derzeit an... da werde ich verschiedenste Sachen integrieren.

**Comment by Culli-TB** [comment]
Wie ist der Stand der Ding?

**Comment by shukari** [comment]
Ist stecken geblieben, habe unseren Soundmod an und bin damit derzeit zufrieden, muss unbedingt den mal testen und schauen. Todo: shukari

**Comment by shukari** [comment]
Andere Sachen haben derzeit höhere Priorität, bis auf weiteres verschoben nach Backlog.
