### ISSUE TITLE
Squadradar customisation

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#227]
Demnächst ist das hier in DUI drin: https://github.com/diwako/diwako_dui/pull/97
Vielleicht hat unser Texturing-Team @E-for-Eron & @Er1807 da coole Ideen für unsere Rollen jeweils.
Und natürlich für mich eine Krone 😈 

Derzeitig werden die hier verwendet, ggf als Vorlage:
https://github.com/diwako/diwako_dui/blob/d3b1766c930547af56563c15e01521f0046f11b2/addons/radar/script_component.hpp#L26-L46

**Comment by E-for-Eron** [comment]
Wir werden das ja an die Rollen des Arsenals wohl knöpfen und für die jeweilige Rolle eine Darstellung benötigen. Darum kann ich mich kümmern.
Damit nur du eine Krone bekommst, müssten wir ne Verbindung deiner Unit zu einer der extra Ränge schaffen. 
@Er1807  ich würde mich wieder um die Grafiken kümmern und deine Hilfe bei der Implementierung benötigen
