### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by Schwaggot** [TacticalBaconDevs/TBMod#231]
In der Weferlingen OP gab es heute bei vielen von uns des öfteren (>10 mal während der Mission) folgende Fehlermeldungen:

```
20:56:24 Error in expression <(_this select 0) say3d (_this select 1)>
20:56:24   Error position: <say3d (_this select 1)>
20:56:24   Error Type Any, expected String
```

Könnte relatiert gewesen sein zu den rumschreienden KIs und Spielern, fiel mir vorallem auf als ich im Turn Out Gunner Seat war vom TPz Fuchs.

Außerdem strange wenn man ständig beim Nachladen rumruft, vorallem auf Englisch als Deutscher.

**Comment by shukari** [comment]
1. Sache kommt durch den im späteren angesprochenen Soundmod, es scheint mir als hättest du nicht die neuste Version des TBMods gehabt, da dieser Fehler behoben wurde in den Soundmod und bei mir nicht mehr vorkam.
2. Das die Spieler Töne von sich geben, ist Teils ein Bug und Teils ein Test der letzten Mission, hatte vergessen es wieder aus zumachen. Fand es aber eiglich cool zu wissen wann dein Nebenmann jemanden abgeschossen hat oder nachlädt ;D

**Comment by Schwaggot** [comment]
1. Hatte die Version aus dem TB Weferlingen Set, alles frisch gesynct und ausm richtigen Ordner gestartet.
2. Ich verstehe die Idee, aber ich persönlich finds nervig, aber ist ja nur meine Meinung^^

**Comment by shukari** [comment]
Kannst mir gerne helfen deutsche Sampels zu machen ^^

Schwaggot <notifications@github.com> schrieb am Fr., 24. Mai 2019, 18:13:

**Comment by shukari** [comment]
Soweit einige Sachen behoben.
Probleme nicht wieder aufgekommen.
