### ISSUE TITLE
Umfrage DMR-Schütze

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#233]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper
Es kam das Thema auf, dass der DMR Schütze aktuell keine wirklich gesonderte Rolle bei TB erfülle, aufgrund der Bewaffnung/Ausrüstung und der Spielweise von TB bzw generell den Missionen die die Missionsbauer bieten können. Es wurde vorgeschlagen, dass man DMR und den Schützen zusammen packt und ein Spieler sich dann selbst raussuchen kann, ob er ein vollautomatisches Sturmgewehr oder ne Halbautomatik mitnehmen möchte.
Ich selbst unterstütze diesen Vorschlag. 
Falls zudem eine Namensanpassung gewünscht wird; gerne hier vorschlagen.
(Waffenspezialist oder ähnliches hätte ich angeboten, da Schütze wählen kann aus Sturmgewehr/DMR/One-Use/Mörser)

**Comment by mordl** [comment]
Ich bin für die Fusion von der Rolle Schütze und Gruppenaufklärer zu einem Waffenspezialisten.
Jedoch sollte er testweise keinen Entfernungsmesser erhalten, um ihn an den TF zu binden.

**Comment by IDarky** [comment]
Für mich hat er eine gesonderte Rolle. 7,62mm . Sehe keinen wirklichen Grund diese zusammen zuführen. Dann ist der Schütze zu überladen und hat dann alles zur Auswahl. Zu @mordl: Auf keinen Fall der DMR-Schütze ist bei mir immer auf der nähst besten Erhöhung und soll von dort selbständig wirken können. Zudem stecke ich meist noch den AT in sein Buddyteam dass dieser indirekten Zugriff auf Aufklärung und Entfernungsmesser hat.

**Comment by shukari** [comment]
Habe nichts gegen eine Fusion, sehe aber eigl euch keinen Handlungsbedarf. Es wurde jetzt einmal geäußert, das ein Spieler lieber was anderes gemacht hätte, unabhängig der Rolle.
Allerdings finde ich die Idee interessant das zu mergen.
Denke auch der DMR sollte den Vector behalten, allerdings @IDarky wenn der DMR auf der Anhöhe sein soll, organisiere dir doch lieber ein Aufklärer Team.... unsere Trupp sollten meist eng agieren, meiner Meinung nach ;D

**Comment by Er1807** [comment]
Finde die Änderung nicht schlecht. Der "Waffenspezialist" wird denke ich dadurch auch nicht zu over powert, da wir zum einen meistens 35kilo nur nutzen. Dabei ist der Mörser mit 9 Magazinen +Waffe und Mun problematisch mit 39.x Kilo. Und mann muss abwägen ob man mehr Mun für die Hauptwaffe mitnimmt oder den Mörser. ganz zu schweigen vom Single Use. Nur Problematisch wirds mit den Rucksäcken. Schüzte hat Kitbacks, der DMR nicht.

**Comment by mordl** [comment]
Ich kann @IDarky seine Vorstellung eines Gruppenaufklärers verstehen, doch ich sehe sie als ungeeignet für ein Mitglied eines größeren Trupps bei der Art wie wir Missionen spielen. Truppenmitglieder sollten max. 100m voneinander entfernt agieren. Gleichzeitig soll aber auch verhindert werden, dass 5 Leute warten müssen während ein GA Ziele auf Distanz bekämpft. Und Darky hat mit seiner ersten Begründung schon einen meiner Gründe für eine Fusion genannt: 7,62mm. Das wars. Mehr hat er nicht das ihn sinnvoll macht. Er braucht ein hohes Gebäude oder einen Berg um seiner Aufgabe als Aufklärer nachzukommen. Ein TF schießt eine Hunter IR in die Luft und sieht alles. Also ist der GA kurz gesagt eine Enttäuschung als Aufklärer. Er ist ein Schütze mit einer dickeren Wumme die dafür nur halbautomatisch schießt und 20 Patronen im Magazin hat. Meinetwegen gebt dem Waffenspezialisten eine Vector. Dann kann er mit jeder anderen Rolle in unseren Standardtrupps sich als Buddy zusätzlich nützlich machen. Damit wäre der Waffenspezialist eine gute Wahl für Stelvs. Der Schütze ist keine Anfängerrolle mehr, sondern der Munitionsträger. Ich will der Rolle des Schützen mehr Tiefe geben, damit erfahrene Mitglieder mehr taktischen Freiraum in der Ausrüstungsphase und in der Mission haben. 
DIe M40A5 und die M24 sind statistisch gesehen zu schwach gegenüber der Mk Mod. Deshalb würde ich sie entfernen und nur die Mk Mod Varianten (ich meine da ist auch eine M14 die aber kaum einer benutzt) dem Waffenspezialisten geben. Die M40A5 ist schwerer als die MSR, trotz geringerer Zerstörungskraft, daher macht es auch keinen Sinn sie dem Sniper zu geben.
An den Munitionskisten müssten wir auch nichts ändern, da seit Längerem die Mk Mod Muniton beiliegt.

Zudem möchte ich nach der Fusion den Sniper und Spotter anpassen, um sie nützlicher und selbstständiger in Missionen zu machen, ohne das der Missionsbauer und GF auf sie groß Rücksicht nehmen muss. Sozusagen eine Phantomeinheit aus zwei erfahrenen Spielern die der restlichen Infanterie eigenständig (Nach Erlaubnis des GF´s) hilft und dabei aber versucht selbst nicht aufgeklärt zu werden bzw. nicht in den Fokus des Gegners zu geraten.

**Comment by E-for-Eron** [comment]
Bezüglich des Gewichts oben von @mordl genannter Gewehre/Munition von Gewehren, kann man was drehen, solange sie ansonsten einen Sinn ergeben genutzt zu werden.

**Comment by IDarky** [comment]
-  [...Ich will der Rolle des Schützen mehr Tiefe geben, damit erfahrene Mitglieder mehr taktischen Freiraum in der Ausrüstungsphase und in der Mission haben....]
meiner Meinung nach ist das Aufgabe des TF´s zu entscheiden was mitgenommen wird. Und der Schütze hat schon genug Möglichkeiten durch die letzten Updates bekommen.

-  [...Ein TF schießt eine Hunter IR...] 
nutze ich Persönlich kaum wenn ich einen DMR-Schützen dabei habe. Mag sie persönlich nicht.

-  Wieso mich jetzt die Zusammenführung stört:

1. keiner meiner DMR schützen hat sich drüber beschwert ein bisschen abseits der truppe zu sein oder sogar deswegen diese rolle gewählt. 
2. Eins von Mordls Argumenten war, dass es "zu viele " Rollen zur Auswahl gibt und deswegen andere Rollen unter gehen. Dazu ist meine Meinung jeder TF sollte frei entscheiden können welche Rolle er nutzt.
3. Ich werde weiterhin den DMR Schützen so nutzen wie ich ihn immer genutz habe. Er wird ja nicht abgeschafft. Für mich macht es die Sache nur komplizierter. Ich sehe jetzt nicht DEN Vorteil. Es ist ja nicht so, dass Schütze oder DMR-Schütze nicht genutzt würden und deswegen zusammen geführt werden.

**Comment by E-for-Eron** [comment]
- ja, es ist die Aufgabe als TF seinen Trupp optimal auf die Situation aufzustellen, aber auch TFs täuschen sich siehe letzten Samstag mit Kampfentfernung über 800m, die selbst gewählt wurden, ohne das alle wirken konnten
- ein DMR Schütze hat nicht annähernd das gleiche Profil der Aufklärung wie eine HuntIR, soll heißen, dass jeder andere Spieler fast genauso gut aufklären kann wie ein DMR Schütze, da mit dem ACOG ebenso mit Leichtigkeit auf bis zu 2km aufgeklärt werden kann
- dann sollten diese Spieler lieber direkt ein Scharfschützenteam bilden meiner Meinung nach, wenn sie Abseits von den anderen Spielern agieren bzw über lange Distanzen schießen wollen; dann wären sie auch eindeutig sinnvoller zu verwenden mit Gewehren, die auch gepanzerte Fahrzeuge stoppen können und mobil als kleine Einheit immer die Vorhut bilden können, ohne das dadurch ein Trupp zerrissen wird (gerade wenn wir wieder den amerikanischen 4/5Mann-Trupp Stil spielen)
- da haben wir zwei verschiedene Meinungen: ich verwende keinen DMR Schützen, weil er keinen Mehrwert für mich mitbringt (außer in gewissen Situationen für eine einzelne Person eine Kampfreichweitenerhöhung um 300m) sondern mich eher in die Bredouille bringen einen Teil meines bereits kleinen Trupps abseits laufen lassen zu müssen- jeder Schütze/Muniträger ist für mich wichtiger, weil sie Eigenschaften oder Ausrüstung mitbringen, die ich stets gebrauchen kann
- ja, es wäre definitv sinnvoll die 12x Zoom Visiere rauszunehmen, und das dem Sniper zu überlassen, ein DMR Schütze braucht nicht mehr viel mehr als ein ACOG, vllt bis 5x/6x Zoom

**Comment by mordl** [comment]
- Ich stimme zu dem Schützen keinen Zugriff auf Snipervisiere zu geben. 

- Das ein TF einen Trupp auf eine komplette Mission in 20-30min Vorbereitungszeit mit Fahrzeugauswahl etc. optimal vorbereitet ist eine Leisung die in meinen Augen bei uns eher weniger oft erreicht wird, wass aber auch daran liegt, dass wir auch persönliche Wünsche von Spielern versuchen sollten zu berücksichtigen. Ebenso sind die Stärken und Schwächen jedes Einzelnen zu berücksichtigen um eine bestimmte Rolle nicht am Samstag in ungeübte Hände fallen zu lassen. Besonders bei Ausrüstung bei denen Zielgenauigkeit, Konzentration und Kenntnisse extrem wichtig sind, da sie sonst nutzlos in der ganzen Mission sind oder einfach gesagt Platzverschwendung. Du kannst eine Schützen als TF zwar sagen, dass er einen One-Use-Raketenwerfer mitnehmen soll. Aber wenn er damit nicht umgehen kann und dadurch seinen Schuss versemmelt, hätte er vielleicht doch lieber ein paar Extrabandagen, Granaten oder Munition mitnehmen sollen.

**Comment by mordl** [comment]
Momentan haben wir oft das Problem, dass der Sniper mit seiner momentanen Ausrüstung sehr eingeschränkt in seinen Einsatzmöglichkeiten ist und dadurch weniger oft zum Einsatz kommt. Dies ist aber eigentlich schlecht, da Sniper/Spotter eine der Spezialisierungen sind, die viel auf Erfahrung mit der Klasse baut. Deshalb habe ich ein paar Tests mit der Ausrüstung des Gruppenaufklärers und des Snipers gemacht. Ich schreibe diese Vorschläge hier, da es immer noch die Entfernung des Gruppenaufklärers als Resultat zur Folge hätte. 

- Ausrüstungsänderungen Sniper

Entfernen:
rhsusf_acc_m8541
rhsusf_acc_m8541_low
rhsusf_acc_m8541_low_d
rhsusf_acc_m8541_low_wd
rhsusf_acc_premier_low
rhsusf_acc_leupoldmk4

Hinzufügen: Alle Hauptwaffen des Gruppenaufklärers+Schalldämpfer+Munitonsvarianten (keine Visiere)
ace_optic_lrps_2d
ace_optic_sos_2d
optic_lrps
rhsusf_acc_compm4
rhsusf_acc_eotech_xps3
rhsusf_weap_MP7A2_desert
rhsusf_acc_rotex_mp7_desert

- Spotter und Sniper erhalten Kampfsanitäterausbildung, jedoch keine Änderung am Arsenal bezüglich medizinisches Material

- MP7 als Sekündärwaffe für Sniper 

- Sniper/Spotter dürfen vom Kommando bis zu zwei Quads anfordern mit je einem Frachtplatz

- Sniper/Spotter sind direkt dem GF unterstellt

**Comment by E-for-Eron** [comment]
Meine aktuelle Planung, um den Sniper wie gewünscht zu verbessern:
- Munition 1 = HEIAP-T (High-Explosive Incendiary/Armor-Piercing Ammunition Tracer) welches der Raufoss entspricht
- Munition 2 = LRS-T (Long-Range Sniper Tracer) keine Penetration von Panzerung, jedoch erweiterte Reichweite und Genauigkeit

**Comment by IDarky** [comment]
> * Spotter und Sniper erhalten Kampfsanitäterausbildung, jedoch keine Änderung am Arsenal bezüglich medizinisches Material

Verstehe nicht worauf du hinaus willst wenn sie kein medizinisches Material haben. Wenn das Sniper team ausfällt finde ich sollte es gerettet werden von anderen Trupps und sich nicht komplett selbst behandeln können.

**Comment by E-for-Eron** [comment]
Also mit den Änderungswünschen der Visiere gehe ich konform, nachdem ich jedes überprüft habe. Mit der MP7 für den Sniper sehe ich auch kein Problem. Das Anfordern der Quads ist innovativ, nur möglicherweise nicht all zu praktisch; bin aber bereit das gerne auszutesten und Meinungen aus den Missionen dazu einzuholen. 
Ich stimme bei der Saniausbildung aber Darky zu: so ganz kann ich dem Gedankengang nicht folgen. Abgesehen vom Realismus würde das doch nur zu schnelleren Behandlungszeiten führen, oder?

**Comment by shukari** [comment]
Wenn es nur ums schnellere behandeln geht, dann können wir ihnen einfach den Coef erhöhen.
Bitte setzt das ganze um, halte mich da komplett raus, ihr macht das, wenns blöd ist meckere ich dann mit 😄 
P.S: Für Hilfe und Fragen bin ich immer da.

**Comment by mordl** [comment]
- Sie sollen auf die Sanikiste angewiesen sein, als eine Art erweiterter Erste-Hilfe-Kasten. Zwei OP-Kits sind enthalten. Somit brauchen sie keine erweiterte Ausstattung im Arsenal. Es soll nur ihre Eigenständigkeit sicherstellen.

**Comment by IDarky** [comment]
ich würde beim USA Sniper noch die rhs_weap_XM2010 aus dem Arsenal entfernen.
Ihre Nachlade Animation ist unvorteilhaft und ist auch nicht durchs auflegen kompensierbar.
Mehrere Schüsse hintereinander nicht möglich.

> Sniper/Spotter dürfen vom Kommando bis zu zwei Quads anfordern mit je einem Frachtplatz
Auch hier wieder sie sollen nicht komplett alleine agieren. Sie soll auch durch Logistik beliefert werden.

**Comment by E-for-Eron** [comment]
> ich würde beim USA Sniper noch die rhs_weap_XM2010 aus dem Arsenal entfernen.
> Ihre Nachlade Animation ist unvorteilhaft und ist auch nicht durchs auflegen kompensierbar.
> Mehrere Schüsse hintereinander nicht möglich.
> 
> > Sniper/Spotter dürfen vom Kommando bis zu zwei Quads anfordern mit je einem Frachtplatz
> 
> Auch hier wieder sie sollen nicht komplett alleine agieren. Sie soll auch durch Logistik beliefert werden.

Beim Scharfschützen spielt Feuerrate eine untergeordnete Rolle, lieber soll er sich 10 Sekunden Zeit nehmen für einen Schuss. Also neben dem M107 MUSS ein weiteres Gewehr existieren, welches möglichst Schalldämpferkapazitäten hat. Ich sehe gerade ein Repetierer als sinnvoll an, weil dann der Schütze sehr darauf bedacht ist zu treffen. Wenn das M2010 nicht deinen Vorstellungen entspricht, mach bitte einen Vorschlag für ein anderes Gewehr. Was Gewichte von Gewehr/Munition und deren Schadenspotential angeht, kann ich alles anpassen @mordl

**Comment by E-for-Eron** [comment]
> * Sie sollen auf die Sanikiste angewiesen sein, als eine Art erweiterter Erste-Hilfe-Kasten. Zwei OP-Kits sind enthalten. Somit brauchen sie keine erweiterte Ausstattung im Arsenal. Es soll nur ihre Eigenständigkeit sicherstellen.

Wodurch wird denn aktuell ihre Eigenständigkeit eingeschränkt? Sie können sich bei Blutverlust Saline geben und in den Quads können sie ne Sanikiste mitschleppen. Wenn es um das Nähen von Wunden geht, wäre es doch intelligenter, wenn sie einfach in der Sanikiste auf die QuikClots zugreifen, mit denen sie zwar viel Verbrauch haben, aber sich Wunden nicht mehr danach wieder öffnen

**Comment by shukari** [comment]
Man kann ja dem Spotter Sanifähigkeit geben... beiden würde ichs nicht geben... bin gegen 100% autonome Ramboeinheiten.

@IDarky die XM2010 oder so hat manuelles Nachladen.... entweder linke maustaste gedrückt halten... dann lädt er erst nach nachdem du sie loslässt oder in den rhs settings kannste einstellen das er nur nachlädt wenn du es per r machst.

**Comment by shukari** [comment]
Btw ist das mit den Quads oder dem Buggy nichts was wir hier beschließen müssen... das ist was was die Zeuse einfach machen.... wenn Logistik da ist dann diese, wenns im Zeitrahmen ist.

Wir dürfen Rahmen nicht immer zu eng setzen, nur wenn es ausgenutzt wird.
Sonst machen wir das per Bestimmungen.

**Comment by E-for-Eron** [comment]
Ich würde mich um alles kümmern, bis auf die Sani Angelegenheit. Der Sniper kann jetzt theoretisch bis 2.5km wirken und sollte bei richtiger Positionierung niemals in der Bredouille sein, sich verbinden zu müssen. Und falls, haben sie ja die Möglichkeit als mobile Einheit schnell zu Unterstützungstruppen zu gelangen. Bei dem 7.62mm Gewehr haben sie zwar nicht die Reichweite, aber ich versuche die Waffe+ Munition dafür einen Stealthbonus zu geben, dass man nicht so schnell aufgeklärt/identifiziert wird.
