### ISSUE TITLE
Bomben/Raketen/Granaten

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#234]
Mk45 Munition
- [x] ~~Laser Guided Munition einbauen~~ Lasermunition funktioniert wieder vollständig
- [x] ~~Rauch Munition mit vorgegebenem Muster einbauen (Quer zur Schussrichtung Rauchwand / Längst  zur Schussrichtung Rauchwand)~~ zentrierter erweiterter Rauch 
- [x] HE Munition anpassen
- [x] UAV Außenlaststationen für UAV Operator verfügbar machen (aktuell muss externe Hilfe in Anspruch genommen werden)
- [x] Anzahl der Munition erhöht

Jet Bomben/Raketen
- [x] sinnvolle Cluster Bomben ~~HE und AT~~ einbauen: AT Minen/HE Minen/ HE Cluster
- [x] ATGM Raketen Arsenal erweitern 
- [x] Namen aller Waffensysteme anpassen, damit jeder den Sinn hinter der jeweiligen Rakete/Bombe versteht
- [x] ~~UH-60 Varianten mit Pylonen: CCD/IR- ,TV/IR- oder LG-ATGM hinzufügen, um abrufbare Feuerunterstützung bieten zu können~~ bereits integriert, nur noch nicht genutzt worden
- [x] A-10 GAU-8 so angepasst, ~~dass alle Radpanzer ohne weiteres bekämpft werden können, für Panzerungen über 15mm jedoch Raketen benötigt werden~~ , dass zwar fast alles penetriert wird, jedoch kein hoher Hit-Wert existiert, sodass man Panzerbesatzungen ausschalten kann bei gezielten Treffern, dass Fahrzeug aber nicht direkt explodiert
- [x] SDB der A-10 zur Verfügung stellen

ULG
- [x] NV-Lasergranate auf ursprüngliche Mündungsgeschwindigkeit setzen, um Zielgenauigkeit zu maximieren+ Effekt beim Auftreffen in Form von kleiner Rauchwolke/Leuchtspur/Staub aufwirbeln o.ä, um überprüfen zu können, dass Granate präzise gelandet ist ~~+ es soll nur eine ULG zeitgleich aktiv Laserziel darstellen, falls bei Fehlschuss eine zweite Granate in kurzem Abstand auf ähnliche Zielposition geschossen werden muss~~

Visier
- [x] SU230 Visier ~~für das SU230 MRDS ersetzen, da Beschwerden aufgrund zu vieler Sichtmodi bei Zweiterem~~ hinzufügen

Weste
- [x] schwarze Weste für SPC machen

**Comment by mordl** [comment]
- Habe das SU230 MRDS Visier getestet. Würde empfehlen das SU230 hinzu zu fügen, aber die vorhandene Variante erstmal im Arsenal lassen.

**Comment by E-for-Eron** [comment]
> * Habe das SU230 MRDS Visier getestet. Würde empfehlen das SU230 hinzu zu fügen, aber die vorhandene Variante erstmal im Arsenal lassen.

In Ordnung, wie kommt es zu der Gedankenänderung?

**Comment by E-for-Eron** [comment]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper
Ich habe aktuell eine ATGM für Jets mit eingefügt, die automatisch per TV-Seek sich Fahrzeuge auf ihrer Flugbahn sucht, anfliegt und zerstört. Natürlich würde damit die Abhängigkeit von Lasern und dem Teamwork von Bodentruppen verloren gehen, ABER: 
- es fliegt das nächstbeste Fahrzeug ohne Freund/Feind Erkennung und zerstört damit ebenso eigene bzw zivile Fahrzeuge
- es ist für Situationen gedacht, in denen schnell Hilfe benötigt wird oder ein Laser nicht dauerhaft auf ein Ziel gehalten werden kann
- pro Pylon gibt es 3 Laserguided ATGM oder 1 TV-Seek ATGM, sodass alleine durch die begrenzte Verfügbarkeit noch ein zusätzliches Balancing entsteht
- die ATGM kann nicht wie die Laserguided Raketen zielgenau ein bestimmtes feindliches Fahrzeug ausschalten (Konvoi) und auch nicht zweckentfremdet werden (im Notfall könnte man mit einer Anti-Tank Laserguided Rakete auch auf ne Scharfschützenstellung schießen)
