### ISSUE TITLE
DAGR

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#245]
Die neuen DAGR fliegen ungelenkt, bis sie innerhalb eines begrenzten Bereiches Feind erkennen und von dort aus an mit leichten Auto-Korrekturen ein Ziel anfliegen. Das System funktioniert tadellos, wenn es an einen Pylon eines Jets (A-10) angebracht wird, versagt aber, sobald es an den Pylonen eines Helis kommt (AH-6). 
CgfAmmo/Magazine/Weapon sollten identisch sein, nur die Vehicle Class ändert sich. An welcher Regelung/Vererbung/Bedingung könnte dieses Problem seine Ursache haben?

**Comment by shukari** [comment]
Vergleich mal die configs per debugcodr
