### ISSUE TITLE
Ausdauer

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#249]
Die Ausdauer muss, abhängig vom Gewicht, angepasst werden. Es soll aber keinen Leistungseinbruch geben, dass wir langsamer als aktuell voran kommen. 
Zwei Personen mit denselben Rollen und 10kg Gewichtsunterschied trennen bei Sprint bis zur Erschöpfung lediglich ~3sek, was weniger als 25m Differenz bedeutet.

Erster Vorschlag: die ACE Variabel "Gewichtsfaktor" nach oben schrauben, aber den "Leistungsfaktor" so anpassen, dass 33kg Gewicht von einer normalen Rolle als Standard gelten und äquivalent zum aktuellen Status Quo sind. Eine lineare Abhängigkeit 1:1 als Berechnung, soll heißen 33kg = 100% / 25kg = 124% / 35kg = 94% aktueller Ausdauer. 

Als zweiter Vorschlag: die ACE Variabel "Gewichtsfaktor" über die Abhängigkeit 1:1 schrauben, zu einem Verhältnis 1,5:1 ( 33kg = 100% / 25kg = 136% / 35kg = 91%), aber dafür den Erholungsfaktor zu erhöhen. Damit würde der Unterschied zwar leicht größer, aber selbst die Personen mit 35kg würden durch den höheren Erholungsfaktor mit den aktuellen Ausdauerwerten mithalten. 

Ich selbst wäre für den zweiten Vorschlag.

Edit: eine Person mit 35kg kann ca 180m sprinten; eine mit nur 10kg etwa 50m weiter......da stimmt doch was nicht in der Logik. Gerne also auch ein höheres Verhältnis als 1,5 : 1 , aber vllt denke ich da zu extrem.

**Comment by mordl** [comment]
Schwieriges Thema in meinen Augen. Kommt eher darauf an ob die Spieler das wollen. Manche stehen mehr auf Hardcore Gameplay, als Andere. 

Etwas das mich persönlich stört ist, wenn man nur einen Balken Ausdauer verloren hat und anfängt mit der Waffe so stark zu wackeln, dass dir ein Betrunkener schon Konkurrenz beim Schießen machen kann.
Dem könnte abgeholfen werden durch einen Toleranzbereich. Zum Beispiel eine Menge an Audauer die ein Spieler verbrennen kann ohne seine Zielgenauigkeit beim Schießen zu beeinträchtigen. Würde überschlagenes Vorgehen unterstützen.

Ein anderer Aspekt wäre das unterschiedliche Gewicht des Equipments. Sturmgewehre wiegen zwischen ca. 2,5 - 3,5kg (kein ULG) ohne einen merkbaren Leistungsunterschied auf 300-500m. Manche tragen gerne eine Pistole, Andere nicht. Westen schwanken um ca. 4kg, Helme um 0,5kg, ebenfalls ohne auffallenden Leistungsunterschied. Somit müsste auch dafür ein Toleranzbereich eingeführt werden, in dem sich Spieler bewegen können ohne Vor- oder Nachteile. 

Was wäre mit den Rollen die an sich mehr tragen? AT, Sniper mit M107, Munitionsträger zum Beispiel.
Ein AT unter 40kg kann sich kaum als richtiger AT bezeichnen lassen. Diese Rollen bräuchten ein Limit wie stark ihre Waffen schwanken. Zugegeben ich bin mir nicht ganz sicher wie Ausdauer und Waffenschwanken zusammenarbeiten. 

Persönlich unterstütze ich Anpassungen von der Ausdauer, um Leute die sich nur vollmachen bis zum Limit am Arsenal zu bestrafen und die Leute, die Nachdenken was sie wirklich benötigen, zu belohnen.

**Comment by E-for-Eron** [comment]
Aktuell gibt es kaum einen Unterschied zwischen 35kg und 25kg Gepäck und damit ist das eher genau das Gegenteil von Hardcore, sondern Arcade- praktisch hast du hier deinen Toleranzbereich und zwar von 10kg...

Diese Rollen haben bereits Boni bekommen, aber falls es notwendig ist, können wir diese nochmal anpassen:

// erhöhte LoadAusdauer - AntiTank / Muniträger  / Pionier
if (isNil "TB_origin_loadFactor") then {TB_origin_loadFactor = ace_advanced_fatigue_LoadFactor};
ace_advanced_fatigue_LoadFactor = [TB_origin_loadFactor, TB_origin_loadFactor / 2] select (_rolle in ["aaat", "trag", "pionier"]);

// erhöhter Anti-Verwackler - AntiTank / Muniträger / Pionier / Unterstützungsschütze / Scharfschütze
if (isNil "TB_origin_swayFactor") then {TB_origin_swayFactor = ace_advanced_fatigue_swayFactor};
ace_advanced_fatigue_swayFactor = [TB_origin_swayFactor, TB_origin_swayFactor / 2] select (_rolle in ["aaat", "trag", "pionier", "mg", "sniper"]);

**Comment by shukari** [comment]
Meine Meinung dazu... sollte etwas mehr spezialisiert werden... wenig mitgenommen belohnt usw.
ABER es darf auf keinen Fall unser Spiel verlangsamen. Wir sind jetzt schon arsch langsam... brauche jetzt nicht noch alle 2min eine Ausdauerpause.

**Comment by E-for-Eron** [comment]
@shukari zu Edit2: wenn wir mit einem linearen Übergang arbeiten, kann man auch direkt den allgemeinen Ausdauerwert hochpacken, das wäre eindeutig nicht so kompliziert.

Planung ist, dass unser aktuelles Maximalgewicht der neue Standard für Ausdauer wird und alles darunter einen Bonus bekommt.
