### ISSUE TITLE
Neue Fraktionen

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#250]
Wie sieht es mit den neuen Fraktionen aus die ich dir geschickt habe. War das so Ok? Ist schon was gemacht worden?

**Comment by shukari** [comment]
Ähm.... Ähm...
Laut WA Verlauf sehe ich das du mir was gesendet hast. Habe aber keinen Plan mehr was es war und ich kanns nicht mehr downloaden.
Tut mir Leid... shukari macht shukari Sachen... kannste nochmal hier hochladen und schreiben was genau... dann KANN ich es NICHT mehr vergessen.
sry

**Comment by Culli-TB** [comment]
Ich habe mit den RHS und 3CB Mod neue Fraktionen erstellt die du zu einem Mod oder in den TB-Mod packen wolltest. Zweiter Vorschlag war Iraqi Syrian Conflict: https://steamcommunity.com/sharedfiles/filedetails/?id=874530860&searchtext=Iraqi-Syrian+Conflict


[Fraktionen.zip](https://github.com/TacticalBaconDevs/TBMod/files/3298042/Fraktionen.zip)

**Comment by shukari** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1771335720

**Comment by shukari** [comment]
Machste ja
