### ISSUE TITLE
Things to do, wishs and thoughts

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#251]
- [x] Sniper Waffentasche geben
- [x] Schalldämpfer/Munition für Mk18 für Stealth Missionen erstellen
- [x] Kiste für TOW o.ä. nach Vorbild der HMG Kiste (in eine Kiste Sandmauern, falls nicht vorhanden)
- [x] Kiste für Luftabwehr
- [x] Status Squad Radar/Symbole
- [x] ~~Fast Roping benötigt aktuell nicht die neuen ACE Seile, die bereits in der Equipmentkiste sind (unter ACE uncategorized Item als notwendig dafür einstellen)~~
- [x] ~~dass KI mehr Granaten wirft~~ kann der Zeus genauer übernehmen, ich sehe von der Anpassung ab
- [x] ~~Default Layouts überprüfen~~ das möchte Darky weiterhin in der Hand haben
- [x] Magazine mit Patronen befüllen, benötigte Zeit dafür überprüfen, vllt runterschrauben
- [x] Script Heli Spawn (durch Eric ermöglicht )
- [x] Morphium negative Effekte leicht verringern, Epi Wirkung leicht verlängern
- [x] HLW /Blutfließrate erhöht
- [x] Skins für Nyx und UGV
- [x] Skins für Culli (Hosen, leichte Westen, Shemaghs, Shirts,Flaggen)
- [x] Equipment Kiste  aktuell nicht tragbar
- [x] Fehlermeldung Delaygranate - Kiste
- [x] AP Mine Bomb for L159
- [x] Hellcat RHS Flares
- [x] Blutvolumen Änderungen
- [x] DAGR entfernen Pylonen
- [x] MK44 Bushmaster AP/HE Munition Reichweite prüfen
- [x] Namen Waffen Bomben
- [x] SMAW/MAAWS
- [x] 12.7mm Explosion aoe Minigun

Wermut ist an mich herangetreten und hat einen Wunsch nach einem PvP Event in einer kleinen Arena in Paintball Format geäußert. Er hat mir dazu direkt auch einen Link geschickt (http://www.armaholic.com/page.php?id=28087), auch wenn ich denke, dass normale Handfeuerwaffen es dafür ebenso täten. Jede Meinung von euch @TacticalBaconDevs/developer @TacticalBaconDevs/helper ist gerne gehört. Vllt gibt es bereits dafür im Editor bereits Module- wenn sich damit jmd auskennt, nur her mit deinen Infos. Für mich hat das aktuell aber eine untergeordnete Rolle, da es ein Sondertermin werden würde und somit frühstens Mitte/Ende kommenden Monats in Frage käme.

**Comment by IDarky** [comment]
>  dass KI mehr Granaten wirft
bin ich dagegen. Lässt mich Kontrolle darüber verlieren wie schnell ein Trupp vorankommt(als Zeus). Und bestraft zu stark taktische Fehler.

**Comment by mordl** [comment]
Gewicht von SMAV Munition sollte reduziert werden. Da die Spottermunition im Moment nicht funktioniert, kann man nur hoffen auf größere Distanzen zu treffen. AT-Schütze liegt mit Minimalausstattung und SMAV +2 Extraschuss im Großen Rucksack ca. 50kg. Zudem sollten wird den Rückstoß oder Ausdauer von Munitionsträger und AT-Schütze überprüfen. Sobald man einen Balken Ausdauer verbaucht, ist es schon mit 40kg extrem schwer aus der Hocke etwas zu treffen. Entweder das Gewicht und die Größe der Munition reduzieren, oder an der Ausdauer etwas machen.

**Comment by mordl** [comment]
Munitionsträger Zugriff auf Vector geben für AT-Muniträger-Buddy-Teams

**Comment by IDarky** [comment]
Stimme ich zu
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

**Comment by shukari** [comment]
Steht auf meiner ToDo Liste nach SA... geht klar

IDarky <notifications@github.com> schrieb am Mo., 1. Juli 2019, 14:23:

**Comment by E-for-Eron** [comment]
Okay aktuelle Situation:
SMAW hat eine Visierung und Reichweite bis zu 500m, MAAWS eine bis zu 900m.
Die Munition der SMAW wiegt 6kg und die der MAAWS 3-4kg. Es gibt aktuell keinen Grund, überhaupt die SMAW zu verwenden, wenn die Spottermunition nicht funktioniert und man in Zukunft sogar mit Vector die Entfernung bestimmen kann.

Vorschlag:
SMAW: Gewicht der Munition stark reduzieren + HEDP weniger Gewicht als HEAA
MAAWS: Gewicht leicht anheben + HE/HEDP/HEAT Gewichtsunterscheidung anpassen

Meinungen/Anmerkungen dazu?

**Comment by IDarky** [comment]
Spottermunition funktioniert. Ist nur seit einem Ace Update oder rhs Update komplizierter. Früher konnte man per Mausrad zwischen den Munitionstypen wechseln. Derzeit muss man F drücken nachladen und dann mit spottermunition schießen und wieder F drücken um auf scharfe Munition zu wechseln. Aber man sieht nicht welche Munition gerade geladen ist.... So mein letzter Stand

**Comment by IDarky** [comment]
Ich persönlich nutze nur SMAW . Hatte nix dagegen wenn sie Munition leichter gemacht wird

**Comment by shukari** [comment]
@IDarky per Strg+R, also dem check wv Muni das derzeitige Magazin hat, sieht man ob Spotting geladen ist.

Laut meinen Tests vor 10 Jahren war die SMAW gegen Panzer mit HEAA wesentlich besser... bestätigt das die config?

**Comment by shukari** [comment]
> In addition to infantry use, the Marines are considering it to replace the SMAW in combat engineer squads. While the SMAW weighs 2.5 lb (1.1 kg) less loaded, the MAAWS has a greater variety of ammunition available and a maximum effective range of 1,000 meters, twice that of the SMAW; the Marines plan to test both weapons' effectiveness against bunkers to inform their decision.[42]

**Comment by E-for-Eron** [comment]
> Laut meinen Tests vor 10 Jahren war die SMAW gegen Panzer mit HEAA wesentlich besser... bestätigt das die config?

Nein, das lässt sich nicht durch die Config bestätigen. Penetrator sind bis auf den Namen komplett identisch und haben auch keine zusätzlichen Hit-Effekte. Bei der Grundmunition hat die SMAW 0.2 höheres Kaliber, dafür etwas weniger Hit-Schaden. Ich sehe das als fast identisch an.
