### ISSUE TITLE
Arsenale haben einen Sinn

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#255]
Funktion schreiben, womit ich in der Mission blacklisted stuff von leuten entferne und sie bestrafe
- Arsenale bieten nur das was Rollen haben sollen, Missions sind darum zu Bauen oder hier Wünsche zu Änderungen zu melden
- es soll keine Allrounder geben

**Comment by mordl** [comment]
Stimme ich zu, dass Rollen nicht gemischt gehören. Aber ist diese Funktion nicht etwas übertrieben? Oder hast du in letzter Zeit spielbeeinflussende Equipmentweitergaben bemerkt?

**Comment by Er1807** [comment]
Ich schließe mal.
