### ISSUE TITLE
BW Sniper Munition

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#267]
Im Arsenal vom Sniper fehlen Munitionsarten:
BWA3_10Rnd_127x99_G82
BWA3_10Rnd_127x99_G82_AP_Tracer
BWA3_10Rnd_127x99_G82_AP

**Comment by E-for-Eron** [comment]
Ja, vollkommen richtig. Wofür sollen diese Munitionsarten denn verwendet werden?
Aktuell im Arsenal für das G82: 
LRS,  mit Tracer gegen weiche Ziele und erhöhter Reichweite;
HEIAP-T, ebenso mit Tracer, leicht erhöhter Reichweite und geeignet für Panzerungen bis zu 25mm sowie Hardcover/Funkanlagen etc

**Comment by E-for-Eron** [comment]
Es war geplant beim US Sniper Ergebnisse für die Munitionsänderungen einzufahren und diese dann auf das G82 zu übertragen, um die erweiterten Möglichkeiten beide Fraktionen zu geben.
Da es sich in beiden Fällen um dasselbe Gewehr handelt, würde ich identische Munition (SLR/HEIAP-T) vorschlagen.
Dennoch danke für die Erinnerung, komme derzeit nicht bei TB hinterher
