### ISSUE TITLE
Reduktion der Magazin repack time

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#272]
Vorschlag:
Zeit pro Patrone auf 1.1
Zeit pro Magazin auf 1.4
Zeit pro Gurtglied auf 6.0

Von mehreren Seiten kam der Hinweis, dass die Zeit dafür etwas zu hoch sei.
Meinungen dazu?

**Comment by mordl** [comment]
Finde es in meinen Augen in Ordnung so wie es im Moment ist. Ich schieße meine Magazine meistens leer. Wenn jmd. seine Magazine alle nur anschießt sollte das in meinen Augen irgendwo einen Haken haben.

**Comment by Er1807** [comment]
Ich persönlich bin jemand der seine Magazine nach jedem Kampf nachlädt. Ich finde dies nicht schlimm, da man so immer bereit ist. Beim Häuserkampf will ich nicht auf einmal nieder geschossen werden, weil ich nur noch 10 Schuss im Magazin hatte. Ich finde es sollte keinen zu großen Nachteil haben Magazine umzupacken. Im schlimmsten Fall cleart man ein Haus mit 3 Türen und hinter jeder Tür steht ein Gegner. Das wären bei mir dann 3 Angefangene Magazine.

**Comment by shukari** [comment]
Bin jemand der nach 10 Minuten Gefecht 10 angefangene Magazine hat, also so wie Eric... allerdings finde ich es dann acuh gut, das ich für meine Übervorsicht "bestraft" werde.
Bin allerdings dafür, das etwas runter zusetzen... gerade für MGs.

**Comment by shukari** [comment]
MG wurde auf 6 gestellt
