### ISSUE TITLE
Blutdruck Adenosin

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#273]
Habe eine Frage an dem Ausgang eines Experimentes mit folgendem Aufbau:
Spieler an Bein verwundet, blutet aus auf bis Blutdruck 60. 

Tourniquet wird angelegt: Blutdruck bleibt stabil auch auf der hunderter Stelle hinterm Komma.
Nun gebe ich der Person Adenosin in den Arm: Blutdruck steigt um 8 Zähler für die nächsten Minuten und flaut danach wieder ab, bis Blutdruck 60.
Soweit, so normal.

Danach senkt sich der BD jedoch unter die 60 und sinkt immer weiter. Nach weiteren 30min ist er bei 58.9 weiter fallend. Ich habe keine begründete Annahme, dass dieser Trend jemals aufhört. Woran liegt das?

Es ist für uns aktuell nicht von großer Bedeutung, da sich die Reduktion im 1/100-1/1000 Bereich pro Sekunde bewegt (Hochrechnung: 5 Zähler über eine gesamte Missionsdauer), aber dennoch ist das für mich nicht erklärbar.

**Comment by mordl** [comment]
Erinnert mich an ein Experiment, welches ich mit Mike vor Ewigkeiten gemacht habe. War noch mit dem alten Sanisystem. Habe einen Trupp vor einem Angriff mit Epis gepusht um eine Ohnmacht und Herzklopfen vorzubeugen, falls sie verletzt werden. Nur wenn du über den von den Einstellungen als Standard eingestuften Wert gehst, sinkt der BD innerhalb von wenigen Minuten wieder auf den Normalwert. Dieser Wert schien aber, was auch von Gästen mal angemerkt wurde, bei uns niedriger. Dadurch haben wir vor dem neuen Sanisystem nach der ersten Verletzung Herzklopfen bekommen, weil wir an sich schon beim Start der Mission mit einem niedrigen Blutdruck von der Basis losgezogen sind. 
Wenn du aber unseren Standardwert weißt und er drunter geht würde ich vielleicht prüfen, ob etwas mit den Zahlen oder Abläufen vom Adenosin nicht stimmt. Bin wie so oft nicht vertraut mit der genauen Technik und den Zahlen die im Hintergrund laufen.

**Comment by shukari** [comment]
Nur bei uns oder auch im Ace3 "Vanilla"?

**Comment by mordl** [comment]
Kann ich dir leider nicht garantiert sagen. Der Blutdruck war damals auf jeden Fall im unteren Normalbereich, weil er sich unter den Durchschnittswert eingependelt hat, nachdem ich Epis vergeben habe.
