### ISSUE TITLE
Sniper Chat Befehl

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#277]
["altis"] call ace_common_fnc_getMapData 

Als Chat befehl damit sie die Latitude der aktuellen Karte auslesen können hier im Beispiel der aktuellen Karte

**Comment by shukari** [comment]
`ace_common_mapLatitude` wird benötigt

Das ist der quatsch der Recherche:
EGVAR(common,mapLatitude) wird für https://github.com/acemod/ACE3/blob/e2ac18a05d5f646bc7cbc043bcc148fde4c0f5dd/addons/advanced_ballistics/functions/fnc_handleFired.sqf#L123 verwendet

https://github.com/acemod/ACE3/blob/master/addons/weather/functions/fnc_getMapData.sqf setzt die mapLatitude

https://github.com/acemod/ACE3/blob/e592b6b975dc30111ebb59d0e02af5b5db7d66de/addons/common/functions/fnc_getMGRSdata.sqf#L24-L33 wird getMapData verwendet sonst CfgWorld Wert...

Map log und lat aus CfgWorlds:
```
private _long = getNumber (configFile >> "CfgWorlds" >> worldName >> "longitude");
private _lat = -1 * getNumber (configFile >> "CfgWorlds" >> worldName >> "latitude"); // latitude is reversed in arma (negative config values in north)
```

**Comment by Er1807** [comment]
@shukari. Schau doch in den PR

**Comment by shukari** [comment]
Junge... keine Verküpfung und zudem 100 Emails und Benachrichtigungen von
euch...

Eric van Fandenfart <notifications@github.com> schrieb am Mo., 22. Juli
2019, 11:38:

**Comment by Er1807** [comment]
Verknüpfung ist seit 13 Std da
