### ISSUE TITLE
Polizei Skins für WoMi

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#282]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 
Heli/Weste/Helm für ein SWAT Team sind fertig. Jedoch keine gepanzerten Fahrzeuge. Ich kann mich zu keinem Modell tatsächlich durchringen, also gebt mir Vorschläge mit Class Names, welches Fahrzeug ich noch optisch anpassen soll!
Ich empfehle die WoMi mit 3CB Faction zu spielen. Unter der Takistan National Polizei gibt es vernünftige ungepanzerte Polizeifahrzeuge, die man neben den Vanilla Gendarmerie Modellen nutzen kann. Diese könnten auch wir verwenden, wenn gewollt.

**Comment by shukari** [comment]
reicht alles so
