### ISSUE TITLE
TBMod Patchnotes - v1.3.13

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#285]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 
Ergänzt bitte alle Dinge, die von eurer Seite aus noch wichtig zu nennen sind. Diese Liste ist nur ein Vorschlag und weder logisch aufgebaut, noch ausformuliert.

Bereits live

- AH-6 hat auf den inneren Pylonen Zugang auf weitere Waffensysteme
- neue Munition für die Scharfschützenwaffen (G82/Mk11) mit Munition für teilweise erweiterte Gefechtsentfernungen (LRS ggn Inf / HEIAP-T ggn Material / SLV für Stealth Einsätze)
- keine UXO bei eigener Verwendung von Clustermunition
- neue Bomben/Granaten für Flugzeuge und oder dem Mk45: HE Cluster (100x100m ggn Inf), AT Minen Cluster (25x25m), verbesserter weißer Rauch (50x50m), HE Minen Cluster (60x60m APERS Sprungminen)
- weitere Verbesserungen am Mk45 (Anzahl Munitionskästen, bessere HE Wirkung etc) 
- A-10 GAU-8 verbesserte Penetration, dafür weniger Schaden (Besatzungen töten, aber nicht den Panzer zerstören), Camshake Effekt sowie starken Rückstoß gegeben (Vorsicht vor Luftabriss) 
- Hellfire/Maverick Raketen spezialisiert, sowie verbessert; neue Maverick Version mit Autoseek für Flugzeuge integriert (es wird ohne Freund/Feind Erkennung auf das sich am nächsten befindende Fahrzeug im Suchradius aufgeschalten)
- für die meistbenutzten Fahrzeuge  (ca 30 Stück) wurden umfangreiche Anpassungen durchgeführt, um ein realistischeres Bild zu bieten und taktische Vorteile nutzen zu können (Panzerung/Geräuschentwicklung/Radarquerschnitt/IR-Querschnitt/optische Sichtbarkeit/Raketenfrühwarnsysteme/Zielsysteme/Abwehrmaßnahmen/Waffenplattformen)
- L-159 als neues Flugzeug für Piloten ohne Jet DLC
- ULG spezialisiert: HEDP besser ggn Panzerungen ; HE nur noch ggn Inf brauchbar ; neue Slug kann verschlossene Türen aufschießen
- neue NV/IR ULG als Zielmarkierung für Laserzielsysteme und lasergesteuerte Bomben/Raketen (Bomben schalten automatisch während des Falls auf, ULG ist auf Radar sichtbar als Laserziel)
- Blut fließt nun doppelt so schnell in den Körper (zukünftige Anpassungen vorbehalten)
- HLW ermöglicht nun je nach Ort der Durchführung (Feld/med Fhrz/med Einrichtung) bis zu 400/600/1000ml schnellere Blutzufuhr
- Morphium geringere negative Effekte, Wirkzeit aller anderen Medikamente auf 5min vereinheitlicht
- neues Default Layout für USA (ACHTUNG: Leuchtspurmunition als Standard bis auf Scharfschützentrupp) 
- Scharfschütze kann Waffentasche mit sich führen und Hauptwaffe wechseln
- US Raketenwerfer/Stinger überarbeitet (MAAWS bis zu 900m Reichweite/SMAW bis zu 500m; Gewichte der Funktion angepasst (HE/HEDP wiegt nun bedeutend weniger als HEAT)
- IV' s um 40% Volumen erhöht bei gleichbleibenden Gewicht
- neue Kisten für TOW/GMG und FlaRak
- mit dem Chatbefehl „#sniper“ können mit der ausgerüsteten Waffe/Munition Werte wie der Breitengrad auf der Karte/Mündungsgeschwindigkeiten abhängig von der Außentemperatur etc ausgelesen werden
- Flugverhalten/Beschleunigung bei Flugzeugen etc angepasst
- viele viele weitere Sachen wie Skins etc
- Crash Helper funktioniert wieder
- Rufnahmen Schild überarbeitet (reservierte Namen, dafür neue rein usw)
- #safe verbietet nun das schießen 
- Masse beim Sligloading wird nun beim owner des Fahrzeuges gesetzt
- Für besondere Leute gibt es nen besonden Spectator (ACE Spectator)
- Modul zur ACE Frachtgrößen änderung während der Mission
- anbringbare Flaggen mit Ziffern an Fahrzeugen
- S.W.A.T. für WoMi (Weste, Helm, Heli)
- Bundeswehr Arsenalanpassungen (G38, Visiere und Bugfixes)
- Eden TB Attribute, Animationen sind abbrechbar (50m Schüsse oder Verletzung)
- <b>stärkster und effektivster Mörser Codename "Shukari" im Arsenal der Infanterie<b>
- Neuer Builder für den TB Mod

**Comment by shukari** [comment]
Nicht Zuhause, deswegen nur über Weboberfläche kontrollierbar, habe etwas hinzugefügt, sonst gut.

**Comment by Er1807** [comment]
Bin soweit durch. Hab mal was hinzugefügt

**Comment by IDarky** [comment]
>Bundeswehr Arsenalanpassungen (G38, Visiere und Bugfixes)

+ Default Layouts

- LDF Arsneal +Nachschub

**Comment by Er1807** [comment]
Ldf ist doch noch gar nicht drin.
