### ISSUE TITLE
Lautstärke im Helikopter

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#290]
Habe immer Problem mit der Lautstärke im Helikopter. Verstehe die Leute nicht wenn Sie normal sprechen. Habe das Gefühl das der Sound nicht mehr automatisch nach untern geregelt wird.
Funktioniert das nicht mehr oder ist das nur bei mir so. Kann man da was machen?

**Comment by shukari** [comment]
Brauche neues Feedback von Dir, habe es von 50% auf 60% gestellt, besser?

**Comment by Culli-TB** [comment]
Werde am Samstag mal darauf achten.
