### ISSUE TITLE
Verschiedenes

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#291]
- [x] Mk11 ebenso für Waffenspezialisten
- [x] M134 Schaden überprüfen, vllt buffen
- [x] MG 5.56/7.62 Schaden erhöhen
- [x] VCOM Unterdrückung für MG entfernen o.Ä. (MG soll einen Sinn wieder bekommen)
- [x] alle Raketen/Bomben/Abwehrsysteme überprüfen (RHS)
- [x] Sanizeug Rucksäcke
- [x] DMR Visierung überdenken
- [x] LRS beim Spez als Standard raus
- [x] Ausrüstung mit Sanisymbol (Debatte)
- [x] O-U Werfer M72 HE für weitere Spieler freischalten (Debatte)
- [x] Mun/Werfer Kiste zu schwer
- [x] Uniform Sniper erweitern
- [x] Holo/Combi Sniper
- [x] Micro DAGR GPS einfügen
- [x] rhs_uaz_spg9_chdkz Fehler beheben
- [x] Karten mit Cup,karten ohne Cup+ tbmod, wie er aktuell (Stand 09/19) ist Fehlermeldung "logo.paa" durch cpp Datei entfernen
- [x] Fallschirmsprung- Fremdinteraktionsmenü- Lastenseil --- Option dafür entfernen
- [x] Mk17 ACE Barrel Twist etc
- [x] M107 Cal runtersetzen 
- [x] Spotter Clucker+Entschärfungskit für Spotter (nur noch ausgewählte Sprengladungen verfügbar machen)
- [x] NS Vorsatz für Snipervisier 
- [x] Gun Bag Bug: wenn Gun Bag auf den Bauch geschnallt wird für Fallschirmabsprung, wird die Waffe aus dem Rucksack gelöscht (BUG- an ACE Team weiterleiten)
- [x] mehr NV Googles in Kiste
- [x] Schalldämpfer Malus für Visieranimation geben
- [x] Mk17 Vererbung - RHS ausschalten und testen
- [x] WSp: Rucksack weg, Animation Waffe umrüsten, O-U weg
- [x] Nachbeben von Bomben
- [x] Rüstung neue RHS Fahrzeuge
- [x] Gewichte Waffen überprüfen # Clacker
- [x] BUG Decals T-72 bzw RHS-Panzer 
- [x] Cam Shake Mk45/Hydra 70 von Standard AH-1Z schwächer, 227mm hinzufügen
- [x] 155mm LaserGuided ggn Panzerung
- [x] Grenadier Entfernungsmesser
- [x] Micro DAGR GPS für alle
- [x] WSP erstes LRS Magazin entfernen
- [x] Culli Waffenliste
- [x] Merkava Kaliber 17, Shukari Nerf Recoil
- [x] Bergen Skin
- [x] optic_mrco
- [x] USAF Mod - Complete
- [x] Bolt Action für Sniper statt WSP
- [x] Default Layouts US/UK/RUSS
- [x] Predator Drohne Pylonen nicht anwählbar bei Spawn
- [x] DAGR RHS umbenennen (2x,4x)
- [x] Wiesel Lautstärke etc prüfen
- [x] UH-80 Triebwerkleistung erhöhen
- [x] Trainingsserver Stomper tauschen/FLugzeugträger anpassen
- [x] US/RUSS/UK Standardlayout anpassen
- [x] Mk17 Munition/Malfunction anpassen
- [x] GBU-12 in GBU-12 Paveway II umbenennen
- [x] Pandur 30mm AP und HE Reichweite etc angleichen
- [x] 114 L übertragen
- [x] Helikopter Absturzsicher machen, bestimmte Modelle Sekundärexplosionen entfernen
- [x] RHS Gref auf Trainingsserver asl Standard
- [x] Repacktime  Patrone 1.1 Magazin 1.7 Gurt 6.0
- [x] Pilotenhelme Panzerung
- [x] Support Modul Gunship Waffen
- [x] AGM 65 CCD verstärken
- [x] Überhitzung von Waffen überprüfen, vllt anpassen (MGs, Mk17)
- [x] DEFAULT LAYOUTS NACH ANNAHME VON ACE 1.13.1
- [x] rhsusf_acc_su230_mrds entfernen + WSP Visier dem Sniper geben
- [x] Darter Batterie auf 60-90min verlängern
- [x] Flaggen CADPAT
- [x] Wiesel2 Radar+FlaRak einbauen
- [x] Splittergranaten entfernen
- [x] MG mit Beta-C Magazin
- [x] RHS Raketen rausschmeißen
- [x] M24 DMG erhöhen
- [x] BW/UK Westen Werte überprüfen
- [x] MGs Genauigkeit anpassen

**Comment by E-for-Eron** [comment]
- [ ] Mk11 ebenso für Waffenspezialisten
- [ ] M134 Schaden überprüfen, vllt buffen

**Comment by shukari** [comment]
zu 1. wollen wir das?
zu 4. kP was du damit meinst

**Comment by E-for-Eron** [comment]
- zu 1. wurde sich von mehreren Seiten gewünscht, dass der Waffenspezialist auf seiner 7.62mm Schalldämpferkapazitäten erhält, was damit gelöst werden würde; er wird aber nicht die Munition vom Sniper erhalten, sondern den Standard verwenden müssen und damit auch nur bis max 1000m wirken können
- bei 4. geht es darum, dass im Endeffekt der MG Schütze unterdrücken kann; also dass VCOM nicht das letzte Wort in Sachen Unterdrückung angibt

**Comment by shukari** [comment]
> bei 4. geht es darum, dass im Endeffekt der MG Schütze unterdrücken kann; also dass VCOM nicht das letzte Wort in Sachen Unterdrückung angibt

Immer noch nicht verstanden.... wenn wir mal auf dem TS3 sind, klären wir das.

**Comment by TBMakuro** [comment]
- Handfeuerwaffen Sinnvoller machen -

Was kann ich mir darunter denn vorstellen ? Die sind doch so wie sie sind für ihre erdachten Situationen vollkommen in Ordnung ?

Ein extra Punkt wär noch ein Modul das jeden Spieler ins Reich der Träume schickt wenn sie versuchen ohne Rauchgranaten die Base zu verlassen... ( war eig als Scherz gemeint aber jetzt wo ich drüber nachdenk find ich die Idee garnicht so schlecht... )

**Comment by E-for-Eron** [comment]
> * Handfeuerwaffen Sinnvoller machen -

Das ist für mich nur die Erinnerung zur Überprüfung, weil kaum Handfeuerwaffen mitgenommen werden. Warum die 2kg+ mitnehmen, wenn mit fast jedem Gewehr ohne Probleme auch im Nahbereich gearbeitet werden kann. Ich überlege mir mehrere Anpassungsmöglichkeiten, wäge die ab, und falls sinnvoll, werden sie vorgeschlagen. 

Bezüglich des Moduls: es wird in den nächsten Wochen weitere Informationsvideos geben, darunter auch Ausrüstungspunkte, wie Rauchgranaten.

**Comment by IDarky** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2285031150 @E-for-Eron  bezüglich mehr Piloten uniformen

**Comment by mordl** [comment]
Bitte mal durchgehen, was davon schon erledigt, oder veraltet ist. 

Zurzeit sehe ich keinen großen Sinn an neuen Munitionsarten. Auch werden die Unterstützungen eher wenig genutzt. Daher ist der Aufwand dem Zweck zum Teil nicht wirklich wert.

**Comment by shukari** [comment]
Nicht erledigte Aufgabe in Ticket #439 hinzugefügt!
