### ISSUE TITLE
MP-Missionen abspeichern

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#302]
Können wir damit etwas anfangen (zB.: für die WoMi's)?
https://steamcommunity.com/sharedfiles/filedetails/?id=1836169957

**Comment by Er1807** [comment]
Warte ich schau mal kurz in unsere Repo. Ah was seh ich da Persistence. Gibt es schon lange

**Comment by shukari** [comment]
Haben wir bereits schon wie Eric meinte... trotzdem müssen wir ums das vor der WoMi nochmal anschauen und vll optimieren
.

**Comment by Culli-TB** [comment]
Alles klar.
