### ISSUE TITLE
Persistence 

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#307]
Persistence aufm Server funktioniert nur zum teil. Es wird gespeichert, aber `[profileNamespace, "TB_persistence_savedNames", []] call BIS_fnc_getServerVariable`  funktioniert nicht. Persistence vom client funktioniert, kann aber nicht alles speichern.

Idee: Persistence wird immer auf dem Server ausgeführt und die Daten optional auch an den Client geschickt. 
 Weitere Ideen @shukari ?

**Comment by shukari** [comment]
> Persistence vom client funktioniert, kann aber nicht alles speichern

Wie ist das zu verstehen?
