### ISSUE TITLE
NotfallWaffen Kiste zu einer Notfallkiste umwandeln

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#309]
Aktuell dient die NotfallWaffen Kiste für Trantüten, die ihre Waffen vergessen. Das ist bisher auch einmal geschehen; aber ich fände es gut wenn wir neben dieser Funktion noch weitere Sachen hinzufügen, um sie zu einer kleinen Notfallkiste umzuwandeln für Szenarien, bei denen Einzelpersonen hinter feindlichen Linien ein Minimum an Versorgung benötigen, ohne das direkt 5 verschiedene Kisten abgeworfen werden. Bsp für abgestürzte Piloten/Sniperteam/von der Gruppe abgeschnittene Personen etc...
@TacticalBaconDevs/developer @TacticalBaconDevs/helper

**Comment by shukari** [comment]
Kein Frage, sondern machen.
Die Notfallkiste, habe ich einfach so damals gemacht, genauso wie die nachtkiste als Zeushilfe.
Wird nie benutzt, da wir andere Möglichkeiten des helfens, sowie erfahrendere Zeuse nun haben.
