### ISSUE TITLE
CBU-85 Cluster Pylon

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#315]
![image](https://user-images.githubusercontent.com/42013222/64182664-dc552900-ce68-11e9-9c32-e08bf42b5b0d.png) 
Getestet mit: [TB] MinimalModset
Keine Script Errors werden ausgeworfen

Diese Konfiguration ist nicht möglich wenn man mit TBMod startet. Bei Missionsstart sind diese Pylonen leer. Gleiches Problem bei anderen Jets auch hier sind bei Missionsstart benachbarte Pylonen leer. 
Problem entsteht nur bei CBU-85 Cluster.
Nimmt man 4 von den CBU-85 Cluster klappt alles wie gewohnt ist aber nur bei der Wipeout möglich.
Ohne TBMod ist diese Konfiguration möglich.

**Comment by Er1807** [comment]
Ist dieses Problem noch wichtig? Haben Jets nicht sehr häufig und meistens werden die von den Spielern noch angepasst. Zudem sind CBUs Bomben die sehr selten/mit besonderem Grund eingesetzt werden.
