### ISSUE TITLE
Atmo Musik Funkstationen

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#317]
Für in Häuser versteckte Basen oder so.

https://community.bistudio.com/wiki/playSound3D
`playSound3D [getArray (configFile >> "CfgMusic" >> "RadioAmbient1" >> "sound") # 0 + ".wss", bob, false, getPosASL bob, 5, 1, 10];`

https://community.bistudio.com/wiki/Arma_3_CfgMusic

**Comment by TBMakuro** [comment]
Hier häng ich mich gleich mal mit an.

Für eine meiner Missionen habe ich einige Radios in Gebäuden verteilt die festgelegte Titel in Dauerschleife abspielen sollen.

Eric hat mir hierfür auch schon etwas zusammengeschustert was wenn ( im "Exec Code Module" ) ausgeführt erste Sahne funktioniert.

if (isServer) then { 
    TB_abordMusic = false; 
    [] spawn { 
        waitUntil { 
            playSound3D ["A3\music_f_EPC\Music\C_EA_RadioMusic2.ogg", Radio_2, false, getPosASL radio_2, 1, 1, 50];  
            uiSleep 72; 
            (!alive Radio_2 || TB_abordMusic); 
        }; 
    }; 
};

Leider ist das Modul aber aus diversen Gründen in unseren Missionen gesperrt....

**Comment by Er1807** [comment]
Es gibt immer noch eine Init.sqf um sowas auszuführen

TBMakuro <notifications@github.com> schrieb am Fr., 4. Okt. 2019, 23:29:

**Comment by shukari** [comment]
@TBMakuro keine Sorge bis nächste Woche haste ein Modul oder Code von mir dafür!
