### ISSUE TITLE
Umfrage Gewichte/Ausdauer

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#321]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 

Sobald #249 umgesetzt worden ist und das Gewicht tatsächlich einen maßgeblichen Einfluss auf die Ausdauer nimmt, möchte ich gerne die aktuell runtergenommenden Gewichte für Javelin etc auf höhere Werte wieder setzen, um dafür zu sorgen, dass mit solchen 12-16kg schweren Geräten nicht Berge bestiegen werden, ohne eine Malus davon zu tragen, sondern sie nur für kurze Strecken bzw innerhalb von Fahrzeugen transportiert werden. Das gilt auch für bspweise das M107 für den Sniper und seine Munition, die aktuell nur einen Bruchteil wiegen. 
Grundgedanke dahinter soll sein, die besten und schwersten Systeme nur dann mitzunehmen, wenn es taktisch einen Sinn ergibt bzw die Personen auch belohnt werden, die sich nicht bis zum Brechen vollpacken. 
Für den Transport sehe ich keinerlei Problem, die Werfer/Waffen ins Inventar zu packen, statt extra ACE-Kistenslots dafür nutzen zu müssen. 

Gegenmeinungen/Anmerkungen/Wünsche?

**Comment by mordl** [comment]
Finde die Idee nicht verkehrt, nur diese Waffen werden ohnehin kaum genutzt.

**Comment by Culli-TB** [comment]
Hört sich realistisch an. Bin dafür :)

**Comment by shukari** [comment]
Sehe das bisschen wie @mordl zB die Javilin nimmt keiner.
Generell bin ich aber dafür ein GANZ BISSCHEN ins derzeitige System einzugreifen, jemand der nicht alles auf 100% vollpackt sollte belohnt werden.
Allerdings ist die Frage, dann zieht der eine der vollgepackt ist den ganzen Trupp runter und man braucht 100 Jahre von A nach B...

**Comment by E-for-Eron** [comment]
In dem Fall würde es ja endlich Sinn ergeben die Maximalgewichtsgrenze gesetzt zu haben. Aktuell macht es ja keinen Unterschied, ob man 25kg oder 35kg mit sich trägt. Und 35kg würde ich als Standard setzen, alle die weniger schleppen, sind schneller aber der gesamte Trupp braucht trotzdem höchstens so lange wie aktuell die Trupps auch benötigen.

**Comment by mordl** [comment]
Würde empfehlen zuerst die Maximalgewichtsgrenze anzupassen und auf Feedback warten, bevor wir anfangen das Gewicht von einzelnen Gegenständen zu verändern.

**Comment by E-for-Eron** [comment]
In Ordnung! Als Hinweis: die maximale Gewichtsgrenze wird sich nicht ändern, soll heißen Niemand wird den Unterschied bemerken, wenn er nicht extra weniger trägt.

Neben den oben genannten Systemen können auch weitere Sachen, wenn gewollt, angepasst werden: 
-Westen, deren Rüstungswerte/Gewichtswerte für verschiedene Trefferbereiche angepasst und großen Einfluss nehmen könnten. Die am besten Schützenden könnten bis zu 12kg(Traumaplatten etc) wiegen.
-Rucksäcke leicht vergrößern, um einen größeren Spielraum zwischen leicht und schwer bepackt zu erschaffen. Wenn man wissentlich in einen Kampf fährt, würde man immer ein/zwei Gurte mehr mitschleppen- werden ja eh verballert.

Frage ist jedoch, ob das nur eine Scheinfreiheit wäre, weil Truppführer entsprechend ihres Auftrags Gewichtsgrenzen etc setzen, die jeder sehr wahrscheinlich ausreizen wird.

**Comment by Culli-TB** [comment]
Ist das den wirklich nötig das wir so tief in das ganze eintauchen und ständig Sachen bzw. Werte verändern? Ich glaube die wenigsten Interessiert das und werden es auch gar nicht bemerken. Ist das die ganze mühe wert? Wieso wollt ihr jetzt das wir noch mehr Muni mittragen können. Macht doch viel mehr Spass wenn die Muni im Kampf knapp wird und wir hoffen müssen das der Muniträger noch was hat oder Nachschub eingeflogen wird. Mir ist das ganze eingreifen in die Werte langsam zu viel. Man sollte nur da Verbesserungen machen wo es auch wirklich nötig erscheint oder den Spielspaß erhöht. Auch das ständige anpassen der Missionen nervt so langsam. Ki hält weniger Treffer aus als der Spieler, dann ist es mal wieder umgekehrt, dann wird der Wert beim nächsten mal wieder verändert. Und dann passiert es wie am Samstag das man ein halbes Magazin braucht bis einer umfällt. Aber ich schweife vom Thema ab :D. Vielleicht bin ich auch für diese Experiment schon wieder zu alt :))

**Comment by BeLink13** [comment]
Bin da ganz bei Culli :)

**Comment by shukari** [comment]
@Culli-TB 
Muss hier 11 Tage später mal zu deiner Nachricht was schreiben. Das ist ein kleiner Schlag ins Gesicht für alle die hier versuchen Sachen zu optimieren. Das einmal in einer Mission seid etwa 1 Jahr das Leben der KI verändert wurde ist nicht ein "ständige anpassen" und meiner Meinung warst du es der mit Missions kam wo wir auf einmal nur begrenzt Rucksäcke mitnehmen durften.
90% der Änderungen die ich überwache sind Buffs für unser Spiel, alleine die Blutänderungen (HLW, Blutfluss usw) ermöglichen es uns mit dem erweiterten System zu spielen und trotzdem nicht 80% der Zeit mit dem Sani zu interagieren.

Ich respektiere deine Meinung, aber du scheinst dir nur oberflächlich eine Meinung gebildet zu haben, was ich verstehen kann, da hier extrem viel passiert. Aber Änderungen die wir machen sind meist wohl überlegt. Leider können wir kein detailliertes Changelog schreiben, da das zu viel Zeit kostet und wir das hier alles in unserer Freizeit machen. Sachen wie unser Recoilsystem, Medicsystem und Arsenalsystem machen TB zu dem was es ist meiner Meinung nach. Viele kriegen es bewusst nicht mit und genießen es einfach.

P.S.: Beim Kontrolllesen viel mir auf das der Text ETWAS passiv aggressiv rüberkommt, soll es aber nicht... nur mal meine Meinung zum Thema, habe Dich lieb ❤️

**Comment by Culli-TB** [comment]
Alles Ok shukari! Ich weiß doch das du mich lieb hast :D

**Comment by shukari** [comment]
@E-for-Eron das hier wurde abgeschlossen richtig? Wir lasssen es... wenn ja bitte closen ;D
