### ISSUE TITLE
Piloten helme

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#322]
Allen Pilotenhelmen komplettes Nachtsicht geben für mehr Auswahl bei Nacht

**Comment by shukari** [comment]
Konzeptfrage an @E-for-Eron 
Ich habe keine Ahnung warum genau... finde persönlich in der Nacht sollten Piloten extremes können Beweisen und nicht 0815 NV, aber das ist meine Meinung.

**Comment by TBMakuro** [comment]
Sehe das ähnlich wie Shukari...

Und Aufgrund der allgemeinen Unbeliebtheit von Nachtmissionen denke ich fast das der angestrebte "Nutzen" den Aufwand rechtfertigen würde.

**Comment by E-for-Eron** [comment]
Können gerne darüber nochmal sprechen, hier erstmal meine Meinung:
Pilotenhelme werden eher selten von Mitspielern bzw gar nicht von der eigenen Person gesehen. 
Hinzukommt die Nachtsicht bei der auf alles geachtet wird, außer auf Farben, weil die eh nicht dargestellt werden. Somit wäre die äußere Form das einzige Merkmal. Wenn die Anfrage rein auf Optik basiert, fehlt mir da das Verständnis...

**Comment by IDarky** [comment]
![image](https://user-images.githubusercontent.com/42013222/66345800-0e1e4b80-e951-11e9-8822-0191eea5431b.png)
Er hat bereits einen Helm der volle Nachtsicht gewährt. H_PilotHelmetFighter_B
Mir gings nur darum die Auswahl an Helmen in der Nacht zu vergrößern wenn man volle Nachricht haben möchte.

**Comment by mordl** [comment]
Ich mag keine alten Issues wo Stille herrscht. 
Sehe ebenfalls keinen Sinn extra Arbeit nur für Äußerlichkeiten.
Wenn also nichts wirklich Wichtiges in diesem Issue aufkommt, welches Handlungsbedarf erfordert, sollte man den Issue schließen.
