### ISSUE TITLE
Modul Vorschlag: Verhindern das KI minen legt

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#324]
oder wie es Eric in ner Mission gemacht hat das alle Minen immer wieder gelöscht werden

**Comment by IDarky** [comment]
bei weferlingen legen die minen in häuser und schießen dann auf die wenn der feind nah ist

**Comment by E-for-Eron** [comment]
Solange es optional bleibt, gehe ich konform. Für fast alle IS/Taliban Missionen möchte ich, dass Minen/Sprengsätze gelegt werden.

**Comment by IDarky** [comment]
War optional gemeint 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04.10.19, 08:29, E-for-Eron <notifications@github.com> schrieb:
Solange es optional bleibt, gehe ich konform. Für fast alle IS/Taliban Missionen möchte ich, dass Minen/Sprengsätze gelegt werden.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/TacticalBaconDevs/TBMod/issues/324?email_source=notifications\u0026email_token=AKAREJUCQHOPWCPDEYWMQLLQM3PEVA5CNFSM4I5GZQJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAKTAFA#issuecomment-538259476",

"url": "https://github.com/TacticalBaconDevs/TBMod/issues/324?email_source=notifications\u0026email_token=AKAREJUCQHOPWCPDEYWMQLLQM3PEVA5CNFSM4I5GZQJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAKTAFA#issuecomment-538259476",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by shukari** [comment]
Ist in VCOM Settings auf 0 oder 5% gestellt... hast du die Settings richtig importiert auf dem Trainingsserver im SERVER Tab IMPORTIERT?!?
Überprüfe das mal gleich wenn du kannst was auf dem SERVER Reiter bei VCOM beim Mine Ding eingestellt ist.

**Comment by IDarky** [comment]
// VCOM SETTINGS
force force VCM_ActivateAI = true;
force force VCM_ADVANCEDMOVEMENT = true;
force force VCM_AIDISTANCEVEHPATH = 0;
force force VCM_AIMagLimit = 2;
force force VCM_AISNIPERS = true;
force force VCM_AISUPPRESS = true;
force force VCM_ARTYDELAY = 30;
force force VCM_ARTYENABLE = false;
force force VCM_ARTYSIDES = [WEST,EAST,GUER];
force force VCM_CARGOCHNG = true;
force force VCM_ClassSteal = false;
force force VCM_Debug = false;
force force VCM_DISEMBARKRANGE = 100;
force force Vcm_DrivingActivated = false;
force force VCM_ForceSpeed = true;
force force VCM_FRMCHANGE = true;
force force VCM_HEARINGDISTANCE = 300;
force force VCM_MINECHANCE = 0;
force force Vcm_PlayerAISkills = true;
force force VCM_RAGDOLL = false;
force force VCM_RAGDOLLCHC = 50;
force force VCM_SIDEENABLED = [GUER,EAST];
force force VCM_SKILLCHANGE = true;
force force VCM_STATICARMT = 300;
force force VCM_StealVeh = false;
force force VCM_TURRETUNLOAD = false;
force force VCM_USECBASETTINGS = true;
force force VCM_WARNDELAY = 30;
force force VCM_WARNDIST = 400;

Mine Chance ist 0 hab ich auch richtig importiert

**Comment by TBMakuro** [comment]
Die 5% von VCOM sind aber noch nicht allzu lange drin oder ? Ich weiß noch das ich mich bei einer meiner Missionen gewundert hatte wo die ganzen IED's herkamen...

Kann aber nicht beurteilen wie das in den letzten 1-2 Monaten war weil ich soweit ich mich entsinne nur 1 Mission hatte und da gezielt alle RPG / IED / Granatwerfer Truppen entfernt hatte...

**Comment by shukari** [comment]
Wir haben es auf 0% gesetzt, da es in normalen Mission zu unerwarteten ggf unfairen Vorfällen kam.
Wenn jemand in der Mission was anderes braucht bescheid geben.
@IDarky es kann sein das VCOM manchmal die Einstellungen nicht richtig liest, dann sind es die default, denke das war bei Dir der Fall.
