### ISSUE TITLE
Radio Modul - Wiedergabe abbrechen wenn synchronisiertes Objekt zerstört

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#351]
Ist es möglich den durch unser Radiomodul ( dickes Danke nochmal an shukari ! ) wiedergegebenen Sound sofort zu beenden wenn das wiedergebende Objekt ( z.B. ein Radio ) zerstört wird ?

**Comment by shukari** [comment]
Es wird derzeit per https://community.bistudio.com/wiki/playSound3D gemacht, da ist es meines Wissens nicht möglich, aber nach dem vollständigen Abspielen kann man es stoppen wenn Radio kaputt, ist das erwünscht?

Umsetzbar keit wäre möglich mit https://community.bistudio.com/wiki/createSoundSource allerdings nimmt der keine Pfade entgegen und müsste in der Config definiert werden, was ich als Problematisch und nicht GUT umsetzbar sehe.
Gleiches gilt für https://community.bistudio.com/wiki/say3D

Echt verzwickt....
