### ISSUE TITLE
EOS Zonen Fahrzeuge

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#359]
- Fahrzeuge sollen nicht mehr despawnen wenn Spieler diese Fahrzeuge übernehmen.

**Comment by mordl** [comment]
Wie genau funktioniert das überhaupt momentan? 
Ich dachte der Zeus kümmert sich um das Entfernen von Objekten/Subjekten bei Missionen? 
Vielleicht ist mein Wissensstand auch absolut nicht mehr Up-to-Date. 
(@shukari, @Er1807 , @E-for-Eron) 

Falls wir also eine gescriptete Mission von Culli zum Beispiel haben (sprich ohne Zeus), wäre eine Funktion zum einfachen Ein-/Ausschalten der Despawnfunktion besser.
