### ISSUE TITLE
TBMod Building Tarnnetz kann nicht gebaut werden

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#363]
Tarnnetz kann nicht gebaut werden

**Comment by shukari** [comment]
Garnicht gebaut, erscheint nicht oder geht sofort kaputt?

**Comment by IDarky** [comment]
Garnicht gebaut

**Comment by shukari** [comment]
Lokal/LokalMP/DS Test abgeschlossen. Nicht nachstellbar! Sollte noch bestehen mit REPO wieder öffnen!
