### ISSUE TITLE
Fehlermeldung beim Start von 3CB-BAF MOD

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#366]
Teststart wurde mit @CBA_A3; @3CBEquipment; @3CBUnits; @3CBVehicles; @3CBWeapons.
Weitere Teststarts wurden zusätzlich mit @ace und @TBMod gemacht.
Fehlermeldung:
https://drive.google.com/open?id=1-7v8SQ3kL4JifKOo1emlHZquxyEzLREJ

**Comment by shukari** [comment]
Rhs wird benötigt also @rhsusaf da ein paar Helis benutzt werden

**Comment by Culli-TB** [comment]
Merkwürdig! Bei Staem wird überhaupt keine Abhängigkeit verlangt. Oder hab ich da was übersehen :(

**Comment by shukari** [comment]
Nein, wir haben die Reskins und Logistik Sachen aktiviert... jetzt hätte ich einen @3cb_rhs Mod machen können den wir immer aktivieren wenn wir das zusammen nutzen oder ich dachte wir nutzen soweiso immer rhs irgendwie

**Comment by Culli-TB** [comment]
Alles klar!
