### ISSUE TITLE
Brainstorming für Infovideo

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#367]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 
Was sind alles kleine nützliche Dinge, die ich in ein allgemeines Informationsvideo packen soll? Ob Zeus, ne spezielle Rolle oder allgemeines Verhalten; vollkommen egal, Hauptsache für TB sinnvoll! 
Ist euch in den Missionen falsches situatives Verhalten aufgefallen oder musstet ihr tausendmal dieselben Sachen erklären? Rein in die Liste!
Es kommen zwar noch Ausbildungsvideos, aber die werden wie im Rahmen für den Sani spezialisiert gehalten und sind auch nur für ganz wenige Rollen, aktuell TF/UAV/Pilot/Sprengmeister. (hier nehme ich auch gerne Infos)
Jeder darf die Liste erweitern.

- bei Ausfall in eigenem Trupp per Medical Assistant Status überprüfen
- Leuchtspur funktioniert in beide Richtungen und soll nicht nur cool sein
- vor Schuss mit AT Rückstrahlzone überprüfen
- Abstand zu anderen so groß wie möglich halten, ohne Kommunikation abbrechen zu lassen
- Rundumsicherung beachten
- Minen sind immer möglich
- bei Fahrzeugen wird "letzter Mann" bestimmt
- rettet nicht blind gefallene Personen
- Rauchgranaten sind Pflicht + mind eine Farbrauchgranate
- Status Rot bedeutet, dass man nicht mehr ein Gefecht wirken kann (ein Magazin/kaum SanMat/eigene Gesundheit kritisch)
- Status Gelb bedeutet, dass man nicht mehr voll einsatzfähig ist (Mun für 1-3 Gefechte/SanMat benötigt/kampffähig, aber Versorgung mittelfristig notwendig)
- macht Kovois nicht kompliziert; Sicherheitsabstand und so schnell wie das Fahrzeug vor einem, abgesehen von Vor-/Nachhut
- wie sichert man ein Haus

Edit:
- Ersatzreifen/ketten (wann haben wir jemals alle Fahrzeuge heil zurückführen können?)
- Türen langsam öffnen (STRG+Leertaste+Mausrad)
- Unterdrückungsfeuer ist Sperrfeuer und damit auch ohne sichtbaren Feind einzusetzen
- denkt mit beim Ausrüsten: Uhrzeit = NV; Kabelbinder etc = kein Gewicht, also immer mitnehmen, Camouflage+Tracer = Slotliste, Breaching Charge = Briefing, Rucksack/Beschränkungen = Briefing , noch Fragen?!
- Windrichtung vor Rauchwurf prüfen
- Tastenkombinationen (Strider Q/E)
- Loadout abspeichern/Loadouts anfertigen
- GPS Kamera für Besatzungen nutzen
- Granatenwurf melden
- Meldung Abzählen 4 fehlt, 4 meldet sich zum Schluss
- "DUKE" nur für Funk-IEDs, nicht Gewichtsplatten
- nicht jede IED/Sprengladungen/UXO ist entschärfbar; sichere Sprengung hat zu erfolgen
- Laser auf Wanne von Fahrzeugen
- SHIFT für schnellen Fahrmodus

**Comment by Er1807** [comment]
Leuchtspur funktioniert in beide Richtungen und soll nicht nur cool sein.
Das kommt aber stark auf den Zeus an. Ki sollte darauf eigentlich nicht reagieren oder?

**Comment by shukari** [comment]
@Er1807 zur Leuchtspur kann ich nur sagen, das es eine Einstellung in der Ammo ist (tracerEvery) die man nicht rauskriegt ob gerade Tracer rumfliegt oder nicht, also denke ich die KI hat keinen Plan... anderes als bei IR Laser durch VCOM ^^

**Comment by E-for-Eron** [comment]
> Leuchtspur funktioniert in beide Richtungen und soll nicht nur cool sein.
> Das kommt aber stark auf den Zeus an. Ki sollte darauf eigentlich nicht reagieren oder?

Jup, denke ebenso, dass in einer geskripteten Mission es keine Rolle spielt; sobald aber ein Zeus führt, normalerweise die Hölle dann ausbricht bzw auch Mitspieler sich darin gestört fühlen wenn mal wieder ein Einzelner vergessen hat Tracer Zuhause zu lassen ;)

**Comment by Culli-TB** [comment]
Was ist eine Linie
Was ist eine Reihe
Was ist eine Schützenreihe
Was ist ein Keil
Was ist überschlagenes Vorgehen (Wann sollte man es nutzen)
Was ist Raubenartiges Vorgehen (Wann sollte man es nutzen)
Was ist beim überqueren von offenen Flächen zu beachten (Rauch bzw. Rauchtunnel werfen)
Was muss ich im Urbanen Gelände beachten
Was muss ich beim vorgehen im dichten Wald beachten
Was ist langsames gehen
Was ist normales gehen
Was ist "Kampfmodus" mit und ohne erhöhte Waffe (2xC)
Wie verhält sich ein gutes Buddyteam
Was sollte ich beim Funken grob beachten
Wie erstelle ich einen Zusatzkanal
Wie kann ich effektiv den Entfernungsmesser benutzen
Wie markiere ich per Laser ein Ziel
Wie erstelle ich einen Laser Code

**Comment by shukari** [comment]
Wow @Culli-TB

**Comment by Nikuga-git** [comment]
So ne Art "Waffenkunde" vlt ? Zbs. das mit dem Schalldämpfer (Mehr Präzise, Schneller Heiß und dann unpräzise)
Unterschiede der Munitionsarten (M885, Mk 262, Etc)
Allgemeines Waffenverhalten (Jams, Laserdisziplin,...)


Und das ist ne seperate Sache ;)

Feinderkennung (Fahrzeuge, Waffen, usw.)

**Comment by Culli-TB** [comment]
@shukari 
Ich nutze es häufiger mit den Rucksäcken. Wie du schon gesagt hast ist das ja auf meinem Mist gewachsen :D Ich finde es gut wenn man mit seiner Munition haushalten muss. Da macht der Muniträger auch viel mehr Sinn.

**Comment by shukari** [comment]
@Culli-TB Ich persönlich mag nur nicht jedes Mal andere Sachen da... mal muit LR mal ohne... mal das mal dies... deswegen die Frage, soll ich das Was Skripten wenn ja brauche ich von Dir und Eron mal die "Standard" etwa Einstellung... das ich das machen kann.

**Comment by TBMakuro** [comment]
# Der Zeus nimmt die Spieler nicht immer an die Hand. z.B. ist es sehr unwahrscheinlich das alle Türen immer aufgeschlossen sind, auch ohne das Zeus das extra ansagt.

**Comment by Er1807** [comment]
@E-for-Eron ich schließe das jetzt erstmal. Wenn noch was reinmuss kannst du es wieder öffnen
