### ISSUE TITLE
EOS Bastion Erweiterung

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#368]
Ich werde mal versuchen meine Idee (Wunsch) bzw. Verbesserung hier zu erklären. Bei unverständnis erkläre ich es noch einmal im Ts.
Im moment ist es so das wir zwei Einstellungen haben was die Ki betrifft wenn wir die Bastion-Zone verlassen.
- die Ki die gerade Angreift despawnt (false) oder
- sie wird in die Zone gebeamt (true)

**Kommen wir nun zu Culli's Wunsch** :D
Ich werde versuchen es an Hand eines Beispiel's zu erklären.
Angenommen die Zone hat 5 Wellen die Angreifen sollen. Wir, der Menschliche Gegner hat nun schon drei Wellen abgewehrt und möchte weiter vorrücken und zwar genau in die Richtung aus der die Wellen kommen. Genau in diesem Moment ist die vierte Welle gespawnt und vereinzelt sind auch noch Gegner von der dritten Welle auf Angriff unterwegs.
- Mein Wunsch wäre es jetzt das der Rest der dritten Welle und die neue Welle ihren Angriff zu Ende führen aber die fünfte Welle _(... also jede Welle die danach käme sobald wir die Zone verlassen haben)_ nicht mehr aktiviert bzw gespawnt wird.

Ich hoffe das war soweit verständlich!?
_Hochachtungsvoll, mit gesenktem Haupt und voller Respekt vor den Skriptern,
niederkniend und erfürchtig von der Arbeit die ihr euch macht_
Euer Culli ;)

**Comment by Culli-TB** [comment]
**EOS Bastion - Wunschliste 2:**
Angriffsart und Geschwindigkeit für Ki _(Sicher, Wachsam, Kampf etc. / Langsam, Normal, Schnell)_
Nachtsichtgeräte an / aus falls die Ki welche besitzen sollte.
Tachenlampe oder Laser an / aus  für Ki.

**Comment by shukari** [comment]
@Culli-TB 
Wollte gerade für die WoMi die Anpassungen an der BastionZone machen, aber es gibt schon, versteckte Parameter damit die Bastionzone dauerhaft anbleibt. Anscheind brauchte ich das mal und habe es für mich eingefügt, auch mit dem TODO das mal als Setting zu machen ^^

In die init.sqf der WoMi einfach schreiben: `TB_dauerZone = true;`
Standard ist false... dann ist es wie immer, ist es auf true bleibt die Zone immer an bis sie bereinigt wurde.

Noch eine versteckte EInstellung ist TB_waterMode, Standard ist 1
0 - kann nicht im Wasser sein
1 - kann im oder ausßerhalb vom Wasser sein
2 - MUSS im wasser sein...
ACHTUNG.... beide Parameter gelten derzeit für ALLE Zonen ^^

**Comment by Er1807** [comment]
:D

shukari <notifications@github.com> schrieb am Di., 3. Dez. 2019, 13:00:

**Comment by Culli-TB** [comment]
Ok, mach ich.

**Comment by shukari** [comment]
@Culli-TB Das ist glaube ich nicht wichtig für dich jetzt... auser du willst Wasser komplett weg machen.
Sonst wie beim anderen in die init zB: `TB_waterMode = 0;`
