### ISSUE TITLE
T-140(K) und T-100 (Vanilla) in RUS Tarnung

### ISSUE THREAD

**Issue by Nikuga-git** [TacticalBaconDevs/TBMod#369]
Nachdem ich mit Eron über die Benutzung des Bradley und wieso diese durch Vanilla Fahrzeuge ersetzt werden, geredet habe, ist mir aufgefallen, dass es kaum russische Modelle gibt, in denen man länger als eine Stunde drinne sitzen kann.

Nun wollte ich fragen, ob es möglich ist den russischen Panzern (Vanilla) einen oliven/camo Skin zu verpassen.

Referenzbild für Camo :![149125_0](https://user-images.githubusercontent.com/57141367/67773812-9bd6ed80-fa5c-11e9-93d1-89395c238a42.jpg)

Sehr Niedrige Priorität, da nur QOL

**Comment by E-for-Eron** [comment]
Für den T-100 hatte ich in der Vergangenheit bereits einen gemacht. Ich lade ihn jetzt bei der Nachfrage hoch. Beim T-14 würde ich tatsächlich erstmal abwarten wie sich das RHS Modell entwickelt- ob es brauchbar ist.
Ich überprüfe zudem die Panzerung etc und setze sie auf vergleichbare Werte wie den MerkavaIV.

**Comment by Nikuga-git** [comment]
Vielen Dank. 
T-100 sollte auch erstmal reichen.

Ja von dem T-14 hatte ich erstmal Abstand genommen, wegen dem übertriebenen Hardkill-System..
Hoffe, dass die das hinbekommen

**Comment by shukari** [comment]
@E-for-Eron ist der Issue mit dem merge con #378 fertig? Dann closen!
