### ISSUE TITLE
fnc_Arsenal... Recompile problem

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#370]
keyword: ACE_PREP

**Comment by shukari** [comment]
ACE_PREP kann es nicht sein.
Frage: Hast du nach dem recompilen die Rolle NEU am Arsenal ausgewählt, damit er das neue Arsenal geladen hat?

**Comment by shukari** [comment]
> Frage: Hast du nach dem recompilen die Rolle NEU am Arsenal ausgewählt, damit er das neue Arsenal geladen hat?

@IDarky

**Comment by IDarky** [comment]
Eigentlich ja hab die Rollen gewechselt. Sobald das Arsenal einmal "geöffnet" wird funktioniert der Recompile nicht mehr (also keine Änderungen zu sehen)
