### ISSUE TITLE
Modul mit Radius in welchem X% der Gebäude dann abgeschlossen sind

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#371]
Kann sein das ich mich einfach dämlich anstelle, aber wenn ich mit dem "Geländeobjekt editieren" Modul, Gebäude abschließe, sind diese in der Mission dann trotzdem alle offen...

Ein solches Modul würde es zudem bequemer machen.

**Comment by shukari** [comment]
https://github.com/ArmaAchilles/Achilles/blob/148d868cb391a099f6c79a7e2cb091b78c3f3df0/%40AresModAchillesExpansion/addons/modules_f_achilles/Buildings/functions/fn_LockDoors.sqf#L75-L132
