### ISSUE TITLE
Editor previews

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#373]
https://community.bistudio.com/wiki/Eden_Editor:_Configuring_Asset_Previews
https://community.bistudio.com/wiki/BIS_fnc_exportEditorPreviews

example from ace: [nil,"all",[],[],[],["ace_medicalSupplyCrate"]] spawn BIS_fnc_exportEditorPreviews;
undocumented last param ?!?

**Comment by Er1807** [comment]
[nil,"all",[],[],["TBMod_skins"]] spawn BIS_fnc_exportEditorPreviews;
