### ISSUE TITLE
Script für Kriegsimmersion (Zeus/Editor)

### ISSUE THREAD

**Issue by Nikuga-git** [TacticalBaconDevs/TBMod#374]
Möglich/Machbar solch ein Modul in den Editor/Zeus einzufügen ?

[https://www.youtube.com/watch?v=hHFT8NNIsy8](url) - Original
[https://www.youtube.com/watch?v=8QCIix6I3sY](url) - Update dazu

Mit Einstellung wie zbs. Häufigkeit, Farbe der Tracer, Lautstärke und bestimmte Teile (wie zbs. die FLAK) auszuschalten ?

**Comment by Er1807** [comment]
Wend dich mal an Culli. Hab die Scripte für ihn aufbereitet. Ein Modul dafür finde ich nicht so gut, da man das Script in Sekunden zu einer Mission hinzufügen. Zu dem sollten diese Module sparsam eingesetzt werden (FPS/CPS)

**Comment by shukari** [comment]
BTW ist ein Modul in Zeus welches unsichtbare Leute erzeugt die Tracer in die Luft ballern...

**Comment by Nikuga-git** [comment]
Ja war ja nur als Vereinfachung gedacht...
Ambient Sounds zu loopen und halt das das nen bisschen random ist

**Comment by TBMakuro** [comment]
Ich nutze dafür immer "Effekt spawnen". Da gibts die möglichkeit tracer feuer zu setzen. Sind im Endeffekt unsichtbare einheiten die in die luft schießen. Und es lässt sich dann auch löschen wenn die Spieler den punkt passieren.

**Comment by shukari** [comment]
@TBMakuro das meinte ich in https://github.com/TacticalBaconDevs/TBMod/issues/374#issuecomment-548088546
