### ISSUE TITLE
ZeusMod Wechsel

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#380]
- [x] https://zen-mod.github.io/ZEN/#/frameworks/dynamic_dialog?id=creating-a-dialog
- [x] Ares_fnc_showChooseDialog durch https://github.com/zen-mod/ZEN/blob/master/addons/dialog/functions/fnc_create.sqf ersetzen
- [x] Ares aus requAddons nehmen und ZEN rein

---

@TacticalBaconDevs/developer & @TacticalBaconDevs/helper 
Bitte überprüfen, ob der Mod ZEN (https://github.com/zen-mod/ZEN - https://steamcommunity.com/sharedfiles/filedetails/?id=1779063631) soviel kann wie Achilles (nutzen wir derzeit - https://github.com/ArmaAchilles/Achilles)

Grund: Bei Archilles ist die Entwicklung eingeschlafen

**Comment by IDarky** [comment]
Jo schaue mir das heute Mal an

**Comment by IDarky** [comment]
Zusätzliche Mods beim testen: CBA

Besitzt keinerlei Module für Eden oder Zeus (abgesehen von Leuchtstäben und Rauchgranaten)
Folgende Module würden Fehlen:

![image](https://user-images.githubusercontent.com/42013222/68592830-43f4a980-0494-11ea-8b64-286235566d12.png)
![image](https://user-images.githubusercontent.com/42013222/68592835-4951f400-0494-11ea-9648-2c0931743b7f.png)
![image](https://user-images.githubusercontent.com/42013222/68592841-4e16a800-0494-11ea-8f30-b12063f5b702.png)

**Comment by IDarky** [comment]
Warte irgendwas mach ich falsch.... wo sind die Beworbenen Module .... Hat doch nur ne CBA Abhännigkeit

**Comment by Er1807** [comment]
Schau es mir an. @Darky Was meinst du mit die Module fehlen? Ist das Bild
Mit Aris/Archilles?

IDarky <notifications@github.com> schrieb am Mo., 11. Nov. 2019, 15:06:

**Comment by IDarky** [comment]
Also ich hab einmal mit ZEN gestartet und einmal nur mit Achilles.
Aber anscheinend muss man zusätzlich mit ACE starten das es funktioniert @Er1807

**Comment by shukari** [comment]
1. Beides nicht zeitgleich starten (sind zwei ZEUS Mods und überschreiben jeweils die gleichen Sachen natürlich)
2. hast du deinem ZeusObj alle Module plus inoffizelle aktiviert?

**Comment by IDarky** [comment]
zu 1. @shukari  hab nicht mit beiden getartet 
zu 2 prüf ich gerade

**Comment by IDarky** [comment]
> hast du deinem ZeusObj alle Module plus inoffizelle aktiviert?

Daran lags ^^

**Comment by IDarky** [comment]
Vorteile von ZEN

-  Besses Objekte hinzufügen:
![image](https://user-images.githubusercontent.com/42013222/68594388-b6b35400-0497-11ea-8888-2e760ddc24e9.png)
- Nachträglicher Intel 
![image](https://user-images.githubusercontent.com/42013222/68594567-1f023580-0498-11ea-9583-653cd94f1fa4.png)
-  EXEC Code Feld @shukari
![image](https://user-images.githubusercontent.com/42013222/68595909-a5b81200-049a-11ea-99f1-8d81c27c4dd9.png)
ist das besser?
- Attach Object deutlich verständlicher 
![image](https://user-images.githubusercontent.com/42013222/68594887-c7b09500-0498-11ea-9517-bdeb80fd6fa4.png)

**Comment by IDarky** [comment]
Kann eigentlich alles was Achilles kann bis auf nicht nennenswerte Kleinigkeiten wie Atombombe

**Comment by shukari** [comment]
@IDarky zum exec Feld sage ich -> ZEN_disableCodeExecution 😈

**Comment by IDarky** [comment]
@shukari  was bedeutet denn die Kontext Hilfe bei dem exec Feld ?

**Comment by Er1807** [comment]
Hab ZEN jetzt etwas getestet. Finde es auch gut. Wir müssten dann wahrscheinlich ein paar von unseren Dialogen umstellen

**Comment by shukari** [comment]
Aufgaben added
