### ISSUE TITLE
Persistence review

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#381]
@Er1807 @shukari 
Persistence reviewn mit Blick auf:
https://steamcommunity.com/sharedfiles/filedetails/?id=1903981111

ggf bessere Mechaniken oder Methoden!

**Comment by Er1807** [comment]
https://imgur.com/a/GpprGYF

**Comment by Er1807** [comment]
1. So wie ich sehe speichert er noch Skripte. Finde ich eher blöd
2. Hat bei mir sehr lange gedauert. Bei einer Dummy Mission mit paar Einheiten. Da wäre im Fall von einem Server Crash der Server schon weg. Viele andere Features scheinen darauf zu basieren das der Server erreichbar ist.
