### ISSUE TITLE
TBMod_rhs nicht in repo?

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#382]
![image](https://user-images.githubusercontent.com/42013222/68602191-334d2f00-04a6-11ea-910b-fbe024f9feb3.png)

Gibts einen Grund wieso in der Repo TBMod_rhs nicht mehr vorhanden ist?
@shukari @Er1807

**Comment by IDarky** [comment]
nvm habs in rhsusaf gefunden aber wieso liegt das dort ^^

**Comment by Er1807** [comment]
Weil es zu RHS gehört und bicht ohne RHS gestartet werden kann

IDarky <notifications@github.com> schrieb am Mo., 11. Nov. 2019, 17:18:
