### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#385]
Persistence scheint daten wieder nicht zu übertrage. Auf Trainserver

**Comment by Er1807** [comment]
@shukari weinst du ob man Dependencies in DLLs packen damit man eine DLL hat?

**Comment by shukari** [comment]
jap... ich kenne es über resourcen mit geben und dann laden.
https://social.msdn.microsoft.com/Forums/de-DE/db60ca11-42c9-4dbf-b736-48809942170c/dll-in-dll-einbinden?forum=visualcsharpde

**Comment by shukari** [comment]
Ist die Mission mit der Patro nicht gespeichert?

**Comment by Er1807** [comment]
Es sollten die selbst gebauten Objeckte auf dem Server noch gespeicht sein.
Player Positions/Fahrzeuge etc fehlen

shukari <notifications@github.com> schrieb am Mi., 20. Nov. 2019, 10:10:
