### ISSUE TITLE
fastRope Routine

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#388]
HeliAceAktion welche alle Leute automatisch abseilt... ggf verbessert das die Benutzbarkeit des Features

- [x] ggf abseilende capitative machen bis unten
- [x] https://github.com/acemod/ACE3/blob/master/addons/fastroping/functions/fnc_canFastRope.sqf
- [x] https://github.com/acemod/ACE3/blob/master/addons/fastroping/functions/fnc_fastRope.sqf
- [x] ggf auch noch den start automatisch
    - [x] schauen ob Höhe ok
    - [x] schauen ob Seil unten
    - [x] Piloten starten lassen
    - [x] Fries usw ausführen lassen orientieren an https://github.com/zen-mod/ZEN/blob/master/addons/ai/functions/fnc_waypointFastrope.sqf
- [x] opt-out dafür machen (https://github.com/TacticalBaconDevs/TBMod/issues/388#issuecomment-559987463)

**Comment by Er1807** [comment]
Dazu:  Aktives Bereitmachen zum Fastrope damit GF auch mal sitzen bleiben dran
