### ISSUE TITLE
Shukari-Mörser Anzeige

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#391]
Anzeige für aktuelle Entfernung auf der Waffe wird nicht angezeigt- stattdessen nur ein weißes leeres Feld.

**Comment by shukari** [comment]
Pfade im 3d Model müssen angepasst werden...
https://github.com/TacticalBaconDevs/TBMod/blob/master/addons/vz99/data/vz99_vehicle.p3d

**Comment by TBMakuro** [comment]
Ich möchte ja jetzt nicht als Miesepeter dastehn, aber macht der Mörser überhaupt noch großartig Sinn ?

Ich möchte behaupten das wir damit in 3 von 4 Fällen entweder zu langsam sind und die Feinde schon anderweitig bekämpft wurden, oder daneben schießen oder aber die anderen Teiltruppen arg ausgebremst werden bis der Mörser einsatzbereit ist.

( Ich habe es speziell in einer meiner Missionen mal gesehen das sogar alle 3 Fälle zeitgleich eingetreten sind... glaub das war bei OP - Hawkeye ...

Von unseren letzten Missionen denke ich persönlich das eine über den Zeus angeforderte und ausgeführte Feuerunterstützung sinniger ist als den Mörser mit zu tragen.

**Comment by shukari** [comment]
Alles Fälle wo wegen Unerfahrenheit das zutraf. Weil ich ihn nicht einsetzen darf und wir ständig limitierte Rucksäcke haben kann ich auch nicht die Leute daran optimieren... In 2 von 3 Missions in denen ich oder jemand anders ihn in meinem Trupp nutze, wären die Ergebnisse super... So gut das wir ihn ja jetzt nicht mehr nutzen dürfen...

**Comment by Culli-TB** [comment]
Ich bin für das Mörserteam. Sollten wir beibehalten.

shukari <notifications@github.com> schrieb am So., 1. Dez. 2019, 16:33:

**Comment by Er1807** [comment]
@shukari kann das geschlossen werden, Bug ist doch behoben oder?

**Comment by shukari** [comment]
mit #399 resolved
