### ISSUE TITLE
EOS Zone [Eric Wunsch]

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#396]
Aktivierungs/Deaktivierungs Variable / Cond einführen um in einer Mission eine Eos Zone zu deaktivieren.

**Comment by shukari** [comment]
Müssen sowieso das Ding wegen #368 komplett mal umschreiben

**Comment by mordl** [comment]
Ist das hier das gleiche Thema wie bei #359?
Sollten es dann zusammen nehmen.
