### ISSUE TITLE
Poppy Script für TB

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#402]
https://github.com/BaerMitUmlaut/Poppy/

**Comment by shukari** [comment]
Was genau davon möchtest du nutzen?

**Comment by Er1807** [comment]
Einheiten (Eos) damit einkleiden
Meine Ideen:
- neue Einheiten erstellen speziel für Poppy.
- Poppy so anpassen das es nicht Spielern automatisch was anzieht.
