### ISSUE TITLE
#DefaultSettings

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#425]

**Comment by shukari** [comment]
Ähm noch ein paar Infos?   ^^

**Comment by Er1807** [comment]
Befehl um Die Defaultsettings zu laden

**Comment by IDarky** [comment]
falls kein Genstab da ist das man als Offizierstab oder eric die default settings laden können

**Comment by shukari** [comment]
oh shit stimmt super idee!!!

**Comment by Er1807** [comment]
> falls kein Genstab da ist das man als Offizierstab oder eric die default settings laden können
Eigentlich nur Darky. Kann mir ja noch abhelfen.
