### ISSUE TITLE
#Settings Blue Force Tracking

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#432]
Eventhandler / geht nicht mehr an durch #settings

**Comment by Er1807** [comment]
Hast du die Mission neugestartet?

IDarky <notifications@github.com> schrieb am So., 9. Feb. 2020, 00:24:

**Comment by IDarky** [comment]
Bereits mit shukari abgesprochen

**Comment by shukari** [comment]
Wollte Ace PR machen. Zudem saveProfileNamesace fehlt nich

**Comment by shukari** [comment]
ACE3 PR: https://github.com/acemod/ACE3/pull/7519

**Comment by shukari** [comment]
in der nächsten ace3 version
