### ISSUE TITLE
Permanenter Rauch im Edern Editor

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#433]
Modul wie von Ares. Synchronisation mit Trigger?

**Comment by shukari** [comment]
https://github.com/ArmaAchilles/Achilles/tree/master/@AresModAchillesExpansion/addons/modules_f_achilles/Effects

**Comment by shukari** [comment]
Gibts für Zeus schon... ggf einfach scope auf 2?
https://github.com/zen-mod/ZEN/blob/547aea5a94c4c34d5777c1b834625d7bdcecfe77/addons/modules/CfgVehicles.hpp#L334

**Comment by Er1807** [comment]
fnc_moduleSmokePillar nutzt nen Dialog. Sollte ohne Änderungen nicht möglich sein

**Comment by Er1807** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1019445089319566454/2B386EA123756D200FBD88F59316B4F53040C797/
