### ISSUE TITLE
ZEN etwas als IED setzen

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#440]
Es gibt ein Modul wo man ein belibiges Objekt als IED setzen kann
folgende Probleme ergeben sich:

- Minimale Aktivierungsdistanz sind 5 Meter
- Werden nicht vom Ace Minensucher erkannt

Vll kann sich jemand daran setzen und es fixen?

**Comment by shukari** [comment]
Dieses Modul ist einfach Müll... es gibt außer du hast ein Störer Fahrzeug gesetzt keine Gegenmaßnahmen. Man kann es mit ACE3 nicht entschärfen.

Setzt einfach ACE3 IEDs... fertig und nutzt dieses nicht counterbares blöde Modul nicht!
