### ISSUE TITLE
TFAR Schreien automatisch nach 10 sek zurücksetzen

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#443]
TFAR Schreien automatisch nach 10 sek auf Normal zurücksetzen. Für die Leute die es vergessen zurückzuwechseln. Da nicht jeder den Schreien Hotkey benutzt

**Comment by E-for-Eron** [comment]
Das kann dafür sorgen, dass die Problempersonen nie wieder den Modus manuell wechseln werden.
Also einerseits sind 10sek zu lang für die "Störenfriede", um wieder leise gestellt zu werden. Auf der anderen Seite sind 10sek zu kurz für mich als GF, weil ich Wert darauf lege, nicht immer zu funken.

**Comment by TBMakuro** [comment]
Bin mir zwar nicht sicher ob das hier unbedingt passt aber:

Ich hatte in den letzten Wochen vermehrt das Problem das ich zwar auf "flüstern" war, einige Spieler mich aber trotzdem gehört haben als würde ich schreien...
Das scheint sich aber tatsächlich auf mich zu beschränken, weil es mir bei noch niemand anderem aufgefallen ist.

Kann das an meinem momentan schlechtem Internet liegen oder kommt da auch TFAR als Quelle in Frage ?
