### ISSUE TITLE
Arsenal ohne Munition und neue Nachschubkisten - Wunsch Makuro

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#447]
Unser normales US Arsenal nur eben ohne Munition und ein paar Nachschubkisten die etwas "spezialisierter" sind als unsere vorhandenen.

z.B. Sturmgewehr und MG Munition in seperaten Kisten.

Ich habe es soweit ich mich getraut hab schonmal selbst versucht, um euch den Aufwand etwas zu erleichtern, hab aber keinen Plan wie ich da jetzt weitermachen muss.

[Link](https://drive.google.com/open?id=1qTCGy7Y_fkrDAqdsJGyDNANiMfW9ewyC)

Die Dateien basieren auf CfgVehicles_Usa.hpp (TB Nachschub ) & fnc_arsenalUSA.sqf ( TB Arsenal ).

**Comment by shukari** [comment]
Wofür? Temporär?

Kannst du das etwas erklären. Sehe derzeit den Langzeitnutzen nicht, es in den Mod aufzunehmen, Außnahme wären spezielle Nachschubskisten.

**Comment by TBMakuro** [comment]
Gerne auch temporär, oder sogar als "Zweigmod" ( kp wie ich das ausdrücken soll ). 

Die Kisten hätte ich gerne für die Hardcore ( Sontags ) Missionen.
Das Arsenal bräuchte ich für den Umbau der "Liberation" Mission, weil ich die ja seit 2 Wochen zu gunsten einer möglichen Wochenmission am umbauen bin. Da habe ich nur gerade das Problem das die Spieler dauerhaft Resourcen generieren, aber bis auf Fahrzeuge nicht ausgeben. Ich hoffe ich kann das so ausgleichen wenn die Munition gekauft werden muss.

**Comment by TBMakuro** [comment]
Alternativ:

Besteht für mich die Möglichkeit Nachschubkisten und den Inhalt unseres Custom-Arsenals in meinen Szenario Daten zu spezifizieren ? Das würde euch den Aufwand ersparen. Wenns das technisch möglich ist bräuchte ich nur eine Erklärung. 

( Weil wir von mit reden bitte in doppelter Ausführung sonst kapier ichs eh nich :P )

**Comment by Er1807** [comment]
Scheint nach kurz mit dem Ace Arsenal experementiren nicht möglich zu sein.
Munition wird anderes gehandhabt als Items. Wenn Items nich in der Allowed Items sind können sie nur entfernt werdern. Dies gilt nicht für munition
