### ISSUE TITLE
Neuer AI Mod

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#454]
Hab ich heute gefunden aber noch nicht getestet. Hat jemand Erfahrungen damit?
https://github.com/nk3nny/LambsDanger

**Comment by shukari** [comment]
@E-for-Eron wollte es testen
Letzter teste war bei Culli Mission auf der Wasserbasisinsel wo alle AI durch die Wände lief, wenn du dich erinnerst ^^

**Comment by E-for-Eron** [comment]
Fühlt sich nicht gut an. Würde ich von abraten. Habe es vor 2 Wochen getestet.
