### ISSUE TITLE
UK Arsenal Fixes

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#464]
- [x]  Grendier keine Schneeweste
- [x] Ein Visier (LDS) [eins ist im Klassennamen PIP, bitte PictureInPictureVisiere vermeiden!!!] ist doppelt (TiiMeToPlay)
- [x] Batterien für TF
- [x] Visier für großes MG (gibt es nicht)
- [x] Muniträger braucht Möser / MörserMuni (hat er bereits)
- [x] überprüfen wer im USA Arsenal Zugriff auf Laser/Entfernungsmesser hat unf angleichen (haben da geändert gehabt wer was haben sollte)
- [x] normale Visiere (ohne 3 Visiermodi), also ein normales ACOG (2-4x) ohne Holo, generell mehr Visiere wäre cool (wenn möglich)

**Comment by shukari** [comment]
@IDarky liste formatiert und erweitert, warte dann auf deinen PR 😄
