### ISSUE TITLE
LDF Anpassungen

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#476]
- [x] AT braucht noch stärkere AT Version (oder @E-for-Eron bufft den LDV alamut)
- [x] Mehr Rucksack Auswahl? (nicht benötigt)
- [x] Rauchgranten Fehlen
- [x] Default Layouts (zu selten benutzt)
- [x] AT hatte Laserdesignator (unbekannt wieso er ihn hatte)
- [x] UAV Terminal auf Pio und UAV beschränken
- [x] Gesichtsbedeckungen
- [x] Sani hatte LR
- [x] MG kein Schalldämpfer

**Comment by Nikuga-git** [comment]
Dem Waffenspez "besonders" machen. Wie zbs. Zugriff auf die Mk14 oder ähnliches

**Comment by Nikuga-git** [comment]
Allgemein andere Granaten haben gefehlt, nicht nur Rauch. Ebenso Rauchgranaten für den Gren (Unterlauf)

**Comment by shukari** [comment]
> Dem Waffenspez "besonders" machen. Wie zbs. Zugriff auf die Mk14 oder ähnliches

nur zur Info @Nikuga-git ich glaube die MK.14 ist von RHS und die Sachen dürfen nicht in LDF (vanilla) verwendet werden

**Comment by Nikuga-git** [comment]
Achso ne, ich meinte die Vanilla Mk14. Müsste den namen "srifle_DMR_06_hunter_F" tragen. Gibt es auch in Olive oder Tarnfarben, diese sind jedoch vom Marksmen DLC.

Somit ist die normale (braune) Hunter Version der Mk14 im Contact DLC mitinbegriffen.

**Comment by IDarky** [comment]
@Nikuga-git der Waffenspez hat was speziales.

Eine unterlauf Shotgun
