### ISSUE TITLE
Spectrum bugs

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#482]
- [x] in Bewegung gefrezzt (STRG+D) switchMove geben?
- [x] transmitter können mehere sein ARRAY
- [ ] sprengmittel die Funk haben sehen
    - [ ] telephone sehen wenn jemand eins mitführt?!?!

**Comment by IDarky** [comment]
Klingt  cool

**Comment by TBMakuro** [comment]
#511

**Comment by mordl** [comment]
Bestehen die Probleme noch?
