### ISSUE TITLE
Recoil-Visiere

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#485]
Es gab eine Anfrage, ob wir Interesse daran haben, den Recoil ähnlich niedrig zu setzen wie bei der Prea. Garde und dafür die Visiere mit Zoom stärker einschränken. 
DMR würden damit ab bereits 400m sehr sinnvoll werden und ein Problem bei uns lösen, da wir aktuell nach 100m Sprint nicht mehr in der Lage sind ein Feuergefecht zu führen.

**Comment by Er1807** [comment]
Ich bin persönlich dagegen. 
Sprinten sollte gefährlich sein. Wenn ich sprinte gehe ich immer ein Risiko ein das ich erschöpft bin. 
Zudem ist es bei mir ist es so das mit den leichten/ohne Visieren keine mittelweite Feinde erkennen würde.
Die Änderung hatte dann zur Folge das der DMR/WS mehr zu tun hat, da unsere normalen Distanzen bei 300m sind. Die Feinde interessieren sich wenig dafür welche Visier wir haben und schießen weiter.

**Comment by shukari** [comment]
Achtung, der verwackler Faktor ist in der derzeitigen Ace Version broken.
Deswegen haben MG/Träger/AT derzeit riesen Probleme damit

**Comment by E-for-Eron** [comment]
Ich stimme ebenso zu was die Visiere angeht - ich würde sie nicht allgemein, sondern nur abhängig der Mission einschränken, und das ist und bleibt die Angelegenheit des Missionsbauer. 
Ich halte es für *manchmal* gut, dass wir nicht so weit und so genau wie die KI schießen können. Wir haben dafür fast jede Mission gepanzerte Fahrzeuge, Artillerie, Aufklärung, Helikopter o.Ä. .

Bezüglich sprinten sehe ich das für mich aber anders. Ja, während eines Sprints kann man nicht zielen, aber danach ist man in wenigen Sekunden wieder vollkommen in der Lage zu zielen. Und sobald eine Waffe aufgelegt wird, sollte die Waffe sofort ruhig sein können. Aber das hat nicht alles mit dem Rückstoß zu tun, sondern mit anderen Dingen, die wir aktuell auch nicht beeinflussen können.

**Comment by shukari** [comment]
noch offen @E-for-Eron ?
