### ISSUE TITLE
Performance Optimierungen

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#486]
- [x] spectrum deaktivierbar machen (zuviele Aktualisierungen)
- [x] tasks wenn keine da nichts machen + pefh
- [ ] CBA_fnc_addClassEventHandler/ andere Handler nicht Code sondern Functionen aufrufen
    - dann auch per recompile nutzbar
- [x] Analysen mit: https://github.com/dedmen/ArmaScriptProfiler
    - Netzwerkanalyse -> -profilerEnableNetwork

**Comment by mordl** [comment]
Sind die offenen Sachen noch aktuell, bzw. werden sie gebraucht?
