### ISSUE TITLE
YOLO

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#488]
Mein Vorschlag zum YOLO System, falls technisch möglich: Person stirbt nicht direkt, sondern ist für 2,5min am Boden mit schwarzem Bildschirm. Nach den 2,5min, in denen er noch wiederbelebt werden kann, kommt er in den Zuschauermodus für die Restzeit der angepeilten Gesamttodeszeit.

**Comment by Er1807** [comment]
Das heißt kein One Hit KO mehr. Das könnte man warscheinlich realisieren indem man den Cardic Arrest Timer auf 2.5min setzt und den direkttod abschaltet. Das mit der Restzeit ist vom Zeus abhängig. Wann er die Leute wieder reinlassen möchte.

**Comment by E-for-Eron** [comment]
Sorgt dafür, dass ein einzelner Kopfschuss nicht mehr sofort tödlich ist, aber ich möchte gerne, dass unsere Sanis Verwundete, bis auf Status Rot, theoretisch versorgen können. Und 2-3min Cardiac Arrest Timer (CAT) ist genügend niedrig, um Sanis und Führungspersonal dazu zu zwingen in Zukunft Med Fahrzeuge/Einrichtungen so schnell und effizient zu nutzen wie nur möglich.

**Comment by E-for-Eron** [comment]
@Er1807 @shukari  Wollen wir das hier genannte YOLO System morgen ausprobieren? Also kein Insta Death, aber nur 2min Cardiac Arrest, danach Zuschauermodus für X Minuten?

**Comment by E-for-Eron** [comment]
UPDATE 19.05.: Meinungen zum Yolo System "mit Verzögerung bis Zuschauermodus" überwältigend positiv. Es wurde zwei weitere Sachen angesprochen:
1. Wunsch: Statt schwarzer Bildschirm eine Kamerasicht für den sterbenden Kameraden, bevor er in den Zuschauermodus wechselt.
2. Bis auf besondere Missionen, soll mit einer festen Zeit im Zuschauermodus gearbeitet werden, dass tote Spieler sich auf Eintritt vorbereiten können, bzw auch kurz auf Toilette etc, anstatt Zwangsweise am Bildschirm hocken zu müssen, ohne das Wissen wann sie wieder vom Zeus respawned werden.

**Comment by mordl** [comment]
Bei der Hardcore Sonntagsmission wurde Yolo und krit. Schaden verwendet. Fast immer waren die Spieler sofort tot (oft Kopfschüsse, ohne Helm).

Momentan findet nur selten Yolo eine Anwendung. Für Hardcore Missionen fand ich die Einstellungen gut. Für Di. und Samstagsmissionen eher unpraktisch (die Probleme sollten bekannt sein). 

Deshalb finde ich, dass sich dieser Issue erledigt hat.
