### ISSUE TITLE
Persitence Problems

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#496]
- [x] Server/speichern ist lokal und geht nicht
    - lokal/speichern ist Server
- [x] für Marker https://community.bistudio.com/wiki/BIS_fnc_markerToString nutzen
- [ ] Objecte mit ZEN serialisieren?
    - https://github.com/zen-mod/ZEN/blob/0f1f2b715e5231aba2e37713e05fa7b5984406ec/addons/common/functions/fnc_serializeObjects.sqf
    - https://github.com/zen-mod/ZEN/blob/0f1f2b715e5231aba2e37713e05fa7b5984406ec/addons/common/functions/fnc_serializeInventory.sqf

**Comment by Er1807** [comment]
Wie ich die Nachricht verstehe fehlt irgendwo ein !

**Comment by shukari** [comment]
Mal generell drüber schauen... Lokal speichern ging dann garnicht. Das kann durch den Zen rewrite passiert sein mit den dialogen

**Comment by shukari** [comment]
immer noch kaputt
