### ISSUE TITLE
Weferlingen Arsenal Updaten für Weferlingen Teil 4

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#504]
Weferlingen Arsenal Updaten für Weferlingen Teil 4

**Comment by shukari** [comment]
@IDarky die kind/ labels sind nur für PRs interessant die kommen dann ins Changelog an die stelle ^^

**Comment by E-for-Eron** [comment]
Sieht für mich soweit in Ordnung aus. Jedoch nur Ingame überprüft worden. Keine Garantie für Scriptfehler etc.
