### ISSUE TITLE
Vorschlag: Blut mithilfe der Feldflasche wiederherstellen

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#505]
Titel sagts ja schon. z.B. könnte das trinken aus der Feldflasche über 10 min insgesammt 0.75L Blut wiederherstellen.

Feldflaschen können durch ACE schon an an Brunnen / Fässern usw. gefüllt werden und nach dem Befüllen kann 2x getrunken werden.

So können die Truppler kleine Blutdefizite selbst händeln und den Sanis geht nichtmehr ganz so schnell die Flüssigkeit aus.

**Comment by LuGoPaTB** [comment]
Von der Grundidee finde ich das super. Aber ich finde an den Werten müsste man wa ändern. Esscheint mir sehr stark 0.75 in 10 min. Das ist ca gerade mal die doppelte bis dreifache Zeit die eine normale 700ml Infusion braucht.

**Comment by E-for-Eron** [comment]
Nach meinem Erkenntnisstand haben wir in den letzten zwei Monaten kaum Situationen mit IV-Mangel gehabt, noch überdurchschnittliche Ausfallraten. Tatsächlich haben wir in den letzten Missionen mit 20-40min Downtime Bestwerte erreicht.

Truppler können ohne Sanitäter Blutdefizite selbst händeln, da jedem Kochsalzlösung zur Verfügung steht und durch den Buddy genutzt werden kann. Für kleinere Mengen bis höchstens 1l insgesamt ist das System ausgelegt und für jeden auch bezüglich Gewicht/Platz tragbar.

**Comment by Er1807** [comment]
Eine Korrektur zur Downtime. Wenn Leute sterben wird diese nach meiner
Kenntnis nicht dazu gerechnet.

E-for-Eron <notifications@github.com> schrieb am Mo., 27. Juli 2020, 22:57:

**Comment by shukari** [comment]
@E-for-Eron ein paar Leute überleben, dann aber lange... viele sterben nach 10-30sek weg. Wir müssen mal tracken warum.

**Comment by mordl** [comment]
Hat sich das Problem erledigt. Wenn ja, bitte schließen.

**Comment by shukari** [comment]
habs in meine Aufgaben aufbenommen
