### ISSUE TITLE
Änderungen beim Ausbluten

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#507]
- Zeit zum Ausbluten auf 10min erhöhen
    - es ist auf dem Server eingestellt das man 10min braucht ^^
- ~Black Screen bei Ohnmacht verbessern~ -> zwei neue Modi, feste Kamera und Spectator sind verfügbar
- ~Funk soll noch mitgehört werden können~ -> behoben durch Serversetting

**Comment by E-for-Eron** [comment]
Wieso auf 10min erhöhen? Ist es nicht besser es bei 3min einzupendeln, um einerseits den Patienten nicht zu lange am Boden zu lassen und gleichzeitig Sanis zu fordern? Tödliche Verwundungen sollten auch tödlich sein. Wenn rechtzeitig vor Ort, können Sanis/Ersthelfer mit CPR die Zeit immer wieder verlängern, aber ein vergessener Spieler sollte auch schnell sterben.

Mit dem Rest stimme ich überein.

**Comment by shukari** [comment]
Es geht eher um Punkt 2 & 3 und zu 1. gilt nur zu sagen aus unbekannten günden sterben manche direkt.

**Comment by mordl** [comment]
Ja, zudem gibt es ein paar Leute die sich an dem schnellen Tod stören. Es zerstört ihnen die Immersion, wenn sie nach 3min einfach wieder im Spawn stehen und zurück teleportieren können, als wäre nix passiert.

**Comment by E-for-Eron** [comment]
Wenn die Gruppe lieber die 10min Timer hat, ist das in Ordnung. Wenn wir das kombinieren können mit einer Top-Down-Sicht o.Ä. und die Audio nicht nur für Funk, sondern was auch um einen herum geschieht beinhaltet, fände ich das sogar ziemlich optimal.

**Comment by mordl** [comment]
Hört sich gut an. Gab es nicht sowas bei Arma mit dem Apex Update?

**Comment by TBMakuro** [comment]
> 
> 
> Ja, zudem gibt es ein paar Leute die sich an dem schnellen Tod stören. Es zerstört ihnen die Immersion, wenn sie nach 3min einfach wieder im Spawn stehen und zurück teleportieren können, als wäre nix passiert.

Andere wiederrum würden sich dran stören nach z.B. nem direktem Mörsertreffer oder ner IED 10min rumzuliegen, während die ( in dem Fall meist überforderten ) Sanis, erstmal die Fetzen zusammentragen.

Was das angeht können wirs schlicht nicht allen Recht machen.

Ich seh das wie Eron dass 3min ausreichen. Unsere fähigen Sanis bekommen die Leute meist auch wieder auf die Beine. Außerdem macht es das Sani Gameplay auch um einiges immersiver / interessanter weil bei Fehlern eben auch mal jemand den Löffel abgibt.

Die ACE bedingten 20sec. Deaths sind allerdings ein anderes Thema, aber da können wir so wie ich das verstanden hab nicht wirklich was gegen tun.

Punkt 2 & 3 wurden soweit ich das weiß schon mehrfach diskutiert und es wird da doch schon nach ner Lösung gesucht ?
