### ISSUE TITLE
Weferlingen Tweaks

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#509]
- [x] MG Lafette Tragbar machen per ACE  [fixed]
- [x] Sandsäcke und Klappspaten buggy funktionieren nicht überall [fixed]

- [ ] ~~DLC Kisten tragbar machen~~ [Aufwand überwiegt  Nutzen]
- [ ] ~~DLC Stühle sitzbar machen~~ [Aufwand überwiegt Nutzen]

**Comment by mordl** [comment]
Hat sich hier irgendwas getan? @shukari @Er1807

**Comment by shukari** [comment]
@IDarky @mordl muss wissen was genau für Hilfe benötigt wird

**Comment by IDarky** [comment]
Kernprobleme  wurden von Seiten ACE gefixt
