### ISSUE TITLE
"Soundbug" beim nutzen des TB Bausystems. 

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod#511]
Beim platzieren von Objekten ( Sandsackmauer, Salineständer usw. ) wird während die Fortschrittsanzeige durchläuft der Sound vom Spectrum Gerät abgespielt ( Scanvorgang ).

**Comment by shukari** [comment]
Immernoch? das wurde doch eigl gefixt? Wann mit welcher version?

**Comment by TBMakuro** [comment]
Ist bei mir heute ( 20.07.20 ~22:00Uhr ) beim Mission bauen aufgefallen. Aktuellste TBMod Version.
