### ISSUE TITLE
BW Nachschub verbessern

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#512]
Die Nachschubskisten von der Bundeswehr sollten überarbeitet werden.

z.B macht es keinen Sinn, dass die Werfermunitionskiste nur 2xAA und 2xAT hat. 
Da ist mehr als genug Platz und es sollte auf eine AA-Kiste und eine AT-Kiste aufgeteilt werden,
weil ein Trupp so gut wie nie AA und AT gleichzeitig im Trupp hat.

**Comment by Er1807** [comment]
Würde vlt eher das US System Nutzen wo es zusätlich nochmal Kisten für einzelne Werfer gibt, trotsdem eine allgemeine Kiste existiert für zB Missionsbauer zum vor platzieren

**Comment by IDarky** [comment]
@mordl  die AT kiste ist bereits gefixt in #510 wurde aber nicht gemerged

**Comment by mordl** [comment]
Danke @IDarky. Aber bei der Werferkiste muss noch die Munition für die One-Use hinzugefügt werden, weil sie sonst nicht funktioniert.

BWA3_RGW90_HH

**Comment by IDarky** [comment]
- [ ] Dratschneider fehlt

**Comment by E-for-Eron** [comment]
BW Arsenal ist nun komplett überarbeitet und Wünsche, Anregungen übernommen worden. Bei Fehlern oder Misständen sich diesbezüglich bei mir melden.
