### ISSUE TITLE
Changelog 1.1.2

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#52]
Alle commits durchgehen seit dem 21 Aug

**Comment by Er1807** [comment]
Fixes: 
  Funktion addZeus entfernt
  Taser AI/Spieler Unterscheidung
  createSupply Position (Man kann nun nicht mehr auf dem Flugzeugträger von Kisten erschlagen werden)
  Maincore Fix
  HC Fix
  BW Classname Änderungen im Arsenal überarbeitet

Hinzugefügt:
  Ki-Eden-Aktionen (Hinsetzen und Loopanimationen)
  Security Addon  
  Schlüssel-Ki Modul
  VIP HandleasPlayerMedical Modul
  ApplyLoadout Modul
  Safestart, hidegroup, setgroup Chatbefehl
  Extemes Sanisystem Fix
  Anti-Verwackel für bestimmte Klassen
  Minen-Kiste hinzugefügt

Geändert:
  EOS System optimiert sowie verbessert
  Recoilsystem verbessert
  Persistence System stark verbessert
  USA Standartausrüstung erneuert
  Schauspielersystem nun Eden Einstellung(wie heißt das richtig @shukari )
  Safestart Anpassung
  init.sqf Anleitung erneuert
  Blut stats Kochsalz im Nachschub
  M320 kann nun AIM Smokes verschießen
  USA Munitionkiste verändert
  Startfrequenz SW angepasst
  Munition wird Magazinweise nachgeladen
