### ISSUE TITLE
EdSubcat_TB

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#554]
Benötige Hilfe zum Verständnis, warum nur bestimmte Subcats für den Editor und nicht für den Zeus gedacht sind. Aktuell können die Fahrzeuge aus EdSubcat_TB_Spezial nicht als Zeus nachträglich gestellt werden.

**Comment by IDarky** [comment]
wenn du z.b den class TB_MH_60_Silent_Hawk meinst dann musst du  `scopeCurator = 2;` zur klasse hinzufügen

`class TB_MH_60_Silent_Hawk : B_Heli_Transport_01_F // UH-80
    {
        accuracy = 0.4; // 0.5
        displayName = "MH-60 Silent Hawk";
        editorCategory = "EdCat_TB_MainCat";
        editorSubcategory = "EdSubcat_TB_Spezial";
        ....`

**Comment by E-for-Eron** [comment]
Problemlösung weiterhin erwünscht: Fahrzeuge der der Subcat TB-Spezial können nur im Editor gestellt werden.

**Comment by Er1807** [comment]
![image](https://user-images.githubusercontent.com/20169013/98440847-782c9580-20fb-11eb-84b5-30a55e80d29a.png)
Sind die Fahrzeuge wie im Bild eingetragen?
@E-for-Eron
