### ISSUE TITLE
Neue Flaggen

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#555]
- Mit oder ohne Logo ist jetzt noch die Frage

- Es wurde darauf geachtet das die Flagge bei allen Belichtungsverhältnissen gut lesbar ist

![image](https://user-images.githubusercontent.com/42013222/98118607-c8151d80-1eab-11eb-86ac-20a865ce12c5.png)
![image](https://user-images.githubusercontent.com/42013222/98119506-f8a98700-1eac-11eb-9792-1e8eb7e8d10c.png)
![image](https://user-images.githubusercontent.com/42013222/98119556-0b23c080-1ead-11eb-8f7b-26fd4e52f829.png)

**Comment by shukari** [comment]
@E-for-Eron entscheidet

**Comment by BeLink13** [comment]
Ich finde die Flagge cool auch ohne Logo!

**Comment by E-for-Eron** [comment]
Jawohl, passt!
