### ISSUE TITLE
Bring back verschmutzte Brillen

### ISSUE THREAD

**Issue by BeLink13** [TacticalBaconDevs/TBMod#573]
Ich wäre dafür, dass die Brillen wieder dreckig werden, wenn etwas explodiert oder sie durch andere Sachen dreckig werden :)

Außerdem ist es total cool den Dreck abzustreifen 😎

**Comment by shukari** [comment]
ist doch an o.O

**Comment by BeLink13** [comment]
Oh, dann ziehe ich das gerne wieder zurück. Ich war nach dem Gespräch mit @E-for-Eron davon ausgegangen, dass es nicht an ist. Mir ist es auch nicht mehr aufgefallen die letzten Missionen

**Comment by E-for-Eron** [comment]
Mir ist das auch nicht aufgefallen. Und dabei trag ich immer Brille und bin an der Front.
Hat das so wenig Einfluss auf die Sicht?

**Comment by E-for-Eron** [comment]
Ich habe es auch nicht glauben können @BeLink13 und es gerade aufm MainServer geprüft. Ist wohl schon aktiviert, obwohl ich schwören könnte noch nie gebrochene Brillengläser durch eine Granate o.ä. bekommen zu haben für den Rest der Mission.
![20201123230732_1](https://user-images.githubusercontent.com/42243988/100020936-f4ec8e80-2de0-11eb-9887-12adc545a4df.jpg)
