### ISSUE TITLE
Hotkeys funktionieren nicht mehr

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#577]

**Comment by shukari** [comment]
Done, zwei "ifdef" ineinander gehen nicht.
Hat solange zu finden gebarucht, weil es nur in der RELEASE Version passiert... in unserem FULL_DEBUG nicht ^^

https://github.com/TacticalBaconDevs/TBMod/blob/b692d48090c49aa1772535d1124774a37e840d66/addons/main/functions/fnc_shortcuts.sqf#L78
