### ISSUE TITLE
Mk 16 (CQC) Rückstoss anpassen

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#578]
Der Rückstoss zwingt dich, die Waffe wie eine DMR zu benutzen. Aber dafür ist die Munition zu schwach gegen Panzerung. Man kann zwar Feindmunition verwenden, aber die Waffe sollte trotzdem wie eine AR benutzt werden können. Vollautomatik unspielbar in Gebäuden und man ist allgemein im Nahkampf im Nachteil gegenüber den anderen Sturmgewehren. Waffenstabilität ist einfach wichtiger als Feindmunition aufheben zu können. Würde dadurch den Waffenspezialisten etwas besser für Leute machen, die viel Unterdrückungsfeuer leisten.

Vorschlag gleich zu der Munitionskompabilität:
Allen Mk16 Varianten die Möglichkeit geben Feindmunition zu laden, aber dafür nur den Rückstoss der MK16 CQC anpassen. 

Ansonsten ist meiner Meinung nach der Munitionsträger momentan die bessere Wahl. 
Mehr Munition und eine einfacher zu nutzende Waffenauswahl. 
7.62 ist momentan gegen die Feindpanzerungen nicht merklich effektiver als 5.56, 
weshalb Waffenkontrolle wichtiger ist, für schnelle Kopfschüsse.

**Comment by E-for-Eron** [comment]
@mordl wird in #581 behandelt. Ist noch keine zufriedenstellende Lösung für mich, da sie nun jeder anderen Waffen vorgezogen wird. Allgemeine Rückstoßanpassungen von Shukari und mir werden in mittlerer Zukunft das Problem aber angehen. Möglicherweise müssen noch komplett andere Anpassungen vorgenommen werden, um die Waffen in die Balance zu bringen. Vorschläge gerne an mich. 

Es sollten bereits alle Mk16 Varianten die Möglichkeit haben Feindmunition aufzunehmen. Welche kann es denn nicht?

Mk16 = 5.56 STANAG + 5.45mm 
Mk17 = 7.62 STANAG + 7.62mm

**Comment by mordl** [comment]
Ich habe die Mk16 Varianten getestet. Das mit der Munition war eine Falschinformation. 
Balancing ist schwierig bei der MK16, weil es nur zu stark, oder zu schwach gibt.
Aber genau das sollte meiner Meinung nach der WS sein mit den Mk16 Varianten. 
Eine Rolle die bessere Waffen+Visiere zu Verfügung hat. Er hat sonst nichts anderes momentan.
Die Standard 5.56 Waffen die jede andere Rolle hat, sollte ihn gar nicht interessieren.
Da bleibt nur die Mk16 5.56. Aber jede andere Rolle ist mit ihrer 5.56 besser im Treffen als der WS,
was in meinen Augen keinen Sinn macht. Jede andere 7.62 Waffe des WS hat weniger Rückstoss als die Mk16 5.56 (Außer MK16, 7.62).
