### ISSUE TITLE
NLAW einbauen?

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#592]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 
- NLAW ist ein One-Use Werfer mit integriertem Entfernungsmesser, NV-Sicht, Sichtverfolgung und möglichen TopDown Angriff
- Gewicht mit ca 12,5kg sehr hoch (Javelin inkl Rakete=16kg)
- Freigabe für alle O-U Träger
- Werfer kann in TopDown KPz zerstören
- Sichtverfolgung bedeutet, dass man ein sich mit konstanter Geschwindigkeit und gleichem Vektor bewegendes Fahrzeug verfolgen kann und die Rakete eine Kurve fliegt, um vorausberechneten Einschlagspunkt zu erreichen
- 800m Reichweite für Sichtverfolgung
- 1200m maximale Reichweite
- füllt die Lücke zwischen Javelin, MWAAS und M135 HP
- jegliche Werte können nach Wunsch angepasst werden

**Comment by mordl** [comment]
Sieht für mich ausbalanciert aus. Ich habe keine Einwände.

**Comment by IDarky** [comment]
Würde mir nicht gefallen als AT-Schütze. Zu stark für nicht AT. Zudem sieht er recht stark nach Vanilla aus und passt äußerlich nicht zu dem derzeitigen USA Erscheinungsbild.

**Comment by E-for-Eron** [comment]
Camouflage kann angepasst werden, wenn erwünscht. Die Form ist vorgegeben und realistisch.
Du trägst 12.5kg zusätzlich mit dir rum.... wenn du bereits 30kg als Nicht-Munitionsträger/-ATler auf dem Rücken schleppst, wirst du nicht mit dem Trupp normal mithalten können. Dementsprechend kann das nur in Fahrzeugen o.Ä. mitgeführt oder kurze Distanzen getragen werden. Ein AT Schütze hat HE, HEDP und HP Munition und kann damit auf alle Gefahren reagieren und zwar über die Länge der Mission. Den NLAW will man nicht für einen Tactical verwenden, noch mehrere Kilometer lang schleppen.

**Comment by E-for-Eron** [comment]
Nochmals als Hinweis: die NLAW soll nur in bestimmten Situationen den AT-Schützen ersetzen und damit eine andere Funktion als normale O-U Werfer übernehmen.
In einer Missionen mit mehreren feindlichen Fahrzeugen soll ein AT Schütze genutzt werden, wenn die Fahrzeuge nicht durch einfache O-U Werfer, HEDP Granaten etc ausgeschaltet werden könnten. Im Falle einer Mission mit nur einem einzelnen KPz aber sonst leichten Fahrzeugen war die Notwendigkeit eines AT Schützen nötig, da der M136 nicht ausreicht für einen KPz. Für solche Fälle soll die NLAW dienen. Bei Gegenstimmen bitte kommentieren. Mit Darky ist bereits alles abgesprochen.

**Comment by shukari** [comment]
Sehe kein Problem erstmal, wie immer zum test rein, dann Urteil bilden.
