### ISSUE TITLE
Munitionsträger - Waffenspezialist

### ISSUE THREAD

**Issue by E-for-Eron** [TacticalBaconDevs/TBMod#593]
@TacticalBaconDevs/developer @TacticalBaconDevs/helper 
Ich wurde angefragt, dem WSP die O-U Werfer wieder zu geben, dem Munitionsträger sie dafür zu nehmen, aber den Mörser bei Zweiterem zu belassen. Der Munitionsträger sei aktuell ein zu starker Allrounder, da er bis auf 7.62mm Waffen in allem besser ist als ein WSP.
Ich bin damit einverstanden. Gegenstimmen/Gegenargumente?

**Comment by mordl** [comment]
Macht in meinen Augen Sinn. Ich fand es ohne hin komisch, warum ein vollgepackter MT noch einen O-U Werfer mitnehmen soll. Der WS sollte durch seine Mk16/17 ein Selbstversorger von Munition sein, weshalb er an sich weniger Gewicht hat als ein MT und die O-U-Werfer mit weniger Problemen noch unterbringen kann.
