### ISSUE TITLE
Sanibaukiste

### ISSUE THREAD

**Issue by shukari** [TacticalBaconDevs/TBMod#60]
Sanibaukiste Wunsch von Ray Ideen shukari per Mail

**Comment by shukari** [comment]
Du kannst die Zusammenstellung auch als Ordner ablegen, ist dann im Editor unter "Eigene Zusammenstellung zu finden" bei mir liegt der Ordner hier: C:\Users\Ray\Documents\Arma 3\compositions

Die Karte ist die stinknormale "Wüste"

für die Logistik und Ärzte gibt es immer wieder mal Leerlauf, es wäre schön,
wenn wir noch eine Baukiste für das Einrichten einer Sanitätszone hätten.
Das Ganze dient weniger einem Zweck als mehr für Beschäftigung und
Atmosphäre. Ich habe mal einige Objekte zusammengestellt, welche die Kiste
beinhalten könnte. Wäre es möglich so eine mit zu integrieren? Anbei der
Link zu meinem Vorschlag. Es enthält den Ordner mit der Zusammenstellung
oder alternativ eine mission.sqm mit den Objekten.

https://drive.google.com/open?id=1FDp_ANy0fH9aBdbLcRTOUk0MrKTEraxk

LG Rainer

**Comment by IDarky** [comment]
Setze mich dran folglich muss ich diese Dateien bearbeiten.
CfgVehicles  (building)
CfgWeapons (Building)
CfgVehicles (Nachschub)
