### ISSUE TITLE
Anpassung des RUSS Arsenals

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#61]
### Habe mich mit unserem RUSS Arsenal befasst und bin dafür es stark anzupassen. 

**Grund:**
Ich finde es in der bisherigen Form noch zu komplex, da es zuviele Uniformen und dazugehöriges Equipment besitzt. Da wir nur selten das RUSS Arsenal benutzen macht es Sinn es simpler aufzubauen. 
Zudem sind ein sind ein paar nicht notwendige Versionen von Waffen dabei.

**Ziel:**
- Nur noch eine Uniform+ Anpassung des Equipments. Dabei wird der Sinn und Zweck einer Tarnfarbe ignoriert 
_[Ich habe noch ein bisschen mit der Gorka (Yellow) experimentiert, aber fand es am Ende visuell nicht so gut wie die Sommer Ausrüstung.]_
- Leichte Anpassung von Basiswaffen bzw. Versionen + Zubehör
- Equipment besteht aus einer Balance zwischen Traglast und Gewicht, damit ist die Aufteilung des Equipments zwischen den Klassen nicht notwendig, außer zur weiteren Verbesserung der Übersicht

**Durchführung:**
- Alle Uniformen außer EMR-Sommer entfernen
- Entfernung von folgenden Waffen + Zubehör:
rhs_weap_ak74m_2mag
rhs_weap_ak74m_2mag_camo
rhs_weap_ak74m_desert_folded
rhs_weap_ak74m_camo_folded
rhs_weap_ak74m_folded
rhs_weap_ak74m_desert
rhs_weap_ak74m_camo
rhs_weap_asval
rhs_weap_svdp_wd
rhs_weap_svds
rha_acc_1p63
rhs_30Rnd_545x39_AK
rhs_weap_rpg26_used
rhs_weap_rsp30_white
rhs_weap_rsp30_green
rhs_weap_rsp30_red

- Hinzufügen Zubehör:
rhs_30Rnd_545x39_AK_plum_green

- Liste der Gegenstände die bei Weste, Kopf und Rucksack im Arsenal sein sollen:
Weste:
rhs_6b23_6sh116
rhs_6b23_6sh116_vog
rhs_6b23_digi_6sh92_Spetsnaz
rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz
rhs_6b23_digi_6sh92_Vog_Spetsnaz
rhs_6b43

Helme:
rhs_6b7_1m_emr
rhs_6b7_1m_bala1_emr
rhs_6b7_1m_bala2_emr
rhs_6b7_1m_emr_ess
rhs_6b7_1m_emr_ess_bala
rhs_fieldcap_digi2
Falls für Kommando oder Zeus benötigt:
rhs_beret_mp2

Rucksäcke:
B_Carryall_di
B_Kitbag_rgr
B_TacticalPack_oli
B_UAV_01_backpack_F
rhs_assault_umbts
TFAR_rt1523g_bwmod
TFAR_rt1523g_big_bwmod

-Folgende Accesoires hinzufügen:
G_Balaclava_combat
G_Balaclava_lowprofile
G_Balaclava_Tl_tna_F
G_Balaclava_Tl_G_tna_F
G_Balaclava_blk_F
G_Balaclava_G_blk_F
G_Combat
G_Combat_Googles_tna_F
G_lowprofile

-Defaultlayout für alle Klassen setzen:
[[],[],[],["rhs_uniform_emr_patchless",[["ACE_fieldDressing",10],["ACE_CableTie",1],["ACE_MapTools",1],["ACE_morphine",5],["ACE_tourniquet",4],["ACE_quikclot",10]]],[],[],"rhs_fieldcap_digi2","",[],["","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]

Fotos:
https://steamcommunity.com/profiles/76561198074489907/screenshots/

**Comment by mordl** [comment]
Die Frage könnte etwas groß sein, aber würde Interesse bestehen die RUSS Fraktion zu einer Art PMC Einheit mit "erweiterten fragwürdigen Dienstleistungszweig" zu ändern? Die Missionen sollten sich von den der USA und BW unterscheiden z.B. Schwarzmarktwaffenhandel durchführen, VIP oder wichtige Gegenstände beschützen/extrahieren, Destabilisierungsmissionen,... Würde den Zeitraum dieser Missionen in der Moderne bzw. 20Jh. ansiedeln mit Zugriff auf unterschiedliche Waffensysteme. Ziel wäre es eine starke Abwechslung in die Missionen zu bringen mit komplett neuen Erfahrungen.

**Comment by shukari** [comment]
Klingt interessant, würde dafür aber ein eigenes Arsenal dann machen.
Ggf das Themen Arsenalsystem nutzen.

Hast mal Zeit, das ich dir erkläre wir du selbst Arsenale anpassen kannst?

**Comment by IDarky** [comment]
@shukari Würde auch meine Hilfe anbieten. Ggf. @mordl  das Arsenal erklären

**Comment by shukari** [comment]
@mordl hat gestern ne Git schnell Einweisung erhalten. Könnt euch gerne zusammen setzen.

Mir ist nur wichtig, das es ein NORMALES Russen Arsenal gibt und dann ggf das PMC angepasste als Spezial aka Themenarsenal

**Comment by shukari** [comment]
Kleine Änderungen = bestehendes Arsenal anpassen
Große Änderungen = neues zusätzlich
