### ISSUE TITLE
Vanilla Cargo Inventare werden nicht mehr richtig gelöscht.

### ISSUE THREAD

**Issue by LuGoPaTB** [TacticalBaconDevs/TBMod#610]
Seit ca. 2 Wochen werden die vorgeladenen Items in den Vanilla Inventaren nicht mehr entfernt. Sowohl Fahrzeug/Flugzeuge als auch Kisten die nichts haben sollten. Das kam in etwa mit den Warrior Änderungen.

**Comment by shukari** [comment]
Einmal bitte im Editor ein Fahrzeug neu setzen und unter Ausrüstung lager schauen ob was bei Inventar löschen steht ist das angehackt und wie heißt der punkt

**Comment by LuGoPaTB** [comment]
![grafik](https://user-images.githubusercontent.com/68504544/109867143-71a3ca00-7c66-11eb-8984-054111ed6c85.png)
![grafik](https://user-images.githubusercontent.com/68504544/109867214-82544000-7c66-11eb-906b-f688008a13a5.png)
