### ISSUE TITLE
init.sqf Blacklistrollen und Customname

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#664]
Die Init in der Mission pbo soll in der Lage sein:

- Rollen zu Blacklisten für eine Mission
- Rollen umzubenennen für eine Mission

TB_blacklistRollen
TB_customName

**Comment by shukari** [comment]
https://github.com/TacticalBaconDevs/TBMod/wiki/SkripteSammlung#rollen-blockieren-f%C3%BCr-missionbauer

im nächsten Update
