### ISSUE TITLE
Current Issues

### ISSUE THREAD

**Issue by Kili-97** [TacticalBaconDevs/TBMod#690]
- [x] Ferngläser fehlen bei Standard rollen (USA) (hatten wir je welche? das Vanilla Arsenal hat es)
- [x] Skript Fehler

![image](https://github.com/TacticalBaconDevs/TBMod/assets/42013222/9684c103-39a8-4932-a3bf-1a08fcf2d7e3)

**Comment by shukari** [comment]
beide Ferngläser haben jetzt ein rhs_ davor, deswegen ^^
