### ISSUE TITLE
SlingLoad System Verbessern

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#73]
@Er1807  Es wäre cool wenn du einbauen könntest, das nur noch der Pilot die Seile abwerfen kann. Grund hierfür ist das wenn sich der Helikopter vorwärts nach unten bewegt und dann die Crew ein Seil abwirft, sich der Helikopter auf die Seite dreht und der Absturz nicht mehr zu verhindern ist.

**Comment by IDarky** [comment]
https://youtu.be/0yhQopmvqh4

**Comment by shukari** [comment]
Bearbeitung erfolgt in #67 
zudem:
- Sprache auf deutsch ändern
- "Drop Rope" nur anzeigen wenn es auch geht
- Auf Lastenseil ändern damit Unterscheidung zu FastRope

**Comment by Er1807** [comment]
Kümmer mich drum. Frag mich trotzdem wieso man so etwas überhaupt probiert. Besonders beim 2ten Beispiel.

**Comment by Er1807** [comment]
@shukari "Drop Rope" nur anzeigen wenn es auch geht 
Was meinst du damit? Dafür gibt es doch keine Beschränkungen. Außer in der Luft und jetzt auch nur Fahrer

**Comment by shukari** [comment]
@Er1807 Warum sollte man das anzeigen wenn nicht mal irgendein Seil von dir da ist. So ist es derzeit und deswegen die condition so bearbeiten das man nur Dropen kann wenn man Seile aktiv hat, damit es keine unnötige Option gibt und nicht solche drehbugs entstehen können.

**Comment by Er1807** [comment]
War vlt. ne schlechte Übersetzung. Drop Rope hat ein Sein erschaffen nicht wieder gelöscht. @shukari  Cut Rope wird nur angezeigt wenn Seile vorhanden sind.

**Comment by IDarky** [comment]
> Kümmer mich drum. Frag mich trotzdem wieso man so etwas überhaupt probiert. Besonders beim 2ten Beispiel.

@Er1807  Drei 2 test war um eindeutig beweisen zu können das es vom sling load kommt. Beim ersten mal wurde es in einer mission mit fast rope verwechselt
