### ISSUE TITLE
Problem mit Inkognito Script

### ISSUE THREAD

**Issue by IDarky** [TacticalBaconDevs/TBMod#76]
[arma3_x64_2018-11-06_19-37-53.zip](https://github.com/TacticalBaconDevs/TBMod/files/2555220/arma3_x64_2018-11-06_19-37-53.zip)

**Comment by shukari** [comment]
Problem gefunden... die Arsenalrolle wurde falsch gesetzt, da darky aus einem alten Stand versucht hat zu laden... dadurch hat der Crashhelfer das gespeichert und so war das problem die ganze Zeit da.
Behoben dadurch das man einfach keine alten Daten nimmt und am Anfang der Mission der Cache gelöscht wird.
