### ISSUE TITLE
SMAW Nachladen durch andere Personen geht nicht

### ISSUE THREAD

**Issue by Er1807** [TacticalBaconDevs/TBMod#77]
see Title

**Comment by shukari** [comment]
Wie man hier sieht https://github.com/acemod/ACE3/blob/2c9b2bff77f13e312ef72c74c7eff0b41ffff279/optionals/compat_rhs_usf3/CfgWeapons.hpp#L226-L229 
ist reloadLaunchers eigl für diese Klasse aktiviert, müssen dann nochmal schauen was da los ist.
