### ISSUE TITLE
Fehleranzeige mit Griffen bei M4 Varianten

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#86]
Bei den M4 Varianten kommt es zu einer Fehleranzeige, wenn ein Griff ausgerüstet wird.

https://steamcommunity.com/sharedfiles/filedetails/?id=1567112961

**Comment by shukari** [comment]
Reported to rhs http://feedback.rhsmods.org/view.php?id=4741
Weißt du wann der Fehler kommt, also was du tun musst um es zu reproduzieren?

**Comment by mordl** [comment]
Passiert beim De-/Montieren eines Griffs über das Spielerinventar.

**Comment by shukari** [comment]
Wird in der nächsten RHS Version gefixt
