### ISSUE TITLE
M4... Varianten entfernen

### ISSUE THREAD

**Issue by mordl** [TacticalBaconDevs/TBMod#87]
Einfach, weil sie keinen Sinn machen. Wir benutzen sowieso eigene Griffe.

**Comment by IDarky** [comment]
Einmal die classnames von den Waffen die du meinst.

**Comment by mordl** [comment]
Werde doch nicht alle Varianten, welche den Magpullstock besitzen entfernen. Habe da etwas falsch gelesen.

Stattdessen schlage ich eine Liste von Waffen vor die wir testweise ausklammern sollten aus dem Arsenal und schaun, ob jmd ihnen nachweint:

rhs_weap_m16a4
Ironsight von Handgriffversion ist besser.

rhs_weap_m4 
rhs_weap_m4_(Varianten) 
Sind schwerer als M4A1 Varianten ohne irgendwelche Vorteile.

rhs_weap_m4a1
rhs_weap_m4a1_mstock
Handgriffversionen besitzen besseres Ironsight.


Für Grenadier und TF:

1. Entfernen folgender Waffen:
rhs_weap_m4_m320
rhs_weap_m4_m203
rhs_weap_m4_m203S
rhs_weap_m4a1_carryhandle_m203
rhs_weap_m4a1_carryhandle_m203S
rhs_weap_m4a1_m203
rhs_weap_m4a1_m203S
rhs_weap_mk18 (War von mir, kann raus)

Grund:
Die 203 ULGs können nur bis 250m eingestellt werden.
Die 320 ULGs können bis 350m eingestellt werden.
Ich würde aber nur die oben genannten erstmal entfernen, da bereits dafür 320er Varianten vorhanden sind. M4 Varianten wieder komplett wegen den schon oben genannten Grund.
Außerdem wird der ULG Ironsight von manchen Visieren bei den 203er teilweise blockiert, weil sie sich nicht an der Seite sondern auf der Waffe befinden.

2. Waffe hinzufügen:
rhs_weap_m4a1_d 

Grund:
Ist eine Waffe die ich in Zukunft öfter benutzen möchte. 
Sie ersetzt die Mk18.

**Comment by IDarky** [comment]
> 1.Entfernen folgender Waffen:

Nicht notwendig. Sehen alle unterschiedlich aus. Wir legen Fokus darauf das Spieler sich individualisieren können.

> 2. Waffe hinzufügen

Ist beim Schützen bereits vorhanden. Der TF hat bereits die GL Variante.
@shukari @mordl

**Comment by shukari** [comment]
Die MK18 werde ich nicht entfernen, ist meine Mainwaffe 😄
