### ISSUE TITLE
Ideen zum EOS Modul [Cullis Wünsche 2.0]

### ISSUE THREAD

**Issue by Culli-TB** [TacticalBaconDevs/TBMod#92]
1. ~~Höhen und Richtungsangaben inkl. Random für Helikopter (Wie hoch und aus welcher Richtung soll der Helikopter kommen). _In beiden Module._~~
2. ~~Richtungsangabe inkl. Random für Bodentruppen (Aus welcher Richtung sollen die Bodentruppen kommen). _Nur im EOS-Bastion Modul._~~
3. ~~With- und Blacklist (Spezielle Glassnames die gespawnt oder eben nicht gespawnt werden sollen).
_In beiden Module._~~
4. ~~Einheiten nach x min. autom. Löschen wenn alle Tod. _In beiden Module._~~
5. Optimierungen (ggf. Positionen cachen? denke das Position suchen zieht die Leistung)
6. Aufgaben aus #118

**Comment by shukari** [comment]
**1. und 2.** fertig
**zu 3.** wird das wirklich benötigt, man kann doch in der unitPools Datei einfach alles schnell ändern wenn man möchte, eine Blacklist ist kein Problem, eine Whitelist ist ein Problem, da ich nicht weißt was die Klasse dann ist, Man, Schiff oder Heli usw. Gib mal bescheid ob das benötigt wird und wenn ob nur ne Blacklist reicht!
**zu 4.** verstehe ich nicht.  Löschen wenn was? Wer Tod? Wenn die Gegner Tod sind warum löschen, wenn wir Tod sind wird die Zone gecached. Bitte nochmal erklären ;D

**Comment by Culli-TB** [comment]
Withelist und Blacklist muss nicht sein. Hast recht, kann man im Pool machen.
Punkt 4 ist auch nicht notwendig. 
Alles bestens 👍
